{
  "hash": "04e96b2808897467c6f80ba12e8f3927",
  "result": {
    "markdown": "---\ntitle: \"2023-02-06 Sessión 1\"\nformat: \n  html:\n    self-contained: true\n    theme: cosmo\neditor: visual\n---\n\n\n-   Instituut Voor Tropische Geneeskunde - Antwerp, Belgium\n-   Javier Silva-Valencia\n\n## Step by Step - Selection of variables for modeling\n\n##### Import data\n\nImporting a CSV database under the name of \"onch1302\", with \",\" as separator:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nonch1302 <- read.csv(\"C:/Users/pined/OneDrive - Universidad Nacional Mayor de San Marcos/Javier 2022/Belgica/AC2/Logistic Regresion Exercise Database/Datasets/onch1302.csv\", sep=\",\")\n```\n:::\n\n\n------------------------------------------------------------------------\n\n------------------------------------------------------------------------\n\n### Starting the Exercise (MVA_LogReg_Ex1-2023):\n\n<sub> Onchocerciasis (commonly known as River Blindness) is a chronic filarial disease found in sub-Saharan Africa and some parts of Central and South America. An onchocerciasis project was set up in 1982 in the Bo district of Sierra Leone. The aims of the project were to study epidemiological, clin-ical, immunological and entomological aspects of the disease. Prevalence surveys were undertaken in villages selected on the basis of potential high endemicity, being situated on or near rivers which are the breeding sites for the Simulium damnosum blackfly. Of the twelve villages included in the present dataset, five were situated in the south and east of the country in the `forest' zone and the other seven were in the`savannah' zone of the country. A census was taken of each village, and all villagers over the age of five years were asked to participate in the study. Coverage was over 90% in all but one of the selected villages. Diagnosis was made by taking a skin-snip, and clinical and an ocular examination were also performed. The file ONCH1302 contains data for all 1,302 subjects. </sub>\n\n###### 1. To make the naming a bit more logical, copy the 'sex' variable into a new variable called 'female' and the 'area' variable into one called 'forest'. For 'mf' and 'lesions' you may use the variables as is. Next, recode variables with more than 2 levels ('agegrp' and 'mfload') to binary variables. For 'agegrp' use 'adult' and code as 'TRUE' for those aged 20 and older, 'FALSE' for those under 20 years of age. For 'mfload' you can recode to 'highload' taking values 0 and 1 together as 'FALSE' and values 2 and 3 together as 'TRUE\n\nCreating the new variables (as a copy)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nonch1302$female <- onch1302$sex\nonch1302$forest <- onch1302$area\n```\n:::\n\n\nRecoding the variables with more than 2 levels into binary variables\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Adult variable (adult=1, non adult=0)\n  onch1302$adult <- ifelse(onch1302$agegrp>1,1,0)\n\n#Highload (False = 0, True=1)\n  #table(onch1302$mfload, useNA = \"always\")\n  onch1302$highload <- 0\n  onch1302$highload[onch1302$mfload==2] <- 1\n  onch1302$highload[onch1302$mfload==3] <- 1\n```\n:::\n\n\n###### 2. Get an overview of the data by univariable analysis. Construct a table showing numbers and frequencies of each of the variables\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(onch1302$lesions, useNA = \"always\")     #frecuency\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   0    1 <NA> \n1101  201    0 \n```\n:::\n\n```{.r .cell-code}\nprop.table(table(onch1302$lesions))           #proportion\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n        0         1 \n0.8456221 0.1543779 \n```\n:::\n\n```{.r .cell-code}\ntable(onch1302$female, useNA = \"always\")     #frecuency\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   0    1 <NA> \n 616  686    0 \n```\n:::\n\n```{.r .cell-code}\nprop.table(table(onch1302$female))           #proportion\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n        0         1 \n0.4731183 0.5268817 \n```\n:::\n\n```{.r .cell-code}\n#Forest\ntable(onch1302$forest, useNA = \"always\")     #frecuency\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   0    1 <NA> \n 548  754    0 \n```\n:::\n\n```{.r .cell-code}\nprop.table(table(onch1302$forest))           #proportion\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n        0         1 \n0.4208909 0.5791091 \n```\n:::\n\n```{.r .cell-code}\n#Highload\ntable(onch1302$highload, useNA = \"always\")     #frecuency\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   0    1 <NA> \n 847  455    0 \n```\n:::\n\n```{.r .cell-code}\nprop.table(table(onch1302$highload))           #proportion\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n        0         1 \n0.6505376 0.3494624 \n```\n:::\n\n```{.r .cell-code}\n#Adult\ntable(onch1302$adult, useNA = \"always\")     #frecuency\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   0    1 <NA> \n 420  882    0 \n```\n:::\n\n```{.r .cell-code}\nprop.table(table(onch1302$adult))           #proportion\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n        0         1 \n0.3225806 0.6774194 \n```\n:::\n\n```{.r .cell-code}\n#Microfilaria\ntable(onch1302$mf, useNA = \"always\")     #frecuency\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   0    1 <NA> \n 480  822    0 \n```\n:::\n\n```{.r .cell-code}\nprop.table(table(onch1302$mf))           #proportion\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n        0         1 \n0.3686636 0.6313364 \n```\n:::\n:::\n\n\n::: callout-note\n| Factor                   | N          |\n|--------------------------|------------|\n| Female gender            | 686 (52.7) |\n| Adult age                | 882 (67.7) |\n| Living in Forest         | 754 (57.9) |\n| Micro filaria infected   | 822 (63.1) |\n| High micro-filarial load | 455 (34.9) |\n| Eyes affected (lesions)  | 201 (15.4) |\n:::\n\n###### 3. Make three 2x2 tables to explore the association between mf infection and the three exposures, 'female', 'adult' and 'forest' and manually compute the odds ratios between exposed and unex-posed\n\n<sub> We can do that directly with \"cc\" command from the EpiStat library. If EpiStat doesnt work you can do it manually with \"table\" command and a calculator </sub>\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(EpiStats)\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ncc(onch1302, mf,female)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n$df1\n                   Cases Controls Total\nExposed              396      290   686\nUnexposed            426      190   616\nTotal                822      480  1302\nProportion exposed  0.48     0.60  0.53\n\n$df2\n                Point estimate 95%CI-ll 95%CI-ul\nOdds ratio                0.61     0.48     0.77\nPrev. frac. ex.           0.39     0.23     0.52\nPrev. frac. pop           0.24       NA       NA\nchi2(1)                  18.22       NA       NA\nPr>chi2                  0.000       NA       NA\n```\n:::\n:::\n\n\n::: callout-note\n|        | Micro filaria infected |     |\n|--------|------------------------|-----|\n| Gender | Yes                    | No  |\n| Female | 396                    | 290 |\n| Male   | 426                    | 190 |\n\nOR (female) = 0.61 (0.48-0.77) p value = 0.0001\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncc(onch1302, mf,adult)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n$df1\n                   Cases Controls Total\nExposed              677      205   882\nUnexposed            145      275   420\nTotal                822      480  1302\nProportion exposed  0.82     0.43  0.68\n\n$df2\n                Point estimate 95%CI-ll 95%CI-ul\nOdds ratio                6.26     4.82     8.15\nAttr. frac. ex.           0.84     0.79     0.88\nAttr. frac. pop           0.69       NA       NA\nchi2(1)                 218.04       NA       NA\nPr>chi2                  0.000       NA       NA\n```\n:::\n:::\n\n\n::: callout-note\n|      | Micro filaria infected |     |\n|------|------------------------|-----|\n| Age  | Yes                    | No  |\n| 20+  | 677                    | 205 |\n| 1-19 | 145                    | 275 |\n\nOR (female) = 6.26 (4.82-8.15) p value = 0.0001\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncc(onch1302, mf,forest)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n$df1\n                   Cases Controls Total\nExposed              541      213   754\nUnexposed            281      267   548\nTotal                822      480  1302\nProportion exposed  0.66     0.44  0.58\n\n$df2\n                Point estimate 95%CI-ll 95%CI-ul\nOdds ratio                2.41     1.90     3.06\nAttr. frac. ex.           0.59     0.47     0.67\nAttr. frac. pop           0.39       NA       NA\nchi2(1)                  57.15       NA       NA\nPr>chi2                  0.000       NA       NA\n```\n:::\n:::\n\n\n::: callout-note\n|           | Micro filaria infected |     |\n|-----------|------------------------|-----|\n| Residence | Yes                    | No  |\n| Forest    | 541                    | 213 |\n| Savanna   | 281                    | 261 |\n\nOR (female) = 2.41 (1.90-3.06) p value = 0.0001\n:::\n\n###### 4. As a next step, use the 'cc' command from the 'Epistats' package to confirmm the associations between 'mf' and exposures 'female', 'adult' and 'forest' and add the 95% confidence intervals. Are these associations statistically significant? Who are more at risk, men or women?\n\n::: callout-note\nWe did this in the previous step.\n\n|           | Number (%) | OR (95% CI)   |\n|-----------|------------|---------------|\n| Female    | 686 (52.7) | 0.6 (0.5-0.8) |\n| Adult age | 883 (67.7) | 6.3 (4.8-8.2) |\n| Forest    | 754 (57.9) | 2.4 (1.9-3.1) |\n\nAll bivariate associations are significant\n:::\n\n###### 5. Now compare results from table-based analyses with results from logistic regression. Are they consistent? For each of the three models note the OR and it's 95% CI\n\n<sub> Now we are going to calculate the OR again but with the logistic regression </sub>\n\n5.1. mf and female\n\n\n::: {.cell}\n\n```{.r .cell-code}\nGLM1 <- glm(mf ~ female, family=binomial, data=onch1302)\n  summary(GLM1)                   # To see the results of the logistic regression\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = mf ~ female, family = binomial, data = onch1302)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-1.5338  -1.3122   0.8589   1.0483   1.0483  \n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept)  0.80742    0.08724   9.255  < 2e-16 ***\nfemale      -0.49588    0.11655  -4.255 2.09e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1714.1  on 1301  degrees of freedom\nResidual deviance: 1695.7  on 1300  degrees of freedom\nAIC: 1699.7\n\nNumber of Fisher Scoring iterations: 4\n```\n:::\n\n```{.r .cell-code}\n  exp(coef(GLM1))                 # To calculate the OR\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n(Intercept)      female \n  2.2421053   0.6090335 \n```\n:::\n\n```{.r .cell-code}\n  exp(confint(GLM1))              # To calculate the confidence intervarl of the OR\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWaiting for profiling to be done...\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n                2.5 %    97.5 %\n(Intercept) 1.8930554 2.6654704\nfemale      0.4842344 0.7647899\n```\n:::\n:::\n\n\n5.2. mf and adult\n\n\n::: {.cell}\n\n```{.r .cell-code}\nGLM2 <- glm(mf ~ adult, family=binomial, data=onch1302)\n  summary(GLM2)                   # To see the results of the logistic regression\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = mf ~ adult, family = binomial, data = onch1302)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-1.7083  -0.9203   0.7274   0.7274   1.4584  \n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept)  -0.6400     0.1026  -6.236 4.48e-10 ***\nadult         1.8347     0.1300  14.118  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1714.1  on 1301  degrees of freedom\nResidual deviance: 1497.8  on 1300  degrees of freedom\nAIC: 1501.8\n\nNumber of Fisher Scoring iterations: 4\n```\n:::\n\n```{.r .cell-code}\n  exp(coef(GLM2))                 # To calculate the OR\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n(Intercept)       adult \n  0.5272727   6.2632464 \n```\n:::\n\n```{.r .cell-code}\n  exp(confint(GLM2))              # To calculate the confidence intervarl of the OR\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWaiting for profiling to be done...\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n                2.5 %    97.5 %\n(Intercept) 0.4302207 0.6435193\nadult       4.8647343 8.0981555\n```\n:::\n:::\n\n\n5.3. mf and forest\n\n\n::: {.cell}\n\n```{.r .cell-code}\nGLM3 <- glm(mf ~ forest, family=binomial, data=onch1302)\n  summary(GLM3)                   # To see the results of the logistic regression\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = mf ~ forest, family = binomial, data = onch1302)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-1.5900  -1.1992   0.8148   0.8148   1.1558  \n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept)  0.05111    0.08546   0.598     0.55    \nforest       0.88102    0.11767   7.487 7.05e-14 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1714.1  on 1301  degrees of freedom\nResidual deviance: 1657.0  on 1300  degrees of freedom\nAIC: 1661\n\nNumber of Fisher Scoring iterations: 4\n```\n:::\n\n```{.r .cell-code}\n  exp(coef(GLM3))                 # To calculate the OR\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n(Intercept)      forest \n   1.052434    2.413363 \n```\n:::\n\n```{.r .cell-code}\n  exp(confint(GLM3))              # To calculate the confidence intervarl of the OR\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWaiting for profiling to be done...\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n                2.5 %   97.5 %\n(Intercept) 0.8901384 1.244620\nforest      1.9176644 3.042055\n```\n:::\n:::\n\n\n::: callout-note\nYes, the OR calculated with logistic regresion it is consistent with the OR calculated in step 4\n\n|           | Number (%) | OR (95% CI)   |\n|-----------|------------|---------------|\n| Female    | 686 (52.7) | 0.6 (0.5-0.8) |\n| Adult age | 883 (67.7) | 6.3 (4.8-8.2) |\n| Forest    | 754 (57.9) | 2.4 (1.9-3.1) |\n:::\n\n###### 6. The only exposure that we could do something about in an intervention is 'living in the forest', do you think age or gender could be confounders in the association between 'living in the forest' and being infected with micro filaria?\n\n::: callout-note\nYes it could be confounders.\n\nClarification:\n\n    To being counfunders has to fulfill 3 conditions:\n    1. Has to be related to the VI, 2. TO be related to the VD, and 3. Not be in the causal pathway\n                \n                (Microfilaria Infection) ----- (living forest)\n                                     \\           /\n                                      Confounders\n                                     (Age or gender)\n                                     \n    If it is permant residence, then probably age or gender cannot affect the residence\n    But in this case it doesn't say anything.\n\n    If adult men spend part of the year in the forest for professional reasons, \n    both age and gender could be associated with living in forest and with having microfilaria infect.\n\n    Also age or gender do not seem to be in the causar pathway\n:::\n\n###### 7. Use 'CCInter' from the 'Epistats' package to test for confounding. Is there confounding or inter-action in the association between 'mf' and 'forest' by either 'female' or 'adult'?\n\n7.1 Confounding: being female\n\n::: {style=\"font-size:14px\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nCCInter(onch1302, \"mf\", \"forest\", \"female\") \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n$df1\n   CCInter mf - forest by(female) Cases Controls          P.est. Stats 95%CI-ll\n1                      female = 1  <NA>     <NA>      Odds ratio  2.87     2.07\n2                         Exposed   265      120 Attrib.risk.exp  0.65     0.52\n3                       Unexposed   131      170 Attrib.risk.pop  0.44     <NA>\n4                           Total   396      290                  <NA>     <NA>\n5                       Exposed % 66.9%    41.4%                  <NA>     <NA>\n6                  ______________  <NA>     <NA>                  <NA>     <NA>\n7                      female = 0  <NA>     <NA>      Odds ratio  1.92     1.34\n8                         Exposed   276       93 Attrib.risk.exp  0.48     0.25\n9                       Unexposed   150       97 Attrib.risk.pop  0.31     <NA>\n10                          Total   426      190                  <NA>     <NA>\n11                      Exposed % 64.8%    48.9%                  <NA>     <NA>\n12                 ______________  <NA>     <NA>                  <NA>     <NA>\n13                  Number of obs  1302     <NA>            <NA>  <NA>     <NA>\n14                        Missing     0     <NA>            <NA>  <NA>     <NA>\n   95%CI-ul\n1      3.97\n2      0.75\n3      <NA>\n4      <NA>\n5      <NA>\n6      <NA>\n7      2.76\n8      0.64\n9      <NA>\n10     <NA>\n11     <NA>\n12     <NA>\n13     <NA>\n14     <NA>\n\n$df2\n                        P.estimate Stats 95%CI-ll 95%CI-ul\n1 MH test of Homogeneity (p-value)  0.09                  \n2              Crude OR for forest  2.41     1.90     3.06\n3 MH OR forest adjusted for female  2.40     1.90     3.02\n4   Adjusted/crude relative change -0.75        _        _\n```\n:::\n:::\n\n:::\n\n::: callout-note\nSteps for check for confounding\n\n      1.Check for the wolf test (homogeneity test) if pvalue higher than 0.05,\n      means no interaction (no effect modifier) and that could be a confounding\n      \n      2. If is not interaction, then check for the change between OR crude and OR adjusted, \n      if that relative change is higher than 10%, it is a confounding\n      \n\nSo, with the results:\n\n      1. The Homogeneity test had a p value of 0.09 (higher than 0.05)\n      means no interaction and that could be a confounding\n      \n      2. Then, the OR crude is 2.41 and the OR adjusted 2.40. \n      Also the relative change is -0.75\n      So sex  is not a confounding\n:::\n\n7.2 Confounding: being adult\n\n::: {style=\"font-size:14px\"}\n\n::: {.cell}\n\n```{.r .cell-code}\nCCInter(onch1302, \"mf\", \"forest\", \"adult\") \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n$df1\n   CCInter mf - forest by(adult) Cases Controls          P.est. Stats 95%CI-ll\n1                      adult = 1  <NA>     <NA>      Odds ratio  3.85     2.72\n2                        Exposed   434       65 Attrib.risk.exp  0.74     0.63\n3                      Unexposed   243      140 Attrib.risk.pop  0.47     <NA>\n4                          Total   677      205                  <NA>     <NA>\n5                      Exposed % 64.1%    31.7%                  <NA>     <NA>\n6                 ______________  <NA>     <NA>                  <NA>     <NA>\n7                      adult = 0  <NA>     <NA>      Odds ratio  2.42     1.53\n8                        Exposed   107      148 Attrib.risk.exp  0.59     0.34\n9                      Unexposed    38      127 Attrib.risk.pop  0.43     <NA>\n10                         Total   145      275                  <NA>     <NA>\n11                     Exposed % 73.8%    53.8%                  <NA>     <NA>\n12                ______________  <NA>     <NA>                  <NA>     <NA>\n13                 Number of obs  1302     <NA>            <NA>  <NA>     <NA>\n14                       Missing     0     <NA>            <NA>  <NA>     <NA>\n   95%CI-ul\n1      5.46\n2      0.82\n3      <NA>\n4      <NA>\n5      <NA>\n6      <NA>\n7      3.86\n8      0.74\n9      <NA>\n10     <NA>\n11     <NA>\n12     <NA>\n13     <NA>\n14     <NA>\n\n$df2\n                        P.estimate Stats 95%CI-ll 95%CI-ul\n1 MH test of Homogeneity (p-value)  0.10                  \n2              Crude OR for forest  2.41     1.90     3.06\n3  MH OR forest adjusted for adult  3.23     2.48     4.22\n4   Adjusted/crude relative change 34.04        _        _\n```\n:::\n:::\n\n:::\n\n::: callout-note\nSo, with the results:\n\n      1. The Homogeneity test had a p value of 0.10 (higher than 0.05)\n      means no interaction and that could be a confounding\n      \n      2. Then, the OR crude is 2.41 and the OR adjusted 3.23 \n      Also the relative change is 34.04 (more than 10%)\n      So being adult is a confounding\n:::\n\n###### 8. Does logistic regression confirm your findings on \"adult\" and \"female\" as potential confounders?\n\n8.1 Logistic regresion only with: mf and forest (bivariate)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nGLM4 <- glm(mf ~ forest, family=binomial, data=onch1302)\nexp(coef(GLM4))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n(Intercept)      forest \n   1.052434    2.413363 \n```\n:::\n:::\n\n\n8.2 Logistic regresion with: mf and forest and female (multivariate)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nGLM5 <- glm(mf ~ forest + female, family=binomial, data=onch1302)\nexp(coef(GLM5))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n(Intercept)      forest      female \n  1.3739477   2.3967425   0.6165796 \n```\n:::\n:::\n\n\n8.3 Logistic regresion with: mf and forest and adult (multivariate)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nGLM6 <- glm(mf ~ forest + adult, family=binomial, data=onch1302)\nexp(coef(GLM6))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n(Intercept)      forest       adult \n  0.2427931   3.2653865   7.6328965 \n```\n:::\n:::\n\n\n8.4 Logistic regresion with: mf and forest and female and adult (multivariate)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nGLM7 <- glm(mf ~ forest + female + adult, family=binomial, data=onch1302)\nexp(coef(GLM7))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n(Intercept)      forest      female       adult \n  0.3313785   3.2577809   0.5342773   8.0289468 \n```\n:::\n:::\n\n\n::: callout-note\nThe OR of forest in model GLM4 (only with: mf and forest) is\n\n      OR (crude) = 2.413363\n\n      Interpretation: The odds of having a microfilarial infection are 2.41 times as high for those \n      who reside in the forest compared to those in the savanna.\n\nThe OR for forest in model GLM5 (with mf and forest and female) is 2.3967425 This ise quite the same with GLM4, so it confirms that adding female do not cause changes, so female it is not a confounder of (mf \\~ forest association)\n\n      Interpretation: The odds of having a microfilarial infection are 2.39 times as high for those \n      who reside in the forest compared to those in the savanna, if sex are held constant.\n\nThe OR for forest in model GLM6 (with mf and forest and adult) is 3.2653865 This OR is different from the GLM4, so it confirms that adding adult do cause changes, so being adult it is a confounder of (mf \\~ forest association)\n\n      Interpretation: The odds of having a microfilarial infection are 3.27 times as high for those \n      who reside in the forest compared to those in the savanna, if age(being adult) \n      are held constant.\n\nThe OR for forest in model GLM7 (with mf and forest and female and adult) is 3.2577809 This is different from the GLM4, so it still confirms that one of the variables added caused changes,\n\n    Interpretation: The odds of having a microfilarial infection are 3.26 times as high for those \n    who reside in the forest compared to those in the savanna, if sex and age are held constant.\n:::\n\n###### 9. What happens if you add an additional term in the 'CCInter' command, e.g. if you type: 'CCInter(Onch1302, \"mf\",\"forest\",\"adult\",\"female\")'?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nCCInter(onch1302, \"mf\", \"forest\", \"female\", \"adult\") \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n$df1\n   CCInter mf - forest by(female) Cases Controls          P.est. Stats 95%CI-ll\n1                      female = 1  <NA>     <NA>      Odds ratio  2.87     2.07\n2                         Exposed   265      120 Attrib.risk.exp  0.65     0.52\n3                       Unexposed   131      170 Attrib.risk.pop  0.44     <NA>\n4                           Total   396      290                  <NA>     <NA>\n5                       Exposed % 66.9%    41.4%                  <NA>     <NA>\n6                  ______________  <NA>     <NA>                  <NA>     <NA>\n7                      female = 0  <NA>     <NA>      Odds ratio  1.92     1.34\n8                         Exposed   276       93 Attrib.risk.exp  0.48     0.25\n9                       Unexposed   150       97 Attrib.risk.pop  0.31     <NA>\n10                          Total   426      190                  <NA>     <NA>\n11                      Exposed % 64.8%    48.9%                  <NA>     <NA>\n12                 ______________  <NA>     <NA>                  <NA>     <NA>\n13                  Number of obs  1302     <NA>            <NA>  <NA>     <NA>\n14                        Missing     0     <NA>            <NA>  <NA>     <NA>\n   95%CI-ul\n1      3.97\n2      0.75\n3      <NA>\n4      <NA>\n5      <NA>\n6      <NA>\n7      2.76\n8      0.64\n9      <NA>\n10     <NA>\n11     <NA>\n12     <NA>\n13     <NA>\n14     <NA>\n\n$df2\n                        P.estimate Stats 95%CI-ll 95%CI-ul\n1 MH test of Homogeneity (p-value)  0.09                  \n2              Crude OR for forest  2.41     1.90     3.06\n3 MH OR forest adjusted for female  2.40     1.90     3.02\n4   Adjusted/crude relative change -0.75        _        _\n```\n:::\n:::\n\n\n::: callout-note\nWhat happened? Nothing. Only worked with female, doesn't show anything about adults This command does not work for more than 1 independent variable\n:::\n\n###### 10.Now try to fit a logistic regression model with 'mf' as outcome variable and 'forest', 'adult' and 'female' as predictors. What happens now to the odds ratio of 'forest' in comparison to the model with only 'forest' and 'adult' as predictors?\n\n::: callout-note\nWe already did this in step 8. They are asking for compare GLM7 with GLM6:\n\nThe OR for forest in model GLM6 (with mf and forest and adult) is 3.2653865\n\n      Interpretation: The odds of having a microfilarial infection are 3.27 times as high for those \n      who reside in the forest compared to those in the savanna, if age(being adult) \n      are held constant.\n\nThe OR for forest in model GLM7 (with mf and forest and female and adult) is 3.2577809\n\n      Interpretation: The odds of having a microfilarial infection are 3.26 times as high for those \n      who reside in the forest compared to those in the savanna, if sex and age are held constant.\n\nThere is a minimal change from 3.2577809 to 3.2653865. This is no surprise because we already knew that adding \"female\", that is not a counfounder, so it was not going to cause change in the OR of forest.\n\nYet, the question still remains: for the final model will it be better to have sex or not? for this we have to compare both models with the likelihood ratio test. we will do it later\n:::\n\n###### 11. Please check that the null deviance (the -2LLR of the null model) is 1714.1 on 1301 degrees of freedom. For the model with 'forest' and 'adult' it is 1416.7 on 1299 degrees of freedom. For the model with 'forest', 'adult' and 'female' it is 1394.1 on 1298 degrees of freedom. So the differ-ence between the last two models is 1416.7-1394.1, which is equal to 22.6, on 1299-1298, i.e. 1 degree of freedom. Is this a significant difference, please check a chi square table or in Excel (formula CHIDIST(22.6,1)?\n\n1.  Model 'forest' and 'adult' is GLM6 (Check step 8.3)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary (GLM6)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = mf ~ forest + adult, family = binomial, data = onch1302)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-1.9765  -1.0805   0.5531   0.9290   1.8072  \n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept)  -1.4155     0.1432  -9.884   <2e-16 ***\nforest        1.1834     0.1359   8.709   <2e-16 ***\nadult         2.0325     0.1402  14.499   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1714.1  on 1301  degrees of freedom\nResidual deviance: 1416.7  on 1299  degrees of freedom\nAIC: 1422.7\n\nNumber of Fisher Scoring iterations: 4\n```\n:::\n:::\n\n\n::: callout-note\nFor Model 'forest' and 'adult' (GLM6)\n\n      null deviance: 1714.1\n      Residual deviance: 1416.7   df: 1299\n:::\n\n2.  Model 'forest', 'adult' and 'female' is GLM7 (Check step 8.4)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsummary (GLM7)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = mf ~ forest + female + adult, family = binomial, \n    data = onch1302)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-2.1302  -0.9543   0.4673   0.7988   1.9465  \n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept)  -1.1045     0.1564  -7.060 1.66e-12 ***\nforest        1.1810     0.1370   8.619  < 2e-16 ***\nfemale       -0.6268     0.1335  -4.696 2.65e-06 ***\nadult         2.0831     0.1427  14.594  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1714.1  on 1301  degrees of freedom\nResidual deviance: 1394.1  on 1298  degrees of freedom\nAIC: 1402.1\n\nNumber of Fisher Scoring iterations: 4\n```\n:::\n:::\n\n\n::: callout-note\nFor Model 'forest', 'adult' and 'female' (GLM7)\n\n      null deviance: 1714.1\n      Residual deviance: 1394.1     df: 1298\n:::\n\n::: callout-note\nNote that the null deviance is the same for all the models (because the null deviance refers to a model without any factor)\n\nSo the differ-ence between the two models is\n\n    Residual deviance 1416.7-1394.1 = 22.6, \n    Degrees of freedom 1299-1298 = 1 \n\nIs this a significant difference, please check a chi square table or in Excel (formula CHIDIST(22.6,1)?\n\n    With the Chi square in excel we will obtain p=0.00002\n    So the difference between both models is highly significant.\n:::\n\n###### 12. So apparently the model with the three terms, 'forest', 'adult' and 'female' is significantly better than the model with only 'forest' and 'adult'. The easier way to check this is to do a likelihood ra-tio test in R. First run the complex model with three terms, then run the simple model with two terms and next use the anova() function to make the comparison.\n\n12.1 Fist the model with 'forest', 'adult' and 'female' (GLM7)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#We will run again the Model ‘forest’, ‘adult’ and ‘female’ (GLM7)\nGLM7 <- glm(mf ~ forest + female + adult, family=binomial, data=onch1302)\nsummary (GLM7)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = mf ~ forest + female + adult, family = binomial, \n    data = onch1302)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-2.1302  -0.9543   0.4673   0.7988   1.9465  \n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept)  -1.1045     0.1564  -7.060 1.66e-12 ***\nforest        1.1810     0.1370   8.619  < 2e-16 ***\nfemale       -0.6268     0.1335  -4.696 2.65e-06 ***\nadult         2.0831     0.1427  14.594  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1714.1  on 1301  degrees of freedom\nResidual deviance: 1394.1  on 1298  degrees of freedom\nAIC: 1402.1\n\nNumber of Fisher Scoring iterations: 4\n```\n:::\n:::\n\n\n12.2 Then the model with 'forest' and 'adult' (GLM6)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Model ‘forest’ and ‘adult’\nGLM6 <- glm(mf ~ forest + adult, family=binomial, data=onch1302)\nsummary (GLM7)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = mf ~ forest + female + adult, family = binomial, \n    data = onch1302)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-2.1302  -0.9543   0.4673   0.7988   1.9465  \n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept)  -1.1045     0.1564  -7.060 1.66e-12 ***\nforest        1.1810     0.1370   8.619  < 2e-16 ***\nfemale       -0.6268     0.1335  -4.696 2.65e-06 ***\nadult         2.0831     0.1427  14.594  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1714.1  on 1301  degrees of freedom\nResidual deviance: 1394.1  on 1298  degrees of freedom\nAIC: 1402.1\n\nNumber of Fisher Scoring iterations: 4\n```\n:::\n:::\n\n\n12.3 Likelyhood ratio test: To check if adding female change the model significantly\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(GLM6, GLM7, test=\"Chisq\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAnalysis of Deviance Table\n\nModel 1: mf ~ forest + adult\nModel 2: mf ~ forest + female + adult\n  Resid. Df Resid. Dev Df Deviance  Pr(>Chi)    \n1      1299     1416.7                          \n2      1298     1394.1  1   22.562 2.035e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\n::: callout-note\nSo, according to the likelihood ratio test (anova) the p value is 2.035e-06 (less of 0.05) So adding sex(female) does generate a change in the model. Because of that we keep the more complex model.\n\nThe final model would be:\n\nGLM7 \\<- glm(mf \\~ forest + female + adult, family=binomial, data=onch1302)\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}