{
  "hash": "fc49f52764d344ea58bc4249db3b0b2e",
  "result": {
    "markdown": "---\ntitle: \"2023-02-14 Session 2\"\nformat: \n  html:\n    self-contained: true\n    code-line-numbers: true\ncustom_title_page: false\nfilters:\n  - lightbox\nlightbox: auto\n---\n\n---\nsubtitle: \"Survival Analysis - Session 2\"\ndate: 2023-02-14\n\nauthor:\n  - name: Javier Silva-Valencia\n    orcid: 0000-0002-5982-2821\n    email: javier.silva@unmsm.edu.pe\n    affiliations:\n      - name: Instituut Voor Tropische Geneeskunde. Antwerp-Belgium\n\nlanguage: \n  title-block-author-single: \"Writer\"\n  \nabstract: The objective of the exercise is to practice Cox-regression. It starts doing a survival curve (K-M) for all the sample, then by group of treatment. Finally we need to create the Cox-regression model using the classical approach to select the variables that will be part of the model.\n---\n\n\n---\n\n---\n\n\n### Starting the Exercise\n\nIndications: \n\nThe data in ExerciseII.xls are results of an (hypothetical) observational cancer trial. The aim of the study was to compare two treatment strategies for a brain tumour: one of consists of local radiation (control regimen), one of a combination of local radiation and aggressive chemotherapy (test regimen). The endpoint of the study was survival duration after therapy.\n\nUse R to explore the data. Describe the patient demographics and survival using Kaplan-Meier curves. Do you think that the test regimen prolongs survival? Analyze the data further using Cox-regression. Describe your conclusions.\n\n::: {.callout-tip collapse=\"true\"}\n## Important initial information \n\nAnalysis variable: Time to death \n\nInitial time: When the treatment begins \n\nEnd time: time of dead \n\nIndependent variable: Type of treatment (local radiation vs local+chemotherapy)\n:::\n\n#### Step 1\nFirst we import the data from an excel file\n\n\n::: {.cell hash='2023-02-14-Survival-Analysis-Session-2_cache/html/unnamed-chunk-1_5b5dcee30118d56dd93da2ffde531b89'}\n\n```{.r .cell-code .numberLines}\nlibrary(readxl)\nExerciseII <- read_excel(\"C:/Users/pined/OneDrive - Universidad Nacional Mayor de San Marcos/Javier 2022/Belgica/AC2/Survival Analysis Exercise Database/Exercises/ExerciseII.xls\")\n```\n:::\n\n\nTo start working with survival analysis we need an event variable (1 when the event happened, otherwise 0) \n\nIn this case we already have the \"died\" variable\n\n#### Step 2\nDoing the Kaplan-Meyer curve (survival curve) for all the sample\n\n\n::: {.cell hash='2023-02-14-Survival-Analysis-Session-2_cache/html/unnamed-chunk-2_c892ef4aa5520c0ef364d5608576f957'}\n\n````{.cell-code .numberLines}\n```{{r}}\n#Code for K-M curve\nlibrary(survival)\nmod0 <- survfit(Surv(time, died) ~ 1, data=ExerciseII)\n```\n````\n:::\n\n::: {.cell hash='2023-02-14-Survival-Analysis-Session-2_cache/html/unnamed-chunk-3_9c079cf16b7720e92fef1daf3f045466'}\n\n```{.r .cell-code .numberLines}\n#Code for Kaplan-Meyer Graph\nplot(mod0, mark.time=TRUE)\n```\n\n::: {.cell-output-display}\n![](2023-02-14-Survival-Analysis-Session-2_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n#### Step 3\nKaplan-Meyer curve (survival curve) by group of treatment\n\n\n::: {.cell hash='2023-02-14-Survival-Analysis-Session-2_cache/html/unnamed-chunk-4_46ed2edd560171e912129ccd4150ace2'}\n\n````{.cell-code .numberLines}\n```{{r}}\n#Code for K-M curve\nmod1 <- survfit(Surv(time, died) ~ trt, data=ExerciseII)\n\n#Code for Kaplan-Meyer Graph\nplot(mod1, mark.time=TRUE, lty=1:2)\nlegend (\"top\", legend=unique(ExerciseII$trt), lty=1:2)\n```\n````\n\n::: {.cell-output-display}\n![](2023-02-14-Survival-Analysis-Session-2_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n:::\n\nWe can also see the numbers of the graphic\n\n\n::: {.cell hash='2023-02-14-Survival-Analysis-Session-2_cache/html/unnamed-chunk-5_1b713528878760095a5c1f18aeb70b79'}\n\n```{.r .cell-code .numberLines}\nmod1\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCall: survfit(formula = Surv(time, died) ~ trt, data = ExerciseII)\n\n        n events median 0.95LCL 0.95UCL\ntrt=0 300    225    512     450     600\ntrt=1 200    151    434     332     605\n```\n:::\n:::\n\n\n::: callout-tip\n## Interpretation\nIn Treatment 0 (local radiation): 50% of the population was alive at day 512 \n\nIn Treatment 1 (local + chemoteraphy): 50% of the population was alive at day 434\n\nSo, at first glance, it seems that in treatment 1, people tend to die faster. Is this true?? *We cannot say yet, we need to do the multivariate analysis with other variables that may be intervening*\n:::\n\n#### Step 4\nCreating Cox Regression model (using the classical model)\n\n4.1 Creating Cox regression with each of the (possible) predictors separately (bivariate analysis):\n\n::: callout-tip\nThe Possible predictors could be: gender, trt and type\n\nAll those could be predictors or counfounders because this is not a clinical trial. (In a clinical trial the amount of persons in each group is fixed)\n::: \n\n\n::: {.cell hash='2023-02-14-Survival-Analysis-Session-2_cache/html/unnamed-chunk-6_6e37faf49a7775481decf0dbbce8098f'}\n\n````{.cell-code .numberLines}\n```{{r}}\n#Creating the Cox models for each variable (bivariate)\nlibrary(survival)\nCox1<- coxph(Surv(time, died) ~ trt, data=ExerciseII)\nCox2<- coxph(Surv(time, died) ~ gender, data=ExerciseII)\nCox3<- coxph(Surv(time, died) ~ type, data=ExerciseII)\n\nsummary(Cox1)\nsummary(Cox2)\nsummary(Cox3)\n```\n````\n\n::: {.cell-output .cell-output-stdout}\n```\nCall:\ncoxph(formula = Surv(time, died) ~ trt, data = ExerciseII)\n\n  n= 500, number of events= 376 \n\n      coef exp(coef) se(coef)     z Pr(>|z|)  \ntrt 0.2342    1.2638   0.1055 2.221   0.0264 *\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n    exp(coef) exp(-coef) lower .95 upper .95\ntrt     1.264     0.7912     1.028     1.554\n\nConcordance= 0.514  (se = 0.013 )\nLikelihood ratio test= 4.85  on 1 df,   p=0.03\nWald test            = 4.93  on 1 df,   p=0.03\nScore (logrank) test = 4.95  on 1 df,   p=0.03\n\nCall:\ncoxph(formula = Surv(time, died) ~ gender, data = ExerciseII)\n\n  n= 500, number of events= 376 \n\n           coef exp(coef) se(coef)     z Pr(>|z|)\ngenderM 0.03332   1.03388  0.10319 0.323    0.747\n\n        exp(coef) exp(-coef) lower .95 upper .95\ngenderM     1.034     0.9672    0.8446     1.266\n\nConcordance= 0.502  (se = 0.014 )\nLikelihood ratio test= 0.1  on 1 df,   p=0.7\nWald test            = 0.1  on 1 df,   p=0.7\nScore (logrank) test = 0.1  on 1 df,   p=0.7\n\nCall:\ncoxph(formula = Surv(time, died) ~ type, data = ExerciseII)\n\n  n= 500, number of events= 376 \n\n       coef exp(coef) se(coef)     z Pr(>|z|)    \ntype 1.2583    3.5193   0.1112 11.32   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n     exp(coef) exp(-coef) lower .95 upper .95\ntype     3.519     0.2841      2.83     4.376\n\nConcordance= 0.644  (se = 0.012 )\nLikelihood ratio test= 131.9  on 1 df,   p=<2e-16\nWald test            = 128.1  on 1 df,   p=<2e-16\nScore (logrank) test = 141.8  on 1 df,   p=<2e-16\n```\n:::\n:::\n\n\n::: callout-tip\n## Results from above\n\n| Factor |  HR   |    95% IC    | p-value |\n|:------:|:-----:|:------------:|:-------:|\n|  trt   | 1.264 | 1.028 1.554  | 0.0264  |\n| gender | 1.034 | 0.8446 1.266 |  0.747  |\n|  type  | 3.519 |  2.83 4.376  | < 2e-16 |\n\nNow we have to select those with p < 0.200 (or 0.100 depending on our analysis plan) for further modeling\n\nThis means that all variables with  p < 0.200 (type) are potential factors that could be in our final model.\n\nWe also keep \"trt\" because it is the main independent variable\n\n:::\n\n4.2 Entering the selected variables in a multivariable model and then removing the non-significant factors one by one (always removing the least significant factor). \"Backwards elimination\"\n\n\n::: {.cell hash='2023-02-14-Survival-Analysis-Session-2_cache/html/unnamed-chunk-7_59abab9cb7c42d93f9c4bf0e0c0b198a'}\n\n````{.cell-code .numberLines}\n```{{r}}\n#Creating the Cox model for all selected variables (multivariate)\nlibrary(survival)\nCox4<- coxph(Surv(time, died) ~ trt + type , data=ExerciseII)\nsummary(Cox4)\n```\n````\n\n::: {.cell-output .cell-output-stdout}\n```\nCall:\ncoxph(formula = Surv(time, died) ~ trt + type, data = ExerciseII)\n\n  n= 500, number of events= 376 \n\n        coef exp(coef) se(coef)      z Pr(>|z|)    \ntrt  -0.5853    0.5569   0.1233 -4.747 2.06e-06 ***\ntype  1.5945    4.9257   0.1316 12.115  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n     exp(coef) exp(-coef) lower .95 upper .95\ntrt     0.5569      1.796    0.4374    0.7092\ntype    4.9257      0.203    3.8058    6.3751\n\nConcordance= 0.67  (se = 0.013 )\nLikelihood ratio test= 154.6  on 2 df,   p=<2e-16\nWald test            = 149.9  on 2 df,   p=<2e-16\nScore (logrank) test = 163.7  on 2 df,   p=<2e-16\n```\n:::\n:::\n\n\n::: callout-tip\n## Reply\nBoth independant variable (trt and type) are significant (p value = 2.06e-06 and < 2e-16 )\n\nSo we need to keep both independent variables. But, are they ok like that, or there is an interaction?\n:::\n\n\n4.3 Checking for interaction\n\n\n::: {.cell hash='2023-02-14-Survival-Analysis-Session-2_cache/html/unnamed-chunk-8_89ed1af3c7671db44800142840126458'}\n\n````{.cell-code .numberLines}\n```{{r}}\n#Creating the Cox model for all selected variables considering interaction\nCox5<- coxph(Surv(time, died) ~ trt * type , data=ExerciseII)\nsummary(Cox5)\n```\n````\n\n::: {.cell-output .cell-output-stdout}\n```\nCall:\ncoxph(formula = Surv(time, died) ~ trt * type, data = ExerciseII)\n\n  n= 500, number of events= 376 \n\n            coef exp(coef) se(coef)      z Pr(>|z|)    \ntrt      -0.1068    0.8987   0.2191 -0.487   0.6260    \ntype      1.7610    5.8185   0.1466 12.014   <2e-16 ***\ntrt:type -0.6405    0.5270   0.2584 -2.479   0.0132 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n         exp(coef) exp(-coef) lower .95 upper .95\ntrt         0.8987     1.1127    0.5850    1.3808\ntype        5.8185     0.1719    4.3656    7.7550\ntrt:type    0.5270     1.8974    0.3176    0.8745\n\nConcordance= 0.67  (se = 0.013 )\nLikelihood ratio test= 160.2  on 3 df,   p=<2e-16\nWald test            = 163.4  on 3 df,   p=<2e-16\nScore (logrank) test = 189.7  on 3 df,   p=<2e-16\n```\n:::\n:::\n\n\n::: {.callout-tip collapse=\"true\"}\n## Things to keep in mind\nIt seems that with the treatment effect interaction it is no longer significant (HR: 0.8987, pvalue= 0.6260), but it is not true.\n\nBecause we're introducing the interaction, when we see the HR = 0.8987 it's the HR for the local cancer only.\n::: \n\n\n::: callout-tip\n## Reply\n\nThe data from the model is:\n\n| Factor |  HR   |\n|:------:|:-----:|\n|  trt   | 0.8987 |\n| type   | 5.8185 |\n|  trt:type  | 0.5270 |\n\nBut to know the correct HR of trt we have to add the HR of the interaction:   \n\n.            HR of trt = 0.899^trt * 0.5270^(trt*type)\n\nHR trt in local cancer = 0.899^trt * 0.5270^(trt*0) \nHR trt in local cancer = 0.899^trt * 1 \nHR trt in local cancer = 0.899\n\nHR trt for metastatic cancer = 0.899^trt * 0.5270^(trt*type)\nHR trt for metastatic cancer = 0.899^trt * 0.5270^(trt*1)\nHR trt for metastatic cancer = 0.899     * 0.527\nHR trt for metastatic cancer = 0.473\n\n\n:::\n\n4.4 We need to compare both models to check if the model with interaction is significantly better\n\n\n::: {.cell hash='2023-02-14-Survival-Analysis-Session-2_cache/html/unnamed-chunk-9_4fcb52192f7672138ce4e5dca0b41871'}\n\n```{.r .cell-code .numberLines}\nanova(Cox5, Cox4, test=\"Chisq\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAnalysis of Deviance Table\n Cox model: response is  Surv(time, died)\n Model 1: ~ trt * type\n Model 2: ~ trt + type\n   loglik  Chisq Df P(>|Chi|)  \n1 -1995.9                      \n2 -1998.8 5.6712  1   0.01725 *\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\n::: callout-tip\n## Reply\nThere is a significant difference with and without interaction models (p = 0.01725). So we keep the interaction.\n:::\n\n4.5 To present better the data with interaction is better to divide the dataset according each group of interaction and to present the model separately.\n\nCreating subsets according each group of interaction:\n\n\n::: {.cell hash='2023-02-14-Survival-Analysis-Session-2_cache/html/unnamed-chunk-10_cc711f41cd1093d0d78940f36f0210d2'}\n\n````{.cell-code .numberLines}\n```{{r}}\ntable(ExerciseII$type)\nLocalCancer  <-  subset(ExerciseII, type==0)  #Creating a database for local cancer\nMetastatic  <-  subset(ExerciseII, type==1)    #Creating a database for metastatic\n```\n````\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  0   1 \n240 260 \n```\n:::\n:::\n\n\nChecking the kaplan-meyer curve and cox regressión in each subset\n\n4.5.1 IN LOCAL CANCER\n\n\n::: {.cell hash='2023-02-14-Survival-Analysis-Session-2_cache/html/unnamed-chunk-11_ad2373923bb2c5dbe21fd0e7f9e2693b'}\n\n````{.cell-code .numberLines}\n```{{r}}\n#Kaplan-Meyer curve\nmodLC <- survfit(Surv(time, died) ~ trt, data=LocalCancer)\nplot(modLC, mark.time=TRUE, lty=1:2)\nlegend (\"top\", legend=unique(LocalCancer$trt), lty=1:2)\n```\n````\n\n::: {.cell-output-display}\n![](2023-02-14-Survival-Analysis-Session-2_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n:::\n\n::: {.cell hash='2023-02-14-Survival-Analysis-Session-2_cache/html/unnamed-chunk-12_7ff6af132f086b48af0f3eb2996076fc'}\n\n````{.cell-code .numberLines}\n```{{r}}\n#Cox Regression\nCoxLC<- coxph(Surv(time, died) ~ trt, data=LocalCancer)\nsummary(CoxLC)\n```\n````\n\n::: {.cell-output .cell-output-stdout}\n```\nCall:\ncoxph(formula = Surv(time, died) ~ trt, data = LocalCancer)\n\n  n= 240, number of events= 151 \n\n       coef exp(coef) se(coef)      z Pr(>|z|)\ntrt -0.1020    0.9030   0.2191 -0.465    0.642\n\n    exp(coef) exp(-coef) lower .95 upper .95\ntrt     0.903      1.107    0.5877     1.387\n\nConcordance= 0.511  (se = 0.016 )\nLikelihood ratio test= 0.22  on 1 df,   p=0.6\nWald test            = 0.22  on 1 df,   p=0.6\nScore (logrank) test = 0.22  on 1 df,   p=0.6\n```\n:::\n:::\n\n::: callout-tip\n## Interpretation:\n\nHR local cancer = 0.90    IC95%(0.5877     1.387)\n\nAmong those with local cancer, the ones that undergo the new treatment has 10% less hazard of die than the ones that went with the traditional treatment.But this is not significant.\n\nThat is the same to say:\n\nAmong those with local cancer, getting the new treatment reduces your hazard of dying by 10%. But this is not significant.\n\n::: \n\n\n4.4.2 IN METASTATIC CANCER\n\n\n::: {.cell hash='2023-02-14-Survival-Analysis-Session-2_cache/html/unnamed-chunk-13_fa597aa15d3bbf80085c857130464c35'}\n\n````{.cell-code .numberLines}\n```{{r}}\n#Kaplan-Meyer curve\nmodMC <- survfit(Surv(time, died) ~ trt, data=Metastatic)\nplot(modMC, mark.time=TRUE, lty=1:2)\nlegend (\"top\", legend=unique(Metastatic$trt), lty=1:2)\n```\n````\n\n::: {.cell-output-display}\n![](2023-02-14-Survival-Analysis-Session-2_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\n::: {.cell hash='2023-02-14-Survival-Analysis-Session-2_cache/html/unnamed-chunk-14_200abbb3d38d3938a9f7a4b3b30effc0'}\n\n````{.cell-code .numberLines}\n```{{r}}\n#Cox regressión\nCoxMC<- coxph(Surv(time, died) ~ trt, data=Metastatic)\nsummary(CoxMC)\n```\n````\n\n::: {.cell-output .cell-output-stdout}\n```\nCall:\ncoxph(formula = Surv(time, died) ~ trt, data = Metastatic)\n\n  n= 260, number of events= 225 \n\n       coef exp(coef) se(coef)      z Pr(>|z|)    \ntrt -0.7685    0.4637   0.1430 -5.375 7.67e-08 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n    exp(coef) exp(-coef) lower .95 upper .95\ntrt    0.4637      2.156    0.3504    0.6137\n\nConcordance= 0.592  (se = 0.018 )\nLikelihood ratio test= 28.13  on 1 df,   p=1e-07\nWald test            = 28.89  on 1 df,   p=8e-08\nScore (logrank) test = 30.19  on 1 df,   p=4e-08\n```\n:::\n:::\n\n::: callout-tip\n## Interpretation:\n\nHR metastatic cancer = 0.46  IC95% (0.3504    0.6137)\n\nAmong those with metastasis cancer, the ones that undergo the new treatment has 54% less hazard of die than the ones that went with the traditional treatment.\n\nThat is the same to say:\n\nAmong those with metastasis cancer, getting the new treatment reduces your hazard of dying by 54%\n\nHR local cancer = 0.90 \n::: ",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}