{
  "hash": "856f9bfc0caeeb511f4851f90756ce76",
  "result": {
    "markdown": "---\ntitle: \"Data Analysis Wk1\"\nformat: \n  html:\n    self-contained: true\n    code-line-numbers: true\n  pdf: \n    documentclass: article\ncustom_title_page: false\nfilters:\n  - lightbox\nlightbox: auto\n---\n\n---\nsubtitle: \"Data Analysis Week - Session 1\"\ndate: 2023-02-27\n\nauthor:\n  - name: Javier Silva-Valencia\n    orcid: 0000-0002-5982-2821\n    email: javier.silva@unmsm.edu.pe\n    affiliations:\n      - name: Instituut Voor Tropische Geneeskunde. Antwerp-Belgium\n\nlanguage: \n  title-block-author-single: \"Writer\"\n  \nabstract: Today we had an introduction to TMRC dataset.\n---\n\n\n\n------------------------------------------------------------------------\n\n------------------------------------------------------------------------\n\n\n### Exercise 1\n\n#### Import CSV\n\nSet working directory: We are not going to do it\n\nImporting the CSV database under the name of Q1_B, with \",\" as separator, and with \".\" as decimal:\n\n\n\n::: {.cell hash='Data-Analysis-Wk1_cache/pdf/unnamed-chunk-1_fd2be0e818d6641af4d4ce19d5252864'}\n\n```{.r .cell-code .numberLines}\nQ1_B <- read.csv(\"C:/Users/pined/OneDrive - Universidad Nacional Mayor de San Marcos/Javier 2022/Belgica/AC2_DataAnalysis_ThWk/Material/Q1_B.csv\", sep=\",\", dec= \".\")\n```\n:::\n\n\n\n#### Subset by row\n\nSeeing FSN\n\n\n::: {.cell hash='Data-Analysis-Wk1_cache/pdf/unnamed-chunk-2_6f4a8c30cf11a12bf257d84a917b1d3a'}\n\n```{.r .cell-code .numberLines}\nsummary(Q1_B$FSN)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n  45001   48527   52032   52110   55671   59606 \n```\n:::\n:::\n\n\n::: callout-tip\nThe median is 52032\n::: \n\nCreating subset\n\n\n::: {.cell hash='Data-Analysis-Wk1_cache/pdf/unnamed-chunk-3_60c682c3f96703d4e9276ed90354fc41'}\n\n```{.r .cell-code .numberLines}\ntop <- subset(Q1_B, subset= FSN < 52032)\nbottom <- subset(Q1_B, subset= FSN >= 52032)\n```\n:::\n\n\n\nSeeing the structure in all sets\n\n\n::: {.cell hash='Data-Analysis-Wk1_cache/pdf/unnamed-chunk-4_8b7bffb130f98a54386fcd1400729ab2'}\n\n```{.r .cell-code .numberLines}\nstr(Q1_B)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t13377 obs. of  40 variables:\n $ ID                 : int  1 2 3 4 5 6 7 8 9 10 ...\n $ FSN                : num  45001 45002 45003 45004 45005 ...\n $ Neem_Tree          : num  0 0 0 0 0 0 0 0 0 0 ...\n $ Neem_Tree_Distance : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Size     : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Age      : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Usage    : chr  \"\" \"\" \"\" \"\" ...\n $ Neem_Tree_Use_Other: chr  \"\" \"\" \"\" \"\" ...\n $ Bamboo_Tree        : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Bamboo_Tree_Dist   : num  3 10 16 17 5 4 15 3 1 10 ...\n $ Banana_Tree        : num  0 0 0 0 0 0 0 1 1 0 ...\n $ Banana_Tree_Dist   : num  -1 -1 -1 -1 -1 -1 -1 5 1 -1 ...\n $ Rice_Field         : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Rice_Field_Dist    : num  4 12 16 13 4 13 10 10 7 12 ...\n $ Perm_Water_Body    : num  0 0 0 0 0 0 0 0 0 0 ...\n $ Perm_Wat_Body_Dist : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Wat_Body_Mid_Point : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ No_Mosquito_Net    : num  0 2 1 0 0 0 0 0 1 0 ...\n $ Sprayed_2010       : num  86 86 86 86 86 86 86 86 86 86 ...\n $ Sprayed_2009       : num  86 86 86 86 86 86 86 86 86 86 ...\n $ Floor_Material     : num  153 153 153 153 153 153 153 153 155 153 ...\n $ Other_Floor_Mat    : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Is_Floor_Damp      : num  1 1 1 1 1 1 1 1 0 1 ...\n $ Roof_Material      : num  161 159 158 156 156 156 156 158 158 156 ...\n $ Other_Roof_Material: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Wall_Material      : num  164 164 164 162 163 163 162 164 164 162 ...\n $ Other_Wall_Material: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Windows_in_Room    : num  1 1 1 0 0 0 0 1 1 0 ...\n $ Granaries_in_HH    : num  1 1 1 0 1 1 0 1 1 0 ...\n $ Source_Drink_Water : num  167 167 92 92 92 92 92 92 92 92 ...\n $ Other_Src_Drink_Wat: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Toilet_Facility    : num  177 177 177 177 177 177 177 177 177 177 ...\n $ Other_Toilet_Fac   : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Cooking_Fuel       : num  180 180 180 180 180 180 180 180 180 180 ...\n $ Other_Cooking_Fuel : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Source_Light       : num  182 182 182 182 182 182 182 182 182 182 ...\n $ Other_Source_Light : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Electricity_in_HH  : num  0 0 0 0 0 0 0 0 0 0 ...\n $ No_Of_Rooms        : num  2 2 3 1 2 3 2 1 3 1 ...\n $ No_Sleeping_Rooms  : num  2 2 2 1 2 2 2 1 1 1 ...\n```\n:::\n\n```{.r .cell-code .numberLines}\nstr(top)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t6688 obs. of  40 variables:\n $ ID                 : int  1 2 3 4 5 6 7 8 9 10 ...\n $ FSN                : num  45001 45002 45003 45004 45005 ...\n $ Neem_Tree          : num  0 0 0 0 0 0 0 0 0 0 ...\n $ Neem_Tree_Distance : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Size     : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Age      : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Usage    : chr  \"\" \"\" \"\" \"\" ...\n $ Neem_Tree_Use_Other: chr  \"\" \"\" \"\" \"\" ...\n $ Bamboo_Tree        : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Bamboo_Tree_Dist   : num  3 10 16 17 5 4 15 3 1 10 ...\n $ Banana_Tree        : num  0 0 0 0 0 0 0 1 1 0 ...\n $ Banana_Tree_Dist   : num  -1 -1 -1 -1 -1 -1 -1 5 1 -1 ...\n $ Rice_Field         : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Rice_Field_Dist    : num  4 12 16 13 4 13 10 10 7 12 ...\n $ Perm_Water_Body    : num  0 0 0 0 0 0 0 0 0 0 ...\n $ Perm_Wat_Body_Dist : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Wat_Body_Mid_Point : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ No_Mosquito_Net    : num  0 2 1 0 0 0 0 0 1 0 ...\n $ Sprayed_2010       : num  86 86 86 86 86 86 86 86 86 86 ...\n $ Sprayed_2009       : num  86 86 86 86 86 86 86 86 86 86 ...\n $ Floor_Material     : num  153 153 153 153 153 153 153 153 155 153 ...\n $ Other_Floor_Mat    : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Is_Floor_Damp      : num  1 1 1 1 1 1 1 1 0 1 ...\n $ Roof_Material      : num  161 159 158 156 156 156 156 158 158 156 ...\n $ Other_Roof_Material: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Wall_Material      : num  164 164 164 162 163 163 162 164 164 162 ...\n $ Other_Wall_Material: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Windows_in_Room    : num  1 1 1 0 0 0 0 1 1 0 ...\n $ Granaries_in_HH    : num  1 1 1 0 1 1 0 1 1 0 ...\n $ Source_Drink_Water : num  167 167 92 92 92 92 92 92 92 92 ...\n $ Other_Src_Drink_Wat: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Toilet_Facility    : num  177 177 177 177 177 177 177 177 177 177 ...\n $ Other_Toilet_Fac   : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Cooking_Fuel       : num  180 180 180 180 180 180 180 180 180 180 ...\n $ Other_Cooking_Fuel : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Source_Light       : num  182 182 182 182 182 182 182 182 182 182 ...\n $ Other_Source_Light : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Electricity_in_HH  : num  0 0 0 0 0 0 0 0 0 0 ...\n $ No_Of_Rooms        : num  2 2 3 1 2 3 2 1 3 1 ...\n $ No_Sleeping_Rooms  : num  2 2 2 1 2 2 2 1 1 1 ...\n```\n:::\n\n```{.r .cell-code .numberLines}\nstr(bottom)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t6689 obs. of  40 variables:\n $ ID                 : int  6689 6690 6691 6692 6693 6694 6695 6696 6697 6698 ...\n $ FSN                : num  52032 52033 52034 52035 52036 ...\n $ Neem_Tree          : num  1 1 1 1 1 1 1 1 1 0 ...\n $ Neem_Tree_Distance : num  12 30 38 38 12 16 20 25 45 -1 ...\n $ Neem_Tree_Size     : num  2 2 2 2 2 2 2 2 2 -1 ...\n $ Neem_Tree_Age      : num  2 2 2 2 2 2 2 2 2 -1 ...\n $ Neem_Tree_Usage    : chr  \"188_\" \"188_\" \"188_\" \"188_\" ...\n $ Neem_Tree_Use_Other: chr  \"\" \"\" \"\" \"\" ...\n $ Bamboo_Tree        : num  0 0 0 0 1 1 0 0 0 1 ...\n $ Bamboo_Tree_Dist   : num  -1 -1 -1 -1 5 15 -1 -1 -1 18 ...\n $ Banana_Tree        : num  1 1 0 0 1 1 1 1 1 1 ...\n $ Banana_Tree_Dist   : num  1 20 -1 -1 1 16 5 2 1 1 ...\n $ Rice_Field         : num  0 1 1 1 1 1 1 1 1 1 ...\n $ Rice_Field_Dist    : num  -1 1 1 1 10 15 18 12 1 2 ...\n $ Perm_Water_Body    : num  0 0 0 0 1 1 1 1 1 1 ...\n $ Perm_Wat_Body_Dist : num  -1 -1 -1 -1 2 1 8 12 26 17 ...\n $ Wat_Body_Mid_Point : num  -1 -1 -1 -1 1 1 1 1 1 1 ...\n $ No_Mosquito_Net    : num  1 1 1 0 1 4 4 5 1 0 ...\n $ Sprayed_2010       : num  86 86 86 86 86 86 86 86 86 86 ...\n $ Sprayed_2009       : num  86 86 86 86 86 86 86 86 86 86 ...\n $ Floor_Material     : num  153 153 153 153 153 153 155 155 153 153 ...\n $ Other_Floor_Mat    : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Is_Floor_Damp      : num  1 1 1 1 1 1 0 0 1 0 ...\n $ Roof_Material      : num  161 156 156 156 54 158 158 158 161 158 ...\n $ Other_Roof_Material: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Wall_Material      : num  164 162 162 162 164 165 165 165 164 165 ...\n $ Other_Wall_Material: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Windows_in_Room    : num  0 0 0 0 1 1 1 1 1 1 ...\n $ Granaries_in_HH    : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Source_Drink_Water : num  92 167 167 92 167 167 167 167 167 167 ...\n $ Other_Src_Drink_Wat: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Toilet_Facility    : num  177 177 177 177 177 174 174 174 177 174 ...\n $ Other_Toilet_Fac   : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Cooking_Fuel       : num  180 180 180 180 180 180 180 180 180 180 ...\n $ Other_Cooking_Fuel : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Source_Light       : num  182 182 182 182 182 182 182 182 182 182 ...\n $ Other_Source_Light : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Electricity_in_HH  : num  0 0 0 0 0 1 1 1 0 0 ...\n $ No_Of_Rooms        : num  2 2 1 1 3 4 5 4 3 1 ...\n $ No_Sleeping_Rooms  : num  1 2 1 1 2 3 4 3 1 1 ...\n```\n:::\n:::\n\n\n::: callout-tip\nIn Q1_B we have 13377 obs\n\nTop + bottom: 6688 + 6689 =13377\n\nSo, it is ok\n::: \n\n#### Joining (Append)\n\n\n::: {.cell hash='Data-Analysis-Wk1_cache/pdf/unnamed-chunk-5_d6b9c1e7a4964b7818343fd49267e5b9'}\n\n```{.r .cell-code .numberLines}\nmerged_top_bottom  <-  rbind(top,bottom)\nstr(merged_top_bottom)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t13377 obs. of  40 variables:\n $ ID                 : int  1 2 3 4 5 6 7 8 9 10 ...\n $ FSN                : num  45001 45002 45003 45004 45005 ...\n $ Neem_Tree          : num  0 0 0 0 0 0 0 0 0 0 ...\n $ Neem_Tree_Distance : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Size     : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Age      : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Usage    : chr  \"\" \"\" \"\" \"\" ...\n $ Neem_Tree_Use_Other: chr  \"\" \"\" \"\" \"\" ...\n $ Bamboo_Tree        : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Bamboo_Tree_Dist   : num  3 10 16 17 5 4 15 3 1 10 ...\n $ Banana_Tree        : num  0 0 0 0 0 0 0 1 1 0 ...\n $ Banana_Tree_Dist   : num  -1 -1 -1 -1 -1 -1 -1 5 1 -1 ...\n $ Rice_Field         : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Rice_Field_Dist    : num  4 12 16 13 4 13 10 10 7 12 ...\n $ Perm_Water_Body    : num  0 0 0 0 0 0 0 0 0 0 ...\n $ Perm_Wat_Body_Dist : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Wat_Body_Mid_Point : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ No_Mosquito_Net    : num  0 2 1 0 0 0 0 0 1 0 ...\n $ Sprayed_2010       : num  86 86 86 86 86 86 86 86 86 86 ...\n $ Sprayed_2009       : num  86 86 86 86 86 86 86 86 86 86 ...\n $ Floor_Material     : num  153 153 153 153 153 153 153 153 155 153 ...\n $ Other_Floor_Mat    : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Is_Floor_Damp      : num  1 1 1 1 1 1 1 1 0 1 ...\n $ Roof_Material      : num  161 159 158 156 156 156 156 158 158 156 ...\n $ Other_Roof_Material: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Wall_Material      : num  164 164 164 162 163 163 162 164 164 162 ...\n $ Other_Wall_Material: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Windows_in_Room    : num  1 1 1 0 0 0 0 1 1 0 ...\n $ Granaries_in_HH    : num  1 1 1 0 1 1 0 1 1 0 ...\n $ Source_Drink_Water : num  167 167 92 92 92 92 92 92 92 92 ...\n $ Other_Src_Drink_Wat: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Toilet_Facility    : num  177 177 177 177 177 177 177 177 177 177 ...\n $ Other_Toilet_Fac   : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Cooking_Fuel       : num  180 180 180 180 180 180 180 180 180 180 ...\n $ Other_Cooking_Fuel : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Source_Light       : num  182 182 182 182 182 182 182 182 182 182 ...\n $ Other_Source_Light : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Electricity_in_HH  : num  0 0 0 0 0 0 0 0 0 0 ...\n $ No_Of_Rooms        : num  2 2 3 1 2 3 2 1 3 1 ...\n $ No_Sleeping_Rooms  : num  2 2 2 1 2 2 2 1 1 1 ...\n```\n:::\n:::\n\n\n\n::: callout-tip\nThere are 13377 obs\n\nSo, it is ok\n::: \n\n\n#### Subset by colls\n\nSeeing the names of the variable\n\n\n::: {.cell hash='Data-Analysis-Wk1_cache/pdf/unnamed-chunk-6_f2903f00c1ebae4fbe1cf4ece02116b7'}\n\n```{.r .cell-code .numberLines}\nnames(Q1_B)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"ID\"                  \"FSN\"                 \"Neem_Tree\"          \n [4] \"Neem_Tree_Distance\"  \"Neem_Tree_Size\"      \"Neem_Tree_Age\"      \n [7] \"Neem_Tree_Usage\"     \"Neem_Tree_Use_Other\" \"Bamboo_Tree\"        \n[10] \"Bamboo_Tree_Dist\"    \"Banana_Tree\"         \"Banana_Tree_Dist\"   \n[13] \"Rice_Field\"          \"Rice_Field_Dist\"     \"Perm_Water_Body\"    \n[16] \"Perm_Wat_Body_Dist\"  \"Wat_Body_Mid_Point\"  \"No_Mosquito_Net\"    \n[19] \"Sprayed_2010\"        \"Sprayed_2009\"        \"Floor_Material\"     \n[22] \"Other_Floor_Mat\"     \"Is_Floor_Damp\"       \"Roof_Material\"      \n[25] \"Other_Roof_Material\" \"Wall_Material\"       \"Other_Wall_Material\"\n[28] \"Windows_in_Room\"     \"Granaries_in_HH\"     \"Source_Drink_Water\" \n[31] \"Other_Src_Drink_Wat\" \"Toilet_Facility\"     \"Other_Toilet_Fac\"   \n[34] \"Cooking_Fuel\"        \"Other_Cooking_Fuel\"  \"Source_Light\"       \n[37] \"Other_Source_Light\"  \"Electricity_in_HH\"   \"No_Of_Rooms\"        \n[40] \"No_Sleeping_Rooms\"  \n```\n:::\n:::\n\n::: {.cell hash='Data-Analysis-Wk1_cache/pdf/unnamed-chunk-7_7cbf2f44292263b977afc354e1ee9c0a'}\n\n```{.r .cell-code .numberLines}\nLeft <- subset(Q1_B, select=c(\"ID\", \"FSN\", \"Neem_Tree\", \"Neem_Tree_Distance\", \"Neem_Tree_Size\", \"Neem_Tree_Age\", \"Neem_Tree_Usage\", \"Neem_Tree_Use_Other\", \"Bamboo_Tree\", \"Bamboo_Tree_Dist\", \"Banana_Tree\", \"Banana_Tree_Dist\", \"Rice_Field\", \"Rice_Field_Dist\", \"Perm_Water_Body\", \"Perm_Wat_Body_Dist\",  \"Wat_Body_Mid_Point\", \"No_Mosquito_Net\", \"Sprayed_2010\", \"Sprayed_2009\", \"Floor_Material\"))\nstr(Left)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t13377 obs. of  21 variables:\n $ ID                 : int  1 2 3 4 5 6 7 8 9 10 ...\n $ FSN                : num  45001 45002 45003 45004 45005 ...\n $ Neem_Tree          : num  0 0 0 0 0 0 0 0 0 0 ...\n $ Neem_Tree_Distance : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Size     : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Age      : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Usage    : chr  \"\" \"\" \"\" \"\" ...\n $ Neem_Tree_Use_Other: chr  \"\" \"\" \"\" \"\" ...\n $ Bamboo_Tree        : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Bamboo_Tree_Dist   : num  3 10 16 17 5 4 15 3 1 10 ...\n $ Banana_Tree        : num  0 0 0 0 0 0 0 1 1 0 ...\n $ Banana_Tree_Dist   : num  -1 -1 -1 -1 -1 -1 -1 5 1 -1 ...\n $ Rice_Field         : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Rice_Field_Dist    : num  4 12 16 13 4 13 10 10 7 12 ...\n $ Perm_Water_Body    : num  0 0 0 0 0 0 0 0 0 0 ...\n $ Perm_Wat_Body_Dist : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Wat_Body_Mid_Point : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ No_Mosquito_Net    : num  0 2 1 0 0 0 0 0 1 0 ...\n $ Sprayed_2010       : num  86 86 86 86 86 86 86 86 86 86 ...\n $ Sprayed_2009       : num  86 86 86 86 86 86 86 86 86 86 ...\n $ Floor_Material     : num  153 153 153 153 153 153 153 153 155 153 ...\n```\n:::\n:::\n\n::: {.cell hash='Data-Analysis-Wk1_cache/pdf/unnamed-chunk-8_87589d7d4d3f0b3a638231319aa9fd03'}\n\n```{.r .cell-code .numberLines}\nRigth <- subset(Q1_B, select=c(\"FSN\", \"Other_Floor_Mat\", \"Is_Floor_Damp\", \"Roof_Material\", \"Other_Roof_Material\", \"Wall_Material\", \"Other_Wall_Material\", \"Windows_in_Room\", \"Granaries_in_HH\", \"Source_Drink_Water\", \"Other_Src_Drink_Wat\", \"Toilet_Facility\", \"Other_Toilet_Fac\", \"Cooking_Fuel\", \"Other_Cooking_Fuel\", \"Source_Light\", \"Other_Source_Light\", \"Electricity_in_HH\", \"No_Of_Rooms\", \"No_Sleeping_Rooms\"))\n\n#Or select the opposite (With a \"-\" in front of the c):\n#Rigth <- subset(Q1_B, select=-c(\"ID\", \"Neem_Tree\", \"Neem_Tree_Distance\", \"Neem_Tree_Size\", \"Neem_Tree_Age\", \"Neem_Tree_Usage\", \"Neem_Tree_Use_Other\", \"Bamboo_Tree\", \"Bamboo_Tree_Dist\", \"Banana_Tree\", \"Banana_Tree_Dist\", \"Rice_Field\", \"Rice_Field_Dist\", \"Perm_Water_Body\", \"Perm_Wat_Body_Dist\",  \"Wat_Body_Mid_Point\", \"No_Mosquito_Net\", \"Sprayed_2010\", \"Sprayed_2009\", \"Floor_Material\"))\n\nstr(Rigth)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t13377 obs. of  20 variables:\n $ FSN                : num  45001 45002 45003 45004 45005 ...\n $ Other_Floor_Mat    : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Is_Floor_Damp      : num  1 1 1 1 1 1 1 1 0 1 ...\n $ Roof_Material      : num  161 159 158 156 156 156 156 158 158 156 ...\n $ Other_Roof_Material: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Wall_Material      : num  164 164 164 162 163 163 162 164 164 162 ...\n $ Other_Wall_Material: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Windows_in_Room    : num  1 1 1 0 0 0 0 1 1 0 ...\n $ Granaries_in_HH    : num  1 1 1 0 1 1 0 1 1 0 ...\n $ Source_Drink_Water : num  167 167 92 92 92 92 92 92 92 92 ...\n $ Other_Src_Drink_Wat: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Toilet_Facility    : num  177 177 177 177 177 177 177 177 177 177 ...\n $ Other_Toilet_Fac   : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Cooking_Fuel       : num  180 180 180 180 180 180 180 180 180 180 ...\n $ Other_Cooking_Fuel : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Source_Light       : num  182 182 182 182 182 182 182 182 182 182 ...\n $ Other_Source_Light : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Electricity_in_HH  : num  0 0 0 0 0 0 0 0 0 0 ...\n $ No_Of_Rooms        : num  2 2 3 1 2 3 2 1 3 1 ...\n $ No_Sleeping_Rooms  : num  2 2 2 1 2 2 2 1 1 1 ...\n```\n:::\n:::\n\n\n#### Joining (Merge)\nJoin database by ID\n\n\n::: {.cell hash='Data-Analysis-Wk1_cache/pdf/unnamed-chunk-9_1c949ab3cfb0befebc4e4cb0ef584d5b'}\n\n```{.r .cell-code .numberLines}\nmerged_left_right  <-  merge(Left, Rigth, all=TRUE, by = \"FSN\")\nstr(merged_left_right)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t13377 obs. of  40 variables:\n $ FSN                : num  45001 45002 45003 45004 45005 ...\n $ ID                 : int  1 2 3 4 5 6 7 8 9 10 ...\n $ Neem_Tree          : num  0 0 0 0 0 0 0 0 0 0 ...\n $ Neem_Tree_Distance : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Size     : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Age      : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Usage    : chr  \"\" \"\" \"\" \"\" ...\n $ Neem_Tree_Use_Other: chr  \"\" \"\" \"\" \"\" ...\n $ Bamboo_Tree        : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Bamboo_Tree_Dist   : num  3 10 16 17 5 4 15 3 1 10 ...\n $ Banana_Tree        : num  0 0 0 0 0 0 0 1 1 0 ...\n $ Banana_Tree_Dist   : num  -1 -1 -1 -1 -1 -1 -1 5 1 -1 ...\n $ Rice_Field         : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Rice_Field_Dist    : num  4 12 16 13 4 13 10 10 7 12 ...\n $ Perm_Water_Body    : num  0 0 0 0 0 0 0 0 0 0 ...\n $ Perm_Wat_Body_Dist : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Wat_Body_Mid_Point : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ No_Mosquito_Net    : num  0 2 1 0 0 0 0 0 1 0 ...\n $ Sprayed_2010       : num  86 86 86 86 86 86 86 86 86 86 ...\n $ Sprayed_2009       : num  86 86 86 86 86 86 86 86 86 86 ...\n $ Floor_Material     : num  153 153 153 153 153 153 153 153 155 153 ...\n $ Other_Floor_Mat    : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Is_Floor_Damp      : num  1 1 1 1 1 1 1 1 0 1 ...\n $ Roof_Material      : num  161 159 158 156 156 156 156 158 158 156 ...\n $ Other_Roof_Material: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Wall_Material      : num  164 164 164 162 163 163 162 164 164 162 ...\n $ Other_Wall_Material: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Windows_in_Room    : num  1 1 1 0 0 0 0 1 1 0 ...\n $ Granaries_in_HH    : num  1 1 1 0 1 1 0 1 1 0 ...\n $ Source_Drink_Water : num  167 167 92 92 92 92 92 92 92 92 ...\n $ Other_Src_Drink_Wat: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Toilet_Facility    : num  177 177 177 177 177 177 177 177 177 177 ...\n $ Other_Toilet_Fac   : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Cooking_Fuel       : num  180 180 180 180 180 180 180 180 180 180 ...\n $ Other_Cooking_Fuel : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Source_Light       : num  182 182 182 182 182 182 182 182 182 182 ...\n $ Other_Source_Light : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Electricity_in_HH  : num  0 0 0 0 0 0 0 0 0 0 ...\n $ No_Of_Rooms        : num  2 2 3 1 2 3 2 1 3 1 ...\n $ No_Sleeping_Rooms  : num  2 2 2 1 2 2 2 1 1 1 ...\n```\n:::\n:::\n\n\n\n### Exercise 2\n\n\n\n::: {.cell hash='Data-Analysis-Wk1_cache/pdf/unnamed-chunk-10_13e4068aa27216e48bba0444d1dcc9bd'}\n\n```{.r .cell-code .numberLines}\nQ1_B_1 <- read.csv(\"C:/Users/pined/OneDrive - Universidad Nacional Mayor de San Marcos/Javier 2022/Belgica/AC2_DataAnalysis_ThWk/Material/Q1_B_1.csv\", sep=\",\", dec= \".\")\n```\n:::\n\n::: {.cell hash='Data-Analysis-Wk1_cache/pdf/unnamed-chunk-11_e512fdf8b7d87e0e220bdf65af4dae00'}\n\n```{.r .cell-code .numberLines}\nstr(Q1_B_1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t9029 obs. of  6 variables:\n $ FSN              : int  45001 45001 45002 45003 45004 45006 45009 45021 45021 45024 ...\n $ Animal_Name      : chr  \"Goats\" \"Poultry (chickens, ducks, pigeon)\" \"Buffaloes\" \"Cows/Oxen\" ...\n $ Animal_Count     : int  3 1 1 1 2 2 7 3 1 3 ...\n $ Animal_Distance  : int  5 0 4 3 5 0 0 15 5 15 ...\n $ Keep_Inside_House: int  1 1 0 1 1 1 1 0 1 1 ...\n $ Days_Inside_House: int  120 365 -1 210 180 360 360 -1 150 90 ...\n```\n:::\n\n```{.r .cell-code .numberLines}\nhead(Q1_B_1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    FSN                       Animal_Name Animal_Count Animal_Distance\n1 45001                             Goats            3               5\n2 45001 Poultry (chickens, ducks, pigeon)            1               0\n3 45002                         Buffaloes            1               4\n4 45003                         Cows/Oxen            1               3\n5 45004                             Goats            2               5\n6 45006                         Cows/Oxen            2               0\n  Keep_Inside_House Days_Inside_House\n1                 1               120\n2                 1               365\n3                 0                -1\n4                 1               210\n5                 1               180\n6                 1               360\n```\n:::\n:::\n\n\n\n::: callout-tip\nWe observe:\n  - There are 9029  obs\n  - There are duplicates in FSN\n  - The animal name is quite large sometimes\n  - The variable names are quite large\n::: \n\n#### Renaming variables\n\nRenaming variables labels: In collumns 2-5 to \"anim\", \"count\", \"dist\", \"indor\", \"daysin\"\n\n\n::: {.cell hash='Data-Analysis-Wk1_cache/pdf/unnamed-chunk-12_21945023eff0d8c99fb116efbf705949'}\n\n```{.r .cell-code .numberLines}\nnames(Q1_B_1)[c(2,3,4,5,6)] <- c(\"anim\", \"count\", \"dist\", \"indor\", \"daysin\")\nstr(Q1_B_1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t9029 obs. of  6 variables:\n $ FSN   : int  45001 45001 45002 45003 45004 45006 45009 45021 45021 45024 ...\n $ anim  : chr  \"Goats\" \"Poultry (chickens, ducks, pigeon)\" \"Buffaloes\" \"Cows/Oxen\" ...\n $ count : int  3 1 1 1 2 2 7 3 1 3 ...\n $ dist  : int  5 0 4 3 5 0 0 15 5 15 ...\n $ indor : int  1 1 0 1 1 1 1 0 1 1 ...\n $ daysin: int  120 365 -1 210 180 360 360 -1 150 90 ...\n```\n:::\n:::\n\n\n\n#### Renaming observations\n\n\n\n::: {.cell hash='Data-Analysis-Wk1_cache/pdf/unnamed-chunk-13_0980db66fa64423ceb58b8bd5b998a38'}\n\n```{.r .cell-code .numberLines}\ntable(Q1_B_1$anim)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n                        Buffaloes                         Cows/Oxen \n                             1592                              3055 \n                             Dogs                             Goats \n                               38                              3816 \n                            Other                              Pigs \n                                3                                20 \nPoultry (chickens, ducks, pigeon) \n                              505 \n```\n:::\n\n```{.r .cell-code .numberLines}\nQ1_B_1$anim[Q1_B_1$anim ==\"Buffaloes\"] <- \"Buff\"\nQ1_B_1$anim[Q1_B_1$anim ==\"Goats\"] <- \"Goat\"\n\n#But if we want to keep the 4 (x) first characters in a all rows\nQ1_B_1$anim <- substr(Q1_B_1$anim, 0, 4)\ntable(Q1_B_1$anim)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nBuff Cows Dogs Goat Othe Pigs Poul \n1592 3055   38 3816    3   20  505 \n```\n:::\n\n```{.r .cell-code .numberLines}\nstr(Q1_B_1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t9029 obs. of  6 variables:\n $ FSN   : int  45001 45001 45002 45003 45004 45006 45009 45021 45021 45024 ...\n $ anim  : chr  \"Goat\" \"Poul\" \"Buff\" \"Cows\" ...\n $ count : int  3 1 1 1 2 2 7 3 1 3 ...\n $ dist  : int  5 0 4 3 5 0 0 15 5 15 ...\n $ indor : int  1 1 0 1 1 1 1 0 1 1 ...\n $ daysin: int  120 365 -1 210 180 360 360 -1 150 90 ...\n```\n:::\n:::\n\n\n\n#### Long to Wide\n\nWe need one line for each household\n\nSo, we will use reshape command to say: Reshape the database taking in to account that i want to make the database wider, having just one line for household (FSN) and replicating the variables count, dist, indor, daysin for every animal that the household had.\n\n\n\n::: {.cell hash='Data-Analysis-Wk1_cache/pdf/unnamed-chunk-14_ee399caf31c0443c05c33bb47313fcf1'}\n\n```{.r .cell-code .numberLines}\nNewtable <- reshape(Q1_B_1,direction = \"wide\", timevar =\"anim\", idvar =\"FSN\", v.names = c(\"count\",\"dist\",\"indor\", \"daysin\"), sep = \"_\")\nstr(Newtable)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t7147 obs. of  29 variables:\n $ FSN        : int  45001 45002 45003 45004 45006 45009 45021 45024 45025 45027 ...\n $ count_Goat : int  3 NA NA 2 NA 7 1 3 3 NA ...\n $ dist_Goat  : int  5 NA NA 5 NA 0 5 15 0 NA ...\n $ indor_Goat : int  1 NA NA 1 NA 1 1 1 1 NA ...\n $ daysin_Goat: int  120 NA NA 180 NA 360 150 90 90 NA ...\n $ count_Poul : int  1 NA NA NA NA NA NA NA NA 2 ...\n $ dist_Poul  : int  0 NA NA NA NA NA NA NA NA 0 ...\n $ indor_Poul : int  1 NA NA NA NA NA NA NA NA 1 ...\n $ daysin_Poul: int  365 NA NA NA NA NA NA NA NA 360 ...\n $ count_Buff : int  NA 1 NA NA NA NA NA NA NA NA ...\n $ dist_Buff  : int  NA 4 NA NA NA NA NA NA NA NA ...\n $ indor_Buff : int  NA 0 NA NA NA NA NA NA NA NA ...\n $ daysin_Buff: int  NA -1 NA NA NA NA NA NA NA NA ...\n $ count_Cows : int  NA NA 1 NA 2 NA 3 NA NA NA ...\n $ dist_Cows  : int  NA NA 3 NA 0 NA 15 NA NA NA ...\n $ indor_Cows : int  NA NA 1 NA 1 NA 0 NA NA NA ...\n $ daysin_Cows: int  NA NA 210 NA 360 NA -1 NA NA NA ...\n $ count_Pigs : int  NA NA NA NA NA NA NA NA NA NA ...\n $ dist_Pigs  : int  NA NA NA NA NA NA NA NA NA NA ...\n $ indor_Pigs : int  NA NA NA NA NA NA NA NA NA NA ...\n $ daysin_Pigs: int  NA NA NA NA NA NA NA NA NA NA ...\n $ count_Dogs : int  NA NA NA NA NA NA NA NA NA NA ...\n $ dist_Dogs  : int  NA NA NA NA NA NA NA NA NA NA ...\n $ indor_Dogs : int  NA NA NA NA NA NA NA NA NA NA ...\n $ daysin_Dogs: int  NA NA NA NA NA NA NA NA NA NA ...\n $ count_Othe : int  NA NA NA NA NA NA NA NA NA NA ...\n $ dist_Othe  : int  NA NA NA NA NA NA NA NA NA NA ...\n $ indor_Othe : int  NA NA NA NA NA NA NA NA NA NA ...\n $ daysin_Othe: int  NA NA NA NA NA NA NA NA NA NA ...\n - attr(*, \"reshapeWide\")=List of 5\n  ..$ v.names: chr [1:4] \"count\" \"dist\" \"indor\" \"daysin\"\n  ..$ timevar: chr \"anim\"\n  ..$ idvar  : chr \"FSN\"\n  ..$ times  : chr [1:7] \"Goat\" \"Poul\" \"Buff\" \"Cows\" ...\n  ..$ varying: chr [1:4, 1:7] \"count_Goat\" \"dist_Goat\" \"indor_Goat\" \"daysin_Goat\" ...\n```\n:::\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}