{
  "hash": "e31653dab9a695ed78ba8efaa3191705",
  "result": {
    "markdown": "---\ntitle: \"2023-02-13 Session 1\"\nformat: \n  html:\n    self-contained: true\n    code-line-numbers: true\ncustom_title_page: false\nfilters:\n  - lightbox\nlightbox: auto\n---\n\n---\nsubtitle: \"Survival Analysis - Session 1\"\ndate: 2023-02-13\n\nauthor:\n  - name: Javier Silva-Valencia\n    orcid: 0000-0002-5982-2821\n    email: javier.silva@unmsm.edu.pe\n    affiliations:\n      - name: Instituut Voor Tropische Geneeskunde. Antwerp-Belgium\n\nlanguage: \n  title-block-author-single: \"Writer\"\n  \nabstract: The exercise begins by asking you to identify the cases in which you need to use survival analysis. Specific patient examples are then provided to tabulate data using either the intention-to-treat approach or a per-protocol approach. Finally we create the kaplan-meyer curves.\n---\n\n\n---\n\n---\n\n\n### Starting the Exercise\n\n#### Question 1\nWhich of the following types of data can/should be analyzed using survival analysis? What would be the analysis variable? What is the time of origin and the end point? Are the data censored, and if yes, which type of censoring occurs?\n\na)  Two groups of patients with skin cancer are treated: group A gets surgical removal of the cancer, group B gets surgical removal + chemotherapy. We believe that the chemotherapy will reduce the risk of recurrence of he cancer. The patients are asked to return for a check up every 3 months for the following 5 years. At every check-up, the patients are examined for skin cancers.\n\n\n::: callout-tip\n## Reply\n\n**a1. Should be analyzed using survival analysis?**: Yes.\n\nWhy?, Because we are interested in analyzing the time from one event to another and also because the data could be censored (when we don't know exactly when is the end point for some individuals)\n\nWhy not linear regression?: Because of the censorship. There is a possibility that some individuals did not continue to follow-up or completed the study without having the event.\n\n**a2. Analysis variable**: Time to cancer recurrence\n\n**a3. Time:**\n\nMoment of origin: Moment in which the intervention is carried out\n\nEnd point: Time to cancer recurrence\n\n**a4. Are the data censored?**: Yes, censoring in survival analysis refers to the situation in which the exact time to event is not known for some individuals in a study.\n\nWhat type of censoring occurs?: Interval, because if you are studying the recurrence of cancer, you do not know if it just appeared before the appointment Also, the point where cancer begins is not well defined.\n:::\n\n\n\nb)  Two groups of patients with malaria are entered in a clinical trial: 1 group receives a new treatment, the other group receives standard care. After 3 months they are asked to return for parasitological examination. We want to see if the new treatment cures more patient than standard therapy.\n\n::: callout-tip\n## Reply\n\n**b1. Should be analyzed using survival analysis?**: No. Our outcome doesn't involve time. It is just one measure.\n\nFor this we should use Logistic Regression. Because the outcome is a binary variable..\n\n**b2. Analysis variable**:% of patients parasite-free at month 3\n:::\n\n\n\n\nc)  To assess risk behaviour for HIV and other STI's, a group of adolescents (12 to 18 years) are asked when they had sexual intercourse for the first time. We are interested in estimating the age of sexual debut.\n\n::: callout-tip\n## Reply\n\n**c1. Should be analyzed using survival analysis?**: Yes. Our outcome is the time of sexual debut. We are interested in the time from one event to another. Also the data could be censored\n\n**c2. Analysis variable**: Age of sexual debut\n\n**c3. Time:**\n      \n  Time of origin: Born\n\n  End point: Age of sexual debut\n\n**c4. Are the data censored?**: Yes. There may be adolescents who at the end of the study have not developed the result (they have not yet had sexual relations at the time of the survey).\n\n  This is a cross-sectional study but you ask for a time. (It's a bit tricky)\n\n  What type of censoring occurs? Right. Because of some teens who have not yet had sex at the time of the survey. We know that the outcome could develop after the end of the study.\n        \n:::\n\nd)  To assess risk behaviors for childhood asthma, we perform a case-control study comparing mothers of children with asthma and children without asthma. We ask the mothers when they were first pregnant. We are interested in estimating the age of first pregnancy for women with a child with asthma vs women with a child without asthma\n\n::: callout-tip\n## Reply\n\n**d1. Should be analyzed using survival analysis?**: Yes. We are interested in the time from one event to another. But, since there is no censoring here, we can also choose to use linear regression.\n\n**d2. Analysis variable**: Age at first pregnancy\n      \nIndependent variable: having or not a child with asthma\n\n**d3. Time:**\n      \n  Time of origin: Birth\n\n  End point: Age of first pregnancy\n\n\n**d4. Are the data censored?** No, censorship is when we don't know the endpoint for some individuals. In this case, all the women have had a first pregnancy, so they have all reached the outcome and we know when. Also, I cannot have losses to follow-up, because it is a cross-sectional study.\n:::\n\n#### Question 2\nWe ran a clinical trial of a new less invasive surgical procedure (treatment A) for patients with myocardial infarction. This procedure is compared to the standard treatment (treatment B) which requires open-heart surgery. After surgery patients were required to return to the clinic every 3 months for a check-up. The trial was completed on 1-Jan-2006. The primary objective of the study is to compare the two treatment groups with respect to mortality, analyzed using an intention-to-treat approach. As a secondary analysis, time to cardiac event (defined as new MI or a new cardiac procedure or cardiac death) is analyzed, using a per-protocol approach.\n\n::: {.callout-tip collapse=\"true\"}\n## Insights about Intention to treat vs Per protocol\n\nIn an intention-to-treat analysis, you analyze everyone according to the groups from the initial randomization. (Although in the end for X reasons some did not follow the planned treatment)\n\nIn a per-protocol analysis, you analyze only those who actually undergo initial randomization.\n\n![Intention to treat vs Per protocol](Intention%20to%20treat.png)\n::: \n\na. Patient 001 was randomized to treatment A. The surgery was performed on 1-Jul-2004 and was successful according to the surgeon. The patient came in for his visits and was in good health at the end of the study.\n\n::: callout-tip\nTable according to an intention-to-treat analysis\n\n| ID  | Original Treatment | Event (death) | Start date | End date | Reason of the end date | Time (start date - end date) |\n|-----------|-----------|-----------|-----------|-----------|-----------|-----------|\n| 1   | A                  | 0             | 1-jul-04   | 1-ene-06 | End of study           | 18.30                        |\n\nTable according to an per-protocol analysis\n\n| ID  | Treatment original | Real treatment | Cardiac Event | Start date | End date (first date) | Reason of the end date | Time to event (months) |\n|---------|---------|---------|---------|---------|---------|---------|---------|\n| 1   | A                  | A              | 0             | 1-jul-04   | 1-ene-06                           | End of study           | 18.30                  |\n\nThe cardiac event is defined as new MI or a new cardiac procedure or cardiac death.\n:::\n\nb. Patient 002 was randomized to treatment A. The surgery was performed on 15-Jul-2004 and was successful according to the surgeon. On 15-Nov-2004, the patient came into the hospital with a new myocardial infarction. The patient however died 15 days later in hospital.\n\n::: callout-tip\n\nAccording to an intention-to-treat analysis\n\n| ID  | Original Treatment | Event (death) | Start date | End date | Reason of the end date | Time (start date - end date) |\n|-----------|-----------|-----------|-----------|-----------|-----------|-----------|\n| 2   | A                  | 1             | 15-jul-04  | 1-dic-04 | Died                   | 4.63                         |\n\nAccording to an per-protocol analysis\n\n| ID  | Treatment original | Real treatment | Cardiac Event | Start date | End date (first date) | Reason of the end date | Time to event (months) |\n|---------|---------|---------|---------|---------|---------|---------|---------|\n| 2   | A                  | A              | 1             | 15-jul-04  | 15-nov-04                          | New MI                 | 4.10                   |\n:::\n\nc. Patient 003 was randomized to treatment B. The surgery was performed on 30-Jul-2004 and was successful. The patient came in hospital for the first 2 visits. The second visit was on 1-Feb-2005 when the patient was in good health. However the patient but did not return to the hospital after this date.\n\n::: callout-tip\nAccording to an intention-to-treat analysis\n\n| ID  | Original Treatment | Event (death) | Start date | End date | Reason of the end date | Time (start date - end date) |\n|-----------|-----------|-----------|-----------|-----------|-----------|-----------|\n| 3   | B                  | 0             | 30-jul-04  | 1-feb-05 | Lost follow up         | 6.20                         |\n\nAccording to an per-protocol analysis\n\n| ID  | Treatment original | Real treatment | Cardiac Event | Start date | End date (first date) | Reason of the end date | Time to event (months) |\n|---------|---------|---------|---------|---------|---------|---------|---------|\n| 3   | B                  | B              | 0             | 30-jul-04  | 1-feb-05                           | Lost follow up         | 6.20                   |\n:::\n\nd. Patient 004 was randomized to standard treatment. When in the operating room (on 1-Aug-2004), the surgeon however decided that the standard surgery was too dangerous to perform, due to the bad condition of the patient. Instead, the new less invasive operation was performed. The patient died in hospital 15 days after the operation.\n\n::: callout-tip\nAccording to an intention-to-treat analysis\n\n| ID  | Original Treatment | Event (death) | Start date | End date  | Reason of the end date | Time (start date - end date) |\n|-----------|-----------|-----------|-----------|-----------|-----------|-----------|\n| 4   | B                  | 1             | 1-ago-04   | 16-ago-04 | Died                   | 0.50                         |\n\nAccording to an per-protocol analysis\n\n| ID  | Treatment original | Real treatment | Cardiac Event | Start date | End date (first date) | Reason of the end date | Time to event (months) |\n|---------|---------|---------|---------|---------|---------|---------|---------|\n| 4   | B                  | A              | Excluded      |            |                                    |                        |                        |\n\nWhy in per-protocol analysis is B? Because this person did not carry out the assigned procedure (randomized), then is excluded\n\n:::\n\ne. Patient 005 was randomized to the treatment B. The surgery was performed on 1-Nov-2004 and was successful according to the surgeon. The patient returned for his first follow-up visit on 1-Feb-2005. The patient did not return to the hospital for any of the next follow-up visits. However one of the study nurses read in the newspaper that the patient (whose name she remembered) had died on 1-Sep-2005 due to a fall when performing repairs to the roof of his house.\n\n::: callout-tip\nAccording to an intention-to-treat analysis\n\n| ID  | Original Treatment | Event (death) | Start date | End date | Reason of the end date     | Time (start date - end date) |\n|-----------|-----------|-----------|-----------|-----------|-----------|-----------|\n| 5   | B                  | 1             | 1-nov-04   | 1-sep-05 | Died (even it was by fall) | 10.13                        |\n\nAccording to an per-protocol analysis\n\n| ID  | Treatment original | Real treatment | Cardiac Event | Start date | End date (first date) | Reason of the end date | Time to event (months) |\n|---------|---------|---------|---------|---------|---------|---------|---------|\n| 5   | B                  | B              | 0             | 1-nov-04   | 1-feb-05                           | Lost follow up         | 3.07                   |\n:::\n\nf. Patient 006 was randomized to the treatment A. The surgery was performed on 1-Dec-2004 and was successful according to the surgeon. On 1-Mar-2005, the patient came into the hospital with a new MI. The surgeon decided to perform open heart surgery, similar to treatment B. After this surgery, the patient did well and returned regularly to the check-ups. On 1-Jan-2006 was still alive and doing well\n\n::: callout-tip\nAccording to an intention-to-treat analysis\n\n| ID  | Original Treatment | Event (death) | Start date | End date | Reason of the end date | Time (start date - end date) |\n|-----------|-----------|-----------|-----------|-----------|-----------|-----------|\n| 6   | A                  | 0             | 1-dic-04   | 1-ene-06 | End of study           | 13.20                        |\n\nAccording to an per-protocol analysis\n\n| ID  | Treatment original | Real treatment | Cardiac Event | Start date | End date (first date) | Reason of the end date | Time to event (months) |\n|---------|---------|---------|---------|---------|---------|---------|---------|\n| 6   | A                  | A              | 1             | 1-dic-04   | 1-mar-05                           | New MI                 | 3.00                   |\n\nWhy in per-protocol analysis is still A? Because this person did carry out the assigned procedure (randomized)\n:::\n\n\n::: callout-note\n## Summary of all the cases\n\nSo the final table for intention-to-treat analysis is:\n\n| ID  | Treatment | Time (months) | Event |\n|-----|-----------|---------------|-------|\n| 1   | A         | 18.30         | 0     |\n| 2   | A         | 4.63          | 1     |\n| 3   | B         | 6.20          | 0     |\n| 4   | B         | 0.50          | 1     |\n| 5   | B         | 10.13         | 1     |\n| 6   | A         | 13.20         | 0     |\n\nAnd the final table for per-protocol analysis is:\n\n| ID  | Treatment | Time (months) | Event |\n|-----|-----------|---------------|-------|\n| 1   | A         | 18.30         | 0     |\n| 2   | A         | 4.10          | 1     |\n| 3   | B         | 6.20          | 0     |\n| 4   | A         | Excluded      |       |\n| 5   | B         | 3.07          | 0     |\n| 6   | A         | 3.00          | 1     |\n:::\n\n#### Question 3 \nPatient 003 was lost to follow-up in the trial. Can you think of ways to recover some additional data for this patient?\n\n::: callout-tip\n## Reply\n\n-   Check with other hospitals\n-   Contact with their house or relatives.\n-   Check demographics records\n:::\n\n#### Question 4 \nThe data below are from a cervical cancer trial. Enter the data in Excel and analyze the data using R.\n\nGive: \n  - Kaplan-Meier plot for the two groups\n  \n  - median survival time in each group \n  \n  - The proportion of patients alive after 2 years in each group \n  \n  - Test the difference between the two curves using the log-rank test\n\n4.1. First we import the data from the excel file\n\n\n::: {.cell hash='2023-02-13-Survival-Analysis-Session-1_cache/html/unnamed-chunk-1_9224a8813d3fb552af2728f66e5a9345'}\n\n```{.r .cell-code .numberLines}\nlibrary(readxl)\ndat <- read_excel(\"C:/Users/pined/OneDrive - Universidad Nacional Mayor de San Marcos/Javier 2022/Belgica/AC2/Survival Analysis Exercise Database/Exercises/MPH2021_T2_MAV_SurvAnal_Day_I_Result_Data.xlsx\")\n```\n:::\n\n\n4.2. To start working with survival analysis we have to create an event variable (1 when the event happened (in this case dead))\n\n\n::: {.cell hash='2023-02-13-Survival-Analysis-Session-1_cache/html/unnamed-chunk-2_8ada6f3c088c41dc902292d86470cdbc'}\n\n```{.r .cell-code .numberLines}\ndat$event <- ifelse(dat$SurvivalStatus == \"dead\", 1, 0)\n```\n:::\n\n\n4.3. We start doing the kaplan-meyer plot for the two groups\n\n\n::: {.cell hash='2023-02-13-Survival-Analysis-Session-1_cache/html/unnamed-chunk-3_cbadf2b434120c1f275f86528b68e471'}\n\n```{.r .cell-code .numberLines}\nlibrary(survival)\nmod2 <- survfit(Surv(SurvivalTime, event) ~ Therapy, data=dat)\nplot(mod2, mark.time=TRUE)\n```\n\n::: {.cell-output-display}\n![](2023-02-13-Survival-Analysis-Session-1_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n::: {.cell hash='2023-02-13-Survival-Analysis-Session-1_cache/html/unnamed-chunk-4_33338ed4021a3bd8bc37add321396d22'}\n\n:::\n\n\n4.4. To see the median survival time for each group we ask for the numbers of the model:\n\n\n::: {.cell hash='2023-02-13-Survival-Analysis-Session-1_cache/html/unnamed-chunk-5_9149b9428dcfae0c89882f83b588994a'}\n\n```{.r .cell-code .numberLines}\nmod2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCall: survfit(formula = Surv(SurvivalTime, event) ~ Therapy, data = dat)\n\n           n events median 0.95LCL 0.95UCL\nTherapy=A 16     11   1037     291      NA\nTherapy=B 14      5   1307     827      NA\n```\n:::\n:::\n\n\n::: callout-tip\n## Reply\nThe median survival time is 1037 for therapy A and 1307 for therapy B.\n\nInterpretation:\n\n- 50% of the population was alive at 1037 days in therapy group A\n      \n- 50% of the population was alive at 1307 days in therapy group B\n      \nSo,  group B (new treatment) keeps more alive for more time\n\n:::\n\n4.5. Proportion of patients alive after two years\n\nFor this we can see the graph:\n\n\n::: {.cell hash='2023-02-13-Survival-Analysis-Session-1_cache/html/unnamed-chunk-6_99d470cf4c421d02a13b41facc03e302'}\n\n```{.r .cell-code .numberLines}\nplot(mod2, mark.time=TRUE)\n```\n\n::: {.cell-output-display}\n![](2023-02-13-Survival-Analysis-Session-1_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n:::\n\n::: {.cell hash='2023-02-13-Survival-Analysis-Session-1_cache/html/unnamed-chunk-7_887aecd0eae9bc989dac0857a9667f59'}\n\n:::\n\n\n::: callout-tip\n## Reply\nSeeing the proportion of patients alive after two years (730 days)\n\nMore or less 60% in the A group and about 80% in the B group are alive after two years\n:::\n\nBut we also can see the proportions of people alive in a certain moment using summary\n\n\n::: {.cell hash='2023-02-13-Survival-Analysis-Session-1_cache/html/unnamed-chunk-8_5feb321b6efe16be9817eed37f5315cd'}\n\n```{.r .cell-code .numberLines}\nsummary(mod2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCall: survfit(formula = Surv(SurvivalTime, event) ~ Therapy, data = dat)\n\n                Therapy=A \n time n.risk n.event survival std.err lower 95% CI upper 95% CI\n   90     16       1    0.938  0.0605       0.8261        1.000\n  142     15       1    0.875  0.0827       0.7271        1.000\n  150     14       1    0.812  0.0976       0.6421        1.000\n  269     13       1    0.750  0.1083       0.5652        0.995\n  291     12       1    0.688  0.1159       0.4941        0.957\n  680     10       1    0.619  0.1230       0.4191        0.914\n  837      9       1    0.550  0.1271       0.3497        0.865\n 1037      7       1    0.471  0.1310       0.2735        0.813\n 1153      4       1    0.354  0.1417       0.1612        0.775\n 1297      3       1    0.236  0.1348       0.0768        0.723\n 1429      2       1    0.118  0.1072       0.0198        0.701\n\n                Therapy=B \n time n.risk n.event survival std.err lower 95% CI upper 95% CI\n  272     14       1    0.929  0.0688        0.803            1\n  362     13       1    0.857  0.0935        0.692            1\n  373     12       1    0.786  0.1097        0.598            1\n  827      7       1    0.673  0.1401        0.448            1\n 1307      3       1    0.449  0.2057        0.183            1\n```\n:::\n:::\n\n\n::: callout-tip\n## Reply\n  In terapy A , at the time 680, 68.8% were alive\n\n  In terapy B , at the time 827, 78.6% were alive\n\n(You need to see the number in the previous row)\n:::\n\n4.6 Test differences between both curves\n\nAre both curves different? (Curve from terapy A vs curve from terapy B). We use the Long-rank test\n\n\n::: {.cell hash='2023-02-13-Survival-Analysis-Session-1_cache/html/unnamed-chunk-9_4ddbd88940f6cecc60b87a84c7de5f67'}\n\n```{.r .cell-code .numberLines}\n#Long rank test command\nsurvdiff(Surv(SurvivalTime, event) ~ Therapy, data=dat)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nCall:\nsurvdiff(formula = Surv(SurvivalTime, event) ~ Therapy, data = dat)\n\n           N Observed Expected (O-E)^2/E (O-E)^2/V\nTherapy=A 16       11     8.44     0.780      1.68\nTherapy=B 14        5     7.56     0.869      1.68\n\n Chisq= 1.7  on 1 degrees of freedom, p= 0.2 \n```\n:::\n:::\n\n\n::: callout-tip\n## Reply\nThe p value is 0.2, so there is no statistical difference between both curves.\n:::\n\n4.7 Conclusions\n\n::: callout-tip\n## Reply\n\nThe prognosis of patients with the new treatment appeared to be better to reduce mortality cases. The median survival was 1037 days (2.8 years) in therapy group A (standard treatment) and 1307 days (3.5 years of survival) in the therapy group B (new treatment)\n\nThis difference was however not statistically significant (p-value = 0.2)\n\nThis could be because it was a small study. A new and larger clinical trial should be planned to reach a definitive conclusion.\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}