{
  "hash": "3290c4ec467c87f81f32c365eca9d565",
  "result": {
    "markdown": "---\ntitle: \"2023-02-10 Session 1\"\nformat: \n  html:\n    self-contained: true\n---\n\n\n\n-   Instituut Voor Tropische Geneeskunde - Antwerp, Belgium\n-   Javier Silva-Valencia\n\n## Step by Step\n\n##### Import data\n\nImporting a CSV database under the name of \"leprosy_comoros\", with \",\" as separator:\n\n\n::: {.cell}\n\n```{.r .cell-code}\nleprosy_comoros <- read.csv(\"C:/Users/pined/OneDrive - Universidad Nacional Mayor de San Marcos/Javier 2022/Belgica/AC2/Poisson Regression Exercise Database/Datasets/leprosy_comoros.csv\", sep=\",\")\n```\n:::\n\n\n------------------------------------------------------------------------\n\n------------------------------------------------------------------------\n\n### Starting the Exercise\n\n###### 1. Use the ‘aggregate’ function in R to determine the total population and how many cases arose over the follow-up period of 1 year? (First create a constant with a value of 1) \n\nWhat was the incidence rate? \n\n::: callout-note\n    \n    The exercise is asking to calculate the total number of cases and population    \n    during the year of the study, using the command aggregate.\n\n    So the original data is:\n\n::: {.cell}\n\n```{.r .cell-code}\nleprosy_comoros\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   PEP_19      dist_cat   pop inc_case\n1       0       same hh   735       11\n2       0 neighbor <25m  5740       37\n3       0       >25-50m  8856       37\n4       0       >50-75m  7462       34\n5       0       75-100m  5802       14\n6       0         >100m 41599       47\n7       1       same hh  1241        6\n8       1 neighbor <25m  2964        9\n9       1       >25-50m  3672        6\n10      1       >50-75m  2435        9\n11      1       75-100m  1638        5\n12      1         >100m  2571        4\n```\n:::\n:::\n\n    \n    The aggregate command could respond to the following request: \n    \"Please agregate( or sum) \"inc_case\" and \"population\" by each category of PEP_19\n\n::: {.cell}\n\n````{.cell-code}\n```{{r}}\ntable1 <- aggregate(cbind(inc_case, pop) ~ PEP_19, data=leprosy_comoros, FUN=sum)\ntable1\n```\n````\n\n::: {.cell-output .cell-output-stdout}\n```\n  PEP_19 inc_case   pop\n1      0      180 70194\n2      1       39 14521\n```\n:::\n:::\n\n    \n    But because we want all the cases and all the population during the study\n    (not by each category of PEP),\n    we have to create a new variable of just one categorie, so that when agregate\n    it calculates everything.\n    \n\n::: {.cell}\n\n````{.cell-code}\n```{{r}}\nleprosy_comoros$const <- 1\ntable1 <- aggregate(cbind(inc_case, pop) ~ const, data=leprosy_comoros, FUN=sum)\ntable1\n```\n````\n\n::: {.cell-output .cell-output-stdout}\n```\n  const inc_case   pop\n1     1      219 84715\n```\n:::\n:::\n\n    So, the incidence rate during the period of the study (1 year) is:\n    = 219/84715\n    = 0.002585138\n    = 2.59 per 1000 population\n\n\nWe can also calculate the incidence ratio using the Poisson regression\n \n    Why Poisson regression?, because the Dependent Variable is a rate.\n    \n    We will just ask for the incidence (using inc_case / population)\n    with no other variable\n\n\n::: {.cell}\n\n````{.cell-code}\n```{{r}}\n# Code for poisson regression (univariate analysis)\nGLM0 <- glm(inc_case ~  offset(log(pop)) , family=poisson(log), data=leprosy_comoros)\nsummary(GLM0)\nexp(coef(GLM0))\nexp(confint(GLM0))\n```\n````\n\n::: {.cell-output .cell-output-stderr}\n```\nWaiting for profiling to be done...\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = inc_case ~ offset(log(pop)), family = poisson(log), \n    data = leprosy_comoros)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-6.5783  -0.4730   0.7412   2.7829   4.8259  \n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept) -5.95798    0.06757  -88.17   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for poisson family taken to be 1)\n\n    Null deviance: 109.51  on 11  degrees of freedom\nResidual deviance: 109.51  on 11  degrees of freedom\nAIC: 164.39\n\nNumber of Fisher Scoring iterations: 5\n\n(Intercept) \n0.002585138 \n      2.5 %      97.5 % \n0.002257694 0.002942787 \n```\n:::\n:::\n\n\n::: callout-note\nWe can see in the results that the incidence rate during the period of the study (1 year) is:\n\n    = exp(-5.95798)*1000\n    = 0.002585138 *1000\n    = 2.59 per 1000 population\n\nSo its the same result. We can calculate the incidence rate both ways\n::: \n\n\n\n\n###### 2. What can you say about the effect of PEP, did it protect?\n\nSo far now the Dependent Variable is: Incidence rate of cases\n\nThe Independent variable is: Received PEP (PEP_19)\n\nThe Covariant is: Distance to the nearest other person (disc_cat)\n\n\n2.1 First we explore bivariate relation (incidence cases - PEP_19)\n\n::: callout-note\n To calculate the RR (between incidence and PEP) we cannot do it in a table2x2 because the variables of interest are not categorical and are not dichotomies, so we use the Poisson regression\n \n    Why Poisson regression?, because the Dependent Variable is a rate\n::: \n\nDoing the poisson regression (bivariate analysis: Incidenc rate and PEP_19)\n\n::: {.cell}\n\n````{.cell-code}\n```{{r}}\n# Code for poisson regression (bivariate analysis)\nGLM1 <- glm(inc_case ~  offset(log(pop)) + PEP_19 , family=poisson(log), data=leprosy_comoros)\nsummary(GLM1)\nexp(coef(GLM1))\nexp(confint(GLM1))\n```\n````\n\n::: {.cell-output .cell-output-stderr}\n```\nWaiting for profiling to be done...\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = inc_case ~ offset(log(pop)) + PEP_19, family = poisson(log), \n    data = leprosy_comoros)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-6.5040  -0.4727   0.6352   2.8244   4.8630  \n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept) -5.96606    0.07454 -80.043   <2e-16 ***\nPEP_19       0.04627    0.17663   0.262    0.793    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for poisson family taken to be 1)\n\n    Null deviance: 109.51  on 11  degrees of freedom\nResidual deviance: 109.44  on 10  degrees of freedom\nAIC: 166.32\n\nNumber of Fisher Scoring iterations: 5\n\n(Intercept)      PEP_19 \n0.002564322 1.047358997 \n                  2.5 %      97.5 %\n(Intercept) 0.002207713 0.002957382\nPEP_19      0.730667264 1.463060462\n```\n:::\n:::\n\n\n::: callout-note\nSo, is PEP associated with incidence? No,  the p value is 0.793 \n\nWe can also see the RR\nRR of PEP = 1.047358997 IC(0.73 - 1.46)\n  So, so far it seems that PEP is a risk factor, not significant, is that true?, \n  We should see counfonders\n::: \n\n###### 3. The data presented here mixes up 4 different study arms, in villages randomized to study arm 1, no PEP was provided, in study arm 2 PEP was provided to household contacts of index cases, in study arm 3 PEP was provided to entire villages and in study arm 4 PEP was provided to household contacts as well as others living in the same village and testing positive to a serological screening test but asymptomatic. As a result there may be an association between PEP and distance to nearest index case. If distance would also be associated with risk of becoming an incident case, distance could be a confounder. First check if distance is indeed associated with risk of becoming an incident case. Make a table with numbers of population, cases and risk ratios + confidence intervals for the 6 distance categories\n\n3.1 We check if distance is indeed associated with risk of becoming an incident case\n\nFirst we count how many cases are by each distance category\n\n::: {.cell}\n\n````{.cell-code}\n```{{r}}\n# We can do it with the command table, but also with aggregate\ntable2 <- aggregate(cbind(inc_case, pop) ~ dist_cat, data=leprosy_comoros, FUN=sum)\ntable2\n```\n````\n\n::: {.cell-output .cell-output-stdout}\n```\n       dist_cat inc_case   pop\n1         >100m       51 44170\n2       >25-50m       43 12528\n3       >50-75m       43  9897\n4       75-100m       19  7440\n5 neighbor <25m       46  8704\n6       same hh       17  1976\n```\n:::\n:::\n\n\nNow we do the poisson regression (bivariate analysis: Incidence rate, dist)\n\n::: {.cell}\n\n````{.cell-code}\n```{{r}}\n# Code for poisson regression (bivariate analysis)\nGLM2 <- glm(inc_case ~  offset(log(pop)) + factor(dist_cat) , family=poisson(log), data=leprosy_comoros)\nsummary(GLM2)\nexp(coef(GLM2))\nexp(confint(GLM2))\n```\n````\n\n::: {.cell-output .cell-output-stderr}\n```\nWaiting for profiling to be done...\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = inc_case ~ offset(log(pop)) + factor(dist_cat), \n    family = poisson(log), data = leprosy_comoros)\n\nDeviance Residuals: \n     Min        1Q    Median        3Q       Max  \n-2.07373  -0.76420   0.06291   0.71563   1.68133  \n\nCoefficients:\n                              Estimate Std. Error z value Pr(>|z|)    \n(Intercept)                    -6.7640     0.1400 -48.304  < 2e-16 ***\nfactor(dist_cat)>25-50m         1.0895     0.2070   5.262 1.42e-07 ***\nfactor(dist_cat)>50-75m         1.3252     0.2070   6.401 1.55e-10 ***\nfactor(dist_cat)75-100m         0.7938     0.2688   2.953  0.00314 ** \nfactor(dist_cat)neighbor <25m   1.5211     0.2033   7.480 7.40e-14 ***\nfactor(dist_cat)same hh         2.0084     0.2800   7.171 7.42e-13 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for poisson family taken to be 1)\n\n    Null deviance: 109.511  on 11  degrees of freedom\nResidual deviance:  16.492  on  6  degrees of freedom\nAIC: 81.368\n\nNumber of Fisher Scoring iterations: 4\n\n                  (Intercept)       factor(dist_cat)>25-50m \n                   0.00115463                    2.97265107 \n      factor(dist_cat)>50-75m       factor(dist_cat)75-100m \n                   3.76289507                    2.21175943 \nfactor(dist_cat)neighbor <25m       factor(dist_cat)same hh \n                   4.57716083                    7.45107964 \n                                     2.5 %       97.5 %\n(Intercept)                   0.0008660436  0.001501143\nfactor(dist_cat)>25-50m       1.9737201350  4.456174129\nfactor(dist_cat)>50-75m       2.4984102103  5.640795139\nfactor(dist_cat)75-100m       1.2743641132  3.678635507\nfactor(dist_cat)neighbor <25m 3.0643672475  6.818042875\nfactor(dist_cat)same hh       4.1804487877 12.625252928\n```\n:::\n:::\n\n::: callout-note\n\n| Distance      \t| Population \t| Cases \t| RR  \t| 95% IC   \t|\n|---------------\t|------------\t|-------\t|-----\t|----------\t|\n| Same HH       \t| 1976       \t| 17    \t| 7.5 \t| 4.2-12.6 \t|\n| Neighbor <25m \t| 8704       \t| 46    \t| 4.6 \t| 3.1-6.8  \t|\n| 25-50m        \t| 12528      \t| 43    \t| 3.0 \t| 2.0-4.5  \t|\n| 50-75m        \t| 9897       \t| 43    \t| 3.8 \t| 2.5-5.6  \t|\n| 75-100m       \t| 7440       \t| 19    \t| 2.2 \t| 1.3-3.7  \t|\n| 100+m         \t| 44170      \t| 51    \t| Ref \t| Ref      \t|\n\nSo the distance is indeed associated with the incidence of leprosy\nwith more near are the cases more is a risk factor\n\nThere is a clear a link between leprasy and distance\nThe probability of receive a PEP is associated at the distance\n\nAlso, we have to consider than distance could be a confounder because:\n    1. Is to the VD, 2. Is related to the VI, and 3. Is not in the causal pathway\n                \n                (Leprasy Infection) --------- (PEP-19)\n                                  \\           /\n                                   Confounders\n                                    (Distance)\n\n::: \n\n\n###### 4. Now that you have shown that distance is clearly associated with risk of disease, fit a poisson model that includes distance and PEP. What happens to the effect of PEP? \n\nFor this we do poisson regression (multivariate analysis: Incidence, PEP, dist)\n\n::: {.cell}\n\n````{.cell-code}\n```{{r}}\n# Code for poisson regression (multivariate analysis)\nGLM3 <- glm(inc_case ~  offset(log(pop)) + PEP_19 + factor(dist_cat) , family=poisson(log), data=leprosy_comoros)\nsummary(GLM3)\nexp(coef(GLM3))\nexp(confint(GLM3))\n```\n````\n\n::: {.cell-output .cell-output-stderr}\n```\nWaiting for profiling to be done...\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = inc_case ~ offset(log(pop)) + PEP_19 + factor(dist_cat), \n    family = poisson(log), data = leprosy_comoros)\n\nDeviance Residuals: \n      1        2        3        4        5        6        7        8  \n 0.8075   0.2849   0.4073  -0.3502  -0.5833  -0.3179  -0.8944  -0.5363  \n      9       10       11       12  \n-0.8804   0.7566   1.2478   1.4215  \n\nCoefficients:\n                              Estimate Std. Error z value Pr(>|z|)    \n(Intercept)                    -6.7397     0.1402 -48.079  < 2e-16 ***\nPEP_19                         -0.5320     0.1854  -2.869  0.00412 ** \nfactor(dist_cat)>25-50m         1.1940     0.2092   5.708 1.14e-08 ***\nfactor(dist_cat)>50-75m         1.4079     0.2083   6.758 1.40e-11 ***\nfactor(dist_cat)75-100m         0.8647     0.2695   3.208  0.00133 ** \nfactor(dist_cat)neighbor <25m   1.6482     0.2066   7.977 1.50e-15 ***\nfactor(dist_cat)same hh         2.2839     0.2929   7.797 6.33e-15 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for poisson family taken to be 1)\n\n    Null deviance: 109.5113  on 11  degrees of freedom\nResidual deviance:   7.4757  on  5  degrees of freedom\nAIC: 74.351\n\nNumber of Fisher Scoring iterations: 4\n\n                  (Intercept)                        PEP_19 \n                  0.001183039                   0.587440946 \n      factor(dist_cat)>25-50m       factor(dist_cat)>50-75m \n                  3.300353348                   4.087421777 \n      factor(dist_cat)75-100m factor(dist_cat)neighbor <25m \n                  2.374303585                   5.197433272 \n      factor(dist_cat)same hh \n                  9.815321524 \n                                     2.5 %       97.5 %\n(Intercept)                   0.0008871107  0.001538568\nPEP_19                        0.4032137828  0.835625711\nfactor(dist_cat)>25-50m       2.1820609064  4.967595519\nfactor(dist_cat)>50-75m       2.7068955509  6.142667468\nfactor(dist_cat)75-100m       1.3661994452  3.954939056\nfactor(dist_cat)neighbor <25m 3.4569176392  7.790047953\nfactor(dist_cat)same hh       5.3795372678 17.072393655\n```\n:::\n:::\n\n::: callout-note\n\nSo, what happens to the efect of PEEP?\n\n    Is PEP now significant?\n    Yes after adjusting with distance, the p value for PEP is 0.00412, \n    so now the association is significant\n\nAlso the RR of PEP now is 0.587440946  IC (0.4032137828  0.835625711)\nso is significative protective.\n\n::: \n\n###### 5. Assume we are fitting a significance based classic model. Is the model with both PEP and distance better than the model with only distance? \n\nI already know that the association is significant, but for being sure they are asking to compare both models (with and without distance)(GLM1 vs GLM3) to see in there is a significant improvement\n\n\n::: {.cell}\n\n```{.r .cell-code}\nanova(GLM3, GLM1, test=\"Chisq\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAnalysis of Deviance Table\n\nModel 1: inc_case ~ offset(log(pop)) + PEP_19 + factor(dist_cat)\nModel 2: inc_case ~ offset(log(pop)) + PEP_19\n  Resid. Df Resid. Dev Df Deviance  Pr(>Chi)    \n1         5      7.476                          \n2        10    109.443 -5  -101.97 < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\n::: callout-note\n\nThe p value is 2.2e-16 , so it is a significant difference between both models\nSo we keep the GLM3 model\n\n::: \n\n###### 6. Check the dispersion parameter, is it far removed from 1? Is there a problem with the condition that mean should be more or less equal to variance\n\nOne of the main conditions for us to use Poisson regression is to check for overdispersion (if the mean is similar to the variance), if the result is close to 1 then if Poisson can be used, otherwise we will use binomial regression negative\n\n\n::: {.cell}\n\n````{.cell-code}\n```{{r}}\n# Code for checking for overdispersion\ndispp <- sum(residuals(GLM3, type=\"pearson\")^2)/GLM3$df.residual\ndispp\n```\n````\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.703122\n```\n:::\n:::\n\n::: callout-note\n\nThe dispersion parameter is 1.7 so it is near to one.\n\nThen is ok to use the poisson regression.\n\nYet, just for educational purpuses we are going to test the negative binomial regression\n\n::: \n\n###### 7. Even though it is not necessary in this case, try to fit a negative binomial model. Does the result differ?\n\nIf we don't have the library MASS we should install it\n\n::: {.cell}\n\n```{.r .cell-code}\n#install.packages(\"MASS\")\n```\n:::\n\n::: {.cell}\n\n````{.cell-code}\n```{{r}}\n# Code for poisson regression (multivariate analysis)\nlibrary(MASS)\nGLM.NM1 <- glm.nb(inc_case ~  offset(log(pop)) + PEP_19 + factor(dist_cat), data=leprosy_comoros)\n```\n````\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in theta.ml(Y, mu, sum(w), w, limit = control$maxit, trace =\ncontrol$trace > : iteration limit reached\n\nWarning in theta.ml(Y, mu, sum(w), w, limit = control$maxit, trace =\ncontrol$trace > : iteration limit reached\n```\n:::\n\n````{.cell-code}\n```{{r}}\nexp(coef(GLM.NM1))\nexp(confint(GLM.NM1))\n```\n````\n\n::: {.cell-output .cell-output-stderr}\n```\nWaiting for profiling to be done...\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n                  (Intercept)                        PEP_19 \n                  0.001183054                   0.587446051 \n      factor(dist_cat)>25-50m       factor(dist_cat)>50-75m \n                  3.300273827                   4.087400355 \n      factor(dist_cat)75-100m factor(dist_cat)neighbor <25m \n                  2.374295046                   5.197325128 \n      factor(dist_cat)same hh \n                  9.815151563 \n                                     2.5 %      97.5 %\n(Intercept)                   0.0008870494  0.00153864\nPEP_19                        0.4031984916  0.83565023\nfactor(dist_cat)>25-50m       2.1818890837  4.96772620\nfactor(dist_cat)>50-75m       2.7067289044  6.14295421\nfactor(dist_cat)75-100m       1.3660182361  3.95513469\nfactor(dist_cat)neighbor <25m 3.4566639695  7.79027966\nfactor(dist_cat)same hh       5.3787294252 17.07279368\n```\n:::\n:::\n\n::: callout-note\n\nThe OR and IC are similar in bot models (poisson and negative binomial model)\n\n::: \n\n\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}