{
  "hash": "dc7ec9fd9ec8746a7a8edb3e62ac5940",
  "result": {
    "markdown": "---\ntitle: \"2023-02-01. Session 2\"\nformat: \n  html:\n    self-contained: true\n    code-line-numbers: true\ncustom_title_page: false\nfilters:\n  - lightbox\nlightbox: auto\nnumber-sections: false\nfig-cap-location: top\n---\n\n---\nsubtitle: \"Linear Regression - Session 2\"\ndate: 2023-02-01\n\nauthor:\n  - name: Javier Silva-Valencia\n    orcid: 0000-0002-5982-2821\n    email: javier.silva@unmsm.edu.pe\n    affiliations:\n      - name: Instituut Voor Tropische Geneeskunde. Antwerp-Belgium\n\nlanguage: \n  title-block-author-single: \"Writer\"\n  \nabstract: The exercise asks to review again the concepts of intercept, slope and coefficient of determination. However this time in a multivariate linear regression (for 2 independent variables). But first, to know if we can use linear regression or not, we have to test its assumptions (linearity, variance homogeneity, normality and independence of observations). Likewise to use linear regression correctly we need to check for exceptional values (outliers), influential observations or if we need to do any transformation of the variable.\n---\n\n\n------------------------------------------------------------------------\n\n------------------------------------------------------------------------\n\n### Starting the Exercise\n\n**Instructions:**\n\nUse database evans_county.csv. Explore the data. There is a variable QTI,' Quetelet Index' which is equivalent to the BMI, weight in kg divided by the squared height in meters.\n\nIs the Queteled Index(QTI) associated with systolic blood pressure(SBP)?\n\n-   Independent variable: QTI\n-   Dependent variable: SBP\n\n#### Import data\n\nImporting a CSV database under the name of \"evans\", with \",\" as separator and \".\" as decimal:\n\n\n::: {.cell hash='2023-02-01-Linear-Regresion,-Sessión-2_cache/html/unnamed-chunk-1_a447ce422d616a511a17890f6006ce4f'}\n\n```{.r .cell-code .numberLines}\nevans <- read.csv(\"C:/Users/pined/OneDrive - Universidad Nacional Mayor de San Marcos/Javier 2022/Belgica/AC2/Linear Regresion Exercise Database/Datasets/evans_county.csv\", sep=\",\", dec= \".\")\n```\n:::\n\n\nWe assume that all variables ok to start (we dont need to transform or create variables)\n\n#### Explore the data\n\nIt is a good practice to explore the data (Doing bivariate analysis). In this case we can do it quicky with a scatterplot\n\n\n::: {.cell hash='2023-02-01-Linear-Regresion,-Sessión-2_cache/html/fig-plot_47cc7821c2aa0fd3c97702b45ae8ea25'}\n\n```{.r .cell-code .numberLines}\n#Code in R:          \n  # Make a scatterplot\n  plot(evans$QTI, evans$SBP, main=\"Scatterplot\")\n  # add a regression line\n  abline(lm(SBP~QTI, data = evans), col = \"blue\")\n```\n\n::: {.cell-output-display}\n![](2023-02-01-Linear-Regresion,-Sessión-2_files/figure-html/fig-plot-1.png){#fig-plot width=672}\n:::\n:::\n\n\n::: callout-note\nWe can see that there could be a correlation, although it doesn't seem very strong.\n:::\n\n#### Question 1\n\nWhat is the regression equation?\n\nFirst we are going to do the regression analysis for only SBP and QTI (bivariate)\n\n\n::: {.cell hash='2023-02-01-Linear-Regresion,-Sessión-2_cache/html/unnamed-chunk-3_2f0addcd3da4e4f238fa2936376aa536'}\n\n```{.r .cell-code .numberLines}\n#Code for linear regresion:\n  lmQTI = lm(SBP ~ QTI, data = evans)\n  summary(lmQTI)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = SBP ~ QTI, data = evans)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-54.855 -19.634  -5.213  14.743 155.497 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  129.420      6.875  18.824   <2e-16 ***\nQTI            4.439      1.876   2.366   0.0183 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 27.4 on 607 degrees of freedom\nMultiple R-squared:  0.00914,\tAdjusted R-squared:  0.007508 \nF-statistic: 5.599 on 1 and 607 DF,  p-value: 0.01828\n```\n:::\n:::\n\n\n::: callout-note\n-As a result: we can create the equation with the data we obtained\n\n    * Formula:  y = a+b(x)\n    * a = 129.420\n    * b = 4.439\n        (b is the slope, \n        it means that for every increase of 1 in QTI the SBP increase in 4.43)\n\n    So, the equation would be:\n    * Y= 129.420 + 4.439(X)\n:::\n\n#### Question 2\n\nHow much is the determination coefficient? What does it mean?\n\n::: callout-note\n-The determination coefficient is R2 = 0.009\n\n    Interpretation: \n    \" __%  of the variability of the outcome could be explained by the model \"\n    \"0.9% of the variability of the SBP(blood preasure) could be explained by the model\"\n:::\n\n#### Question 3\n\nIs the slope for QTI statistically significant?\n\n::: callout-note\n-The slope for QTI is 4.439, and its p value is 0.0183 (less than 0.05)\n\n    Interpretation: \n    *The p-value in this case says that there is a statistical association between QTI and SBP (ie, the same as saying that \"the slope of the regression line is significantly different from zero)\"\n:::\n\n### Testing assumptions\n\n::: {.callout-tip collapse=\"true\"}\n## What assumptions?\n\nIn order to say whether it is correct to use linear regression, we must first know if certain conditions are met. These conditions are called assumptions.\n\nWhat are the assumptions to decide whether or not to use linear regression? In addition that our dependent variables need to be a continuous numerical variable, we seek to comply with:\n\n1.  Linearity\n2.  Homogeneity of variance\n3.  Normality\n4.  Independence of observations\n\nFor the first 3 we have to check the residuals. The last one is a theoretical concept of what our data is like.\n:::\n\nTo test for the assumptions first we need to calculate the residuals.\n\nThe residuals can be put as another variable in the data set and also with them the estimated outcome(fitted) can be calculated. Both as new variables\n\n\n::: {.cell hash='2023-02-01-Linear-Regresion,-Sessión-2_cache/html/unnamed-chunk-4_28aa449e2c74d4a4ec008cb790d1a6f7'}\n\n```{.r .cell-code .numberLines}\n#Creating the residuals and fitted values as new variables\nevans$mod_resid <- residuals(lmQTI)\nevans$mod_fitted <- fitted(lmQTI)\n```\n:::\n\n\n#### Question 4\n\nChecking for Linearity: Is the association between SBP and QTI a linear association?\n\nFor this we scatterplot the residuals(new variable) against the exposure(the independent variable)\n\n\n::: {.cell hash='2023-02-01-Linear-Regresion,-Sessión-2_cache/html/fig-plot2_7da272516239e31d4ed0ceb2410e8a02'}\n\n```{.r .cell-code .numberLines}\n#Code in R:          \n  # Make a scatterplot\n  plot(evans$QTI, evans$mod_resid, main=\"Scatterplot\")\n  # add a regression line\n  abline(lm(mod_resid~QTI, data = evans), col = \"blue\")\n```\n\n::: {.cell-output-display}\n![](2023-02-01-Linear-Regresion,-Sessión-2_files/figure-html/fig-plot2-1.png){#fig-plot2 width=672}\n:::\n:::\n\n\n::: callout-tip\n## Interpretation\n\nFor Linearity we scatterplot the **residuals against the exposure(VI)**\n\nIn this case we see all the dots as a cloud, this suggests that we can assume linearity\n:::\n\n#### Question 5\n\nChecking for Homogeneity of variance: Is the variance of the residuals homogeneous?\n\nWe scatterplot the residuals against the estimated outcome(fitted)\n\n\n::: {.cell hash='2023-02-01-Linear-Regresion,-Sessión-2_cache/html/fig-plot3_006ec4bd5a221f2faa315f496c466231'}\n\n```{.r .cell-code .numberLines}\n#Code in R:          \n  # Make a scatterplot\n  plot(evans$mod_fitted, evans$mod_resid, main=\"Scatterplot\")\n  # add a regression line\n  abline(lm(mod_resid ~ mod_fitted, data = evans), col = \"blue\")\n```\n\n::: {.cell-output-display}\n![](2023-02-01-Linear-Regresion,-Sessión-2_files/figure-html/fig-plot3-1.png){#fig-plot3 width=672}\n:::\n:::\n\n\n::: callout-tip\n## Interpretation\n\nFor Homogeneity of variance we scatterplot the **residuals against estimated outcome(fitted)**\n\nIn this case we see all the dots as a cloud, then we assume homogeneity\n:::\n\n#### Question 6\n\nChecking for Normality: Are the residuals normally distributed?\n\n\n::: {.cell hash='2023-02-01-Linear-Regresion,-Sessión-2_cache/html/fig-plot4_a199dab6cf2414e38547f8a8ac5b6a4c'}\n\n```{.r .cell-code .numberLines}\n#Doing an histogram of the residuals\n  hist(evans$mod_resid,main=\"Age distribution of study participants\", ylab=\"nb\", col=\"green\", border=\"dark green\")\n```\n\n::: {.cell-output-display}\n![](2023-02-01-Linear-Regresion,-Sessión-2_files/figure-html/fig-plot4-1.png){#fig-plot4 width=672}\n:::\n:::\n\n\n::: callout-tip\n## Interpretation\n\nFor checking normality we do an histogram of the **residuals**\n\nIn this case it seems not, but it is debatable\n:::\n\n#### Question 7\n\nChecking for Independence: Are the observations independent?\n\n::: callout-tip\n## Interpretation\n\nWe don't need to do any calculation for this.\n\nBecause we are not working with sequential measures (in time or in space): The observations are independent\n:::\n\n### Rare values\n\n#### Question 8\n\nAre there any extreme values?\n\n::: callout-tip\n## Reply\n\nFor answer this we need to made a scatter plot of the **residuals against the estimated outcome (fitted)** (we already did this in @fig-plot3 )\n\nFor discussion. It does seem to have some extreme values.\n:::\n\n#### Question 9\n\nAre there any influential observation?\n\n::: callout-tip\n## Reply\n\nFor answer this we need to made a scatter plot of the **residuals against the exposure** (we already did this in @fig-plot2 )\n\nFor discussion. It does seem to have some influential observations.\n:::\n\n#### Question 10\n\nDoes the model significantly improve when the variable AGE is added?\n\nThe exercise is asking to doing an multivariate linear regression\n\n\n::: {.cell hash='2023-02-01-Linear-Regresion,-Sessión-2_cache/html/unnamed-chunk-8_d86d973493f90161d3a7ffc57a3ed7cf'}\n\n```{.r .cell-code .numberLines}\n#Code for linear regresion:\n  lmQTI_AGE = lm(SBP ~ QTI + AGE, data = evans)\n  summary(lmQTI_AGE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = SBP ~ QTI + AGE, data = evans)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-57.645 -15.916  -3.985  11.393 160.285 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  73.4912     9.2816   7.918 1.16e-14 ***\nQTI           5.6031     1.7809   3.146  0.00173 ** \nAGE           0.9630     0.1139   8.452  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 25.93 on 606 degrees of freedom\nMultiple R-squared:  0.1136,\tAdjusted R-squared:  0.1107 \nF-statistic: 38.84 on 2 and 606 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\n::: callout-note\n-A. As a result: we can create the new formula with the data we obtained\n\n    * y = a + b1(x1) + b2(x2)\n    * a= 73.4912\n    * b1 = 5.6031\n    * b2 = 0.9630\n    So, the formula would be:\n    * Y= 73.4912 + 5.6031(QTI) + 0.9630(AGE)\n\n-B. We also find the R2\n\n    * R2 is the \"Determination coefficient\". \n    * R2 =  0.1136\n    Interpretation: \n    \"11% of the variability of the SBP could be explained by the model\"\n\n-C. Does the model significantly improve when the variable AGE is added?\n\n    * It improves, but I dont know if it is a significantly improvement. \n:::\n\nTo know if it is a significant improvement, we can do an anova table comparing the 2 models\n\n\n::: {.cell hash='2023-02-01-Linear-Regresion,-Sessión-2_cache/html/unnamed-chunk-9_69ed0faa4e9887721800bf1aff32ca6d'}\n\n```{.r .cell-code .numberLines}\n#Code for ANOVA\n    anova (lmQTI,lmQTI_AGE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAnalysis of Variance Table\n\nModel 1: SBP ~ QTI\nModel 2: SBP ~ QTI + AGE\n  Res.Df    RSS Df Sum of Sq      F    Pr(>F)    \n1    607 455567                                  \n2    606 407530  1     48037 71.432 < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\n::: callout-tip\n## Reply\n\np = 2.2e-16\n\nThis means that the second model has a significant difference to the first model, so including AGE has increased significantly the model.\n:::\n\n#### Question 11\n\nWhich proportion of the variability in SBP is explained by this model?\n\n::: callout-tip\n## Reply\n\nThey are asking for the R2 (\"Determination coefficient\")\n\nWe already did it in question 10\n\nR2 = 0.1136\n\nInterpretation: \"11% of the variability of the SBP could be explained by the model\"\n:::\n\n#### Question 12\n\nPlease write down the equation of the model\n\n::: callout-tip\n## Reply\n\nWe already did it in question 10\n\ny = a + b1(x1) + b2(x2)\n\n-   a= 73.4912\n-   b1 = 5.6031\n-   b2 = 0.9630\n\nSo, the formula would be:\n\nY= 73.4912 + 5.6031(QTI) + 0.9630(AGE)\n:::\n\nFinish =)\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}