{
  "hash": "5ce31948e23d99ebbc565c927c1cfe6e",
  "result": {
    "markdown": "---\ntitle: \"2023-02-09 CaseAssignm\"\nformat: \n  html:\n    self-contained: true\n---\n\n\n-   Instituut Voor Tropische Geneeskunde - Antwerp, Belgium\n\n## Step by Step \n\n##### Import data\n\nImporting a CSV database under the name of \"VL_Bihar\":\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-1_0e394de8a8a914d5290a9fb72f670a2b'}\n\n```{.r .cell-code .numberLines}\nlibrary(readxl)\nVL_Bihar <- read_excel(\"C:/Users/pined/OneDrive - Universidad Nacional Mayor de San Marcos/Javier 2022/Belgica/AC2/Logistic Regresion Exercise Database/Datasets/VL_Bihar.xlsx\")\n```\n:::\n\n\n### Starting the Exercise:\n\n##### 1. Description of the study population\n\n1.1 Sex\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-2_caf2121cde68d472b07df8ca51a3c38c'}\n\n````{.cell-code .numberLines}\n```{{r}}\ntable(VL_Bihar$sex, useNA = \"always\")     #frecuency\nprop.table(table(VL_Bihar$sex))           #proportion\n```\n````\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   1    2 <NA> \n 907  973    0 \n\n        1         2 \n0.4824468 0.5175532 \n```\n:::\n:::\n\n\n1.2 Age\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-3_96349ec0d78092cb0ce8dacf4079453a'}\n\n````{.cell-code .numberLines}\n```{{r}}\nsummary(VL_Bihar$age)\n```\n````\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n   2.00    8.00   19.50   24.15   35.00   90.00       2 \n```\n:::\n:::\n\n\n1.2.1 Categories of age\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-4_b1c0194525b7d0e7faf5dfe69e9f47a8'}\n\n````{.cell-code .numberLines}\n```{{r}}\n#Group Age\nVL_Bihar$groupage <- NA\nVL_Bihar$groupage[VL_Bihar$age<15] <- \"0\"\nVL_Bihar$groupage[VL_Bihar$age>14 & VL_Bihar$age<35] <- \"1\"\nVL_Bihar$groupage[VL_Bihar$age>34] <- \"2\"\n\ntable(VL_Bihar$groupage, useNA = \"always\")     #frecuency\nprop.table(table(VL_Bihar$groupage, useNA = \"always\"))           #proportion\n```\n````\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   0    1    2 <NA> \n 765  608  505    2 \n\n         0          1          2       <NA> \n0.40691489 0.32340426 0.26861702 0.00106383 \n```\n:::\n:::\n\n\n1.3 Case\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-5_249dd8f8a034adcdef34ea8b39b4e3bf'}\n\n````{.cell-code .numberLines}\n```{{r}}\ntable(VL_Bihar$case, useNA = \"always\")     #frecuency\nprop.table(table(VL_Bihar$case))           #proportion\n```\n````\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   0    1 <NA> \n1673  207    0 \n\n        0         1 \n0.8898936 0.1101064 \n```\n:::\n:::\n\n\n1.4. Died\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-6_008588253df39e792ebef111ea083c07'}\n\n````{.cell-code .numberLines}\n```{{r}}\ntable(VL_Bihar$died, useNA = \"always\")     #frecuency\nprop.table(table(VL_Bihar$died))           #proportion\n```\n````\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   0    1 <NA> \n1877    3    0 \n\n          0           1 \n0.998404255 0.001595745 \n```\n:::\n:::\n\n\n1.5. neem_tree\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-7_3706e8c2a0ce65403cfdc8d4d1c53605'}\n\n````{.cell-code .numberLines}\n```{{r}}\ntable(VL_Bihar$neem_tree, useNA = \"always\")     #frecuency\nprop.table(table(VL_Bihar$neem_tree))           #proportion\n```\n````\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   0    1 <NA> \n1122  758    0 \n\n        0         1 \n0.5968085 0.4031915 \n```\n:::\n:::\n\n\n1.6. bamboo_tree\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-8_ce8d72cd876e682b32b6c428b2821838'}\n\n````{.cell-code .numberLines}\n```{{r}}\ntable(VL_Bihar$bamboo_tree, useNA = \"always\")     #frecuency\nprop.table(table(VL_Bihar$bamboo_tree))           #proportion\n```\n````\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   0    1 <NA> \n1144  736    0 \n\n        0         1 \n0.6085106 0.3914894 \n```\n:::\n:::\n\n\n1.7. banana_tree\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-9_a3df892c8f66c133fd4bb67923d2bd09'}\n\n````{.cell-code .numberLines}\n```{{r}}\ntable(VL_Bihar$banana_tree, useNA = \"always\")     #frecuency\nprop.table(table(VL_Bihar$banana_tree))           #proportion\n```\n````\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   0    1 <NA> \n 304 1576    0 \n\n        0         1 \n0.1617021 0.8382979 \n```\n:::\n:::\n\n\n1.8. rice_field\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-10_958ae59eec8fe92b553b783168d6f1c1'}\n\n````{.cell-code .numberLines}\n```{{r}}\ntable(VL_Bihar$rice_field, useNA = \"always\")     #frecuency\nprop.table(table(VL_Bihar$rice_field))           #proportion\n```\n````\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   0    1 <NA> \n 379 1501    0 \n\n        0         1 \n0.2015957 0.7984043 \n```\n:::\n:::\n\n\n1.9. permanent_water_body\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-11_0b64fa24e9353b9d314d45d6272138f4'}\n\n````{.cell-code .numberLines}\n```{{r}}\ntable(VL_Bihar$permanent_water_body, useNA = \"always\")     #frecuency\nprop.table(table(VL_Bihar$permanent_water_body))           #proportion\n```\n````\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   0    1 <NA> \n1002  878    0 \n\n        0         1 \n0.5329787 0.4670213 \n```\n:::\n:::\n\n\n1.10 granaries_in_hh\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-12_86e76d73a9856b209ec8d6d254e5e093'}\n\n````{.cell-code .numberLines}\n```{{r}}\ntable(VL_Bihar$granaries_in_hh, useNA = \"always\")     #frecuency\nprop.table(table(VL_Bihar$granaries_in_hh))           #proportion\n```\n````\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   0    1 <NA> \n 806 1074    0 \n\n        0         1 \n0.4287234 0.5712766 \n```\n:::\n:::\n\n\n1.11 owngoat\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-13_65e91df57da3b51e38c1ee30d1f62265'}\n\n````{.cell-code .numberLines}\n```{{r}}\ntable(VL_Bihar$owngoat, useNA = \"always\")     #frecuency\nprop.table(table(VL_Bihar$owngoat))           #proportion\n```\n````\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   0    1 <NA> \n1282  598    0 \n\n        0         1 \n0.6819149 0.3180851 \n```\n:::\n:::\n\n\n1.12 ownpoul\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-14_a1bcac65261eef63e05305e7afbbc0b6'}\n\n````{.cell-code .numberLines}\n```{{r}}\ntable(VL_Bihar$ownpoul, useNA = \"always\")     #frecuency\nprop.table(table(VL_Bihar$ownpoul))           #proportion\n```\n````\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   0    1 <NA> \n1799   81    0 \n\n         0          1 \n0.95691489 0.04308511 \n```\n:::\n:::\n\n\n1.13 ownbov\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-15_b436708cf10c22c60240e4f3ca980377'}\n\n````{.cell-code .numberLines}\n```{{r}}\ntable(VL_Bihar$ownbov, useNA = \"always\")     #frecuency\nprop.table(table(VL_Bihar$ownbov))           #proportion\n```\n````\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   0    1 <NA> \n1161  719    0 \n\n        0         1 \n0.6175532 0.3824468 \n```\n:::\n:::\n\n\n1.14 bednet\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-16_e64514daaed39e226df6b18c392add33'}\n\n````{.cell-code .numberLines}\n```{{r}}\ntable(VL_Bihar$bednet, useNA = \"always\")     #frecuency\nprop.table(table(VL_Bihar$bednet))           #proportion\n```\n````\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   0    1 <NA> \n1507  373    0 \n\n        0         1 \n0.8015957 0.1984043 \n```\n:::\n:::\n\n\n1.15 asset_index\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-17_e8523d90ad1224f9ceec8c8cc61f5d9b'}\n\n````{.cell-code .numberLines}\n```{{r}}\ntable(VL_Bihar$asset_index, useNA = \"always\")     #frecuency\nprop.table(table(VL_Bihar$asset_index))           #proportion\n```\n````\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   1    2    3    4    5 <NA> \n 447  374  325  392  342    0 \n\n        1         2         3         4         5 \n0.2377660 0.1989362 0.1728723 0.2085106 0.1819149 \n```\n:::\n:::\n\n\n1.16 riskwall\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-18_d8daea4d022fd49e750c215c0ee893e3'}\n\n````{.cell-code .numberLines}\n```{{r}}\ntable(VL_Bihar$riskwall, useNA = \"always\")     #frecuency\nprop.table(table(VL_Bihar$riskwall))           #proportion\n```\n````\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   0    1 <NA> \n1104  776    0 \n\n       0        1 \n0.587234 0.412766 \n```\n:::\n:::\n\n\n1.17 earthfloor\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-19_ad109925409eaa8ae4883911d7d5f6a8'}\n\n````{.cell-code .numberLines}\n```{{r}}\ntable(VL_Bihar$earthfloor, useNA = \"always\")     #frecuency\nprop.table(table(VL_Bihar$earthfloor))           #proportion\n```\n````\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   0    1 <NA> \n 171 1709    0 \n\n         0          1 \n0.09095745 0.90904255 \n```\n:::\n:::\n\n\n1.18 sc_caste\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-20_d2cf35d104725ed4b1638f6ddfa8eba8'}\n\n````{.cell-code .numberLines}\n```{{r}}\ntable(VL_Bihar$sc_caste, useNA = \"always\")     #frecuency\nprop.table(table(VL_Bihar$sc_caste))           #proportion\n```\n````\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   0    1 <NA> \n1808   72    0 \n\n         0          1 \n0.96170213 0.03829787 \n```\n:::\n:::\n\n\n##### 2. Bivariate analysis\n\n2.1 Case and sex\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-21_34c13085ea4ba48a4ab7f7b884d8c5aa'}\n\n````{.cell-code .numberLines}\n```{{r}}\nGLM1 <- glm(formula = case ~ factor(sex), family = binomial, data = VL_Bihar)\n    summary(GLM1)\n    exp(coef(GLM1))\n    exp(confint(GLM1))\n```\n````\n\n::: {.cell-output .cell-output-stderr}\n```\nWaiting for profiling to be done...\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = case ~ factor(sex), family = binomial, data = VL_Bihar)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-0.5011  -0.5011  -0.4657  -0.4657   2.1332  \n\nCoefficients:\n             Estimate Std. Error z value Pr(>|z|)    \n(Intercept)   -2.0118     0.1029 -19.544   <2e-16 ***\nfactor(sex)2  -0.1550     0.1474  -1.051    0.293    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1303.7  on 1879  degrees of freedom\nResidual deviance: 1302.6  on 1878  degrees of freedom\nAIC: 1306.6\n\nNumber of Fisher Scoring iterations: 4\n\n (Intercept) factor(sex)2 \n   0.1337500    0.8564302 \n                 2.5 %    97.5 %\n(Intercept)  0.1087251 0.1628343\nfactor(sex)2 0.6410060 1.1433795\n```\n:::\n:::\n\n\n2.2 Case and age\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-22_72aa82129ff77800e8244ebfd8c25b29'}\n\n````{.cell-code .numberLines}\n```{{r}}\nGLM2 <- glm(formula = case ~ age, family = binomial, data = VL_Bihar)\n    summary(GLM2)\n    exp(coef(GLM2))\n    exp(confint(GLM2))\n```\n````\n\n::: {.cell-output .cell-output-stderr}\n```\nWaiting for profiling to be done...\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = case ~ age, family = binomial, data = VL_Bihar)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-0.5340  -0.5134  -0.4815  -0.4272   2.2860  \n\nCoefficients:\n             Estimate Std. Error z value Pr(>|z|)    \n(Intercept) -1.854781   0.118111 -15.704   <2e-16 ***\nage         -0.010493   0.004288  -2.447   0.0144 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1299.1  on 1877  degrees of freedom\nResidual deviance: 1292.8  on 1876  degrees of freedom\n  (2 observations deleted due to missingness)\nAIC: 1296.8\n\nNumber of Fisher Scoring iterations: 5\n\n(Intercept)         age \n  0.1564872   0.9895616 \n                2.5 %    97.5 %\n(Intercept) 0.1236807 0.1965649\nage         0.9810855 0.9977385\n```\n:::\n:::\n\n\n2.2.1 Case and age group\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-23_43f13706bf24b8cb59b46ce5fa04b630'}\n\n````{.cell-code .numberLines}\n```{{r}}\nGLM2_1 <- glm(formula = case ~ groupage, family = binomial, data = VL_Bihar)\n    summary(GLM2_1)\n    exp(coef(GLM2_1))\n    exp(confint(GLM2_1))\n```\n````\n\n::: {.cell-output .cell-output-stderr}\n```\nWaiting for profiling to be done...\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = case ~ groupage, family = binomial, data = VL_Bihar)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-0.5265  -0.5265  -0.4677  -0.4270   2.2092  \n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept)  -1.9062     0.1077 -17.696   <2e-16 ***\ngroupage1    -0.2515     0.1712  -1.469   0.1419    \ngroupage2    -0.4430     0.1910  -2.319   0.0204 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1299.1  on 1877  degrees of freedom\nResidual deviance: 1293.1  on 1875  degrees of freedom\n  (2 observations deleted due to missingness)\nAIC: 1299.1\n\nNumber of Fisher Scoring iterations: 5\n\n(Intercept)   groupage1   groupage2 \n  0.1486486   0.7776480   0.6420824 \n                2.5 %    97.5 %\n(Intercept) 0.1196675 0.1826217\ngroupage1   0.5538452 1.0847758\ngroupage2   0.4379600 0.9277561\n```\n:::\n:::\n\n\n2.3 Case and died\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-24_f60b844243b6ffd91a3e36ee586763e7'}\n\n````{.cell-code .numberLines}\n```{{r}}\nGLM3 <- glm(formula = case ~ factor(died), family = binomial, data = VL_Bihar)\n    summary(GLM3)\n    exp(coef(GLM3))\n    exp(confint(GLM3))\n```\n````\n\n::: {.cell-output .cell-output-stderr}\n```\nWaiting for profiling to be done...\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: glm.fit: fitted probabilities numerically 0 or 1 occurred\n\nWarning: glm.fit: fitted probabilities numerically 0 or 1 occurred\n\nWarning: glm.fit: fitted probabilities numerically 0 or 1 occurred\n\nWarning: glm.fit: fitted probabilities numerically 0 or 1 occurred\n\nWarning: glm.fit: fitted probabilities numerically 0 or 1 occurred\n\nWarning: glm.fit: fitted probabilities numerically 0 or 1 occurred\n\nWarning: glm.fit: fitted probabilities numerically 0 or 1 occurred\n\nWarning: glm.fit: fitted probabilities numerically 0 or 1 occurred\n\nWarning: glm.fit: fitted probabilities numerically 0 or 1 occurred\n\nWarning: glm.fit: fitted probabilities numerically 0 or 1 occurred\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = case ~ factor(died), family = binomial, data = VL_Bihar)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-0.4797  -0.4797  -0.4797  -0.4797   2.1068  \n\nCoefficients:\n               Estimate Std. Error z value Pr(>|z|)    \n(Intercept)    -2.10425    0.07416 -28.375   <2e-16 ***\nfactor(died)1  16.67032  509.65213   0.033    0.974    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1303.7  on 1879  degrees of freedom\nResidual deviance: 1290.5  on 1878  degrees of freedom\nAIC: 1294.5\n\nNumber of Fisher Scoring iterations: 13\n\n  (Intercept) factor(died)1 \n 1.219366e-01  1.737115e+07 \n                     2.5 %    97.5 %\n(Intercept)   1.051421e-01 0.1406351\nfactor(died)1 2.290754e-22        NA\n```\n:::\n:::\n\n\n2.4 Case and neem_tree\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-25_e36be1688155a362fe4bfb1c4b6fce86'}\n\n````{.cell-code .numberLines}\n```{{r}}\nGLM4 <- glm(formula = case ~ factor(neem_tree), family = binomial, data = VL_Bihar)\n    summary(GLM4)\n    exp(coef(GLM4))\n    exp(confint(GLM4))\n```\n````\n\n::: {.cell-output .cell-output-stderr}\n```\nWaiting for profiling to be done...\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = case ~ factor(neem_tree), family = binomial, data = VL_Bihar)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-0.5023  -0.5023  -0.5023  -0.4533   2.1571  \n\nCoefficients:\n                   Estimate Std. Error z value Pr(>|z|)    \n(Intercept)        -2.00635    0.09236 -21.724   <2e-16 ***\nfactor(neem_tree)1 -0.21755    0.15330  -1.419    0.156    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1303.7  on 1879  degrees of freedom\nResidual deviance: 1301.7  on 1878  degrees of freedom\nAIC: 1305.7\n\nNumber of Fisher Scoring iterations: 4\n\n       (Intercept) factor(neem_tree)1 \n         0.1344793          0.8044893 \n                       2.5 %   97.5 %\n(Intercept)        0.1117282 0.160517\nfactor(neem_tree)1 0.5933996 1.083238\n```\n:::\n:::\n\n\n2.5 Case and bamboo_tree\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-26_74a8ed446c3905b15e1f4f8633510a05'}\n\n````{.cell-code .numberLines}\n```{{r}}\nGLM5 <- glm(formula = case ~ factor(bamboo_tree), family = binomial, data = VL_Bihar)\n    summary(GLM5)\n    exp(coef(GLM5))\n    exp(confint(GLM5))\n```\n````\n\n::: {.cell-output .cell-output-stderr}\n```\nWaiting for profiling to be done...\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = case ~ factor(bamboo_tree), family = binomial, \n    data = VL_Bihar)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-0.5287  -0.5287  -0.4518  -0.4518   2.1600  \n\nCoefficients:\n                     Estimate Std. Error z value Pr(>|z|)    \n(Intercept)          -2.23069    0.09987 -22.335   <2e-16 ***\nfactor(bamboo_tree)1  0.33357    0.14817   2.251   0.0244 *  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1303.7  on 1879  degrees of freedom\nResidual deviance: 1298.7  on 1878  degrees of freedom\nAIC: 1302.7\n\nNumber of Fisher Scoring iterations: 4\n\n         (Intercept) factor(bamboo_tree)1 \n            0.107454             1.395946 \n                          2.5 %    97.5 %\n(Intercept)          0.08787735 0.1300431\nfactor(bamboo_tree)1 1.04293293 1.8656202\n```\n:::\n:::\n\n\n2.6 Case and banana_tree\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-27_adb845537f7ddd99272b3948a7e4811d'}\n\n````{.cell-code .numberLines}\n```{{r}}\nGLM6 <- glm(formula = case ~ factor(banana_tree), family = binomial, data = VL_Bihar)\n    summary(GLM6)\n    exp(coef(GLM6))\n    exp(confint(GLM6))\n```\n````\n\n::: {.cell-output .cell-output-stderr}\n```\nWaiting for profiling to be done...\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = case ~ factor(banana_tree), family = binomial, \n    data = VL_Bihar)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-0.5021  -0.4793  -0.4793  -0.4793   2.1076  \n\nCoefficients:\n                     Estimate Std. Error z value Pr(>|z|)    \n(Intercept)          -2.00747    0.17751 -11.309   <2e-16 ***\nfactor(banana_tree)1 -0.09866    0.19511  -0.506    0.613    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1303.7  on 1879  degrees of freedom\nResidual deviance: 1303.5  on 1878  degrees of freedom\nAIC: 1307.5\n\nNumber of Fisher Scoring iterations: 4\n\n         (Intercept) factor(banana_tree)1 \n           0.1343284            0.9060498 \n                          2.5 %    97.5 %\n(Intercept)          0.09330639 0.1875041\nfactor(banana_tree)1 0.62506879 1.3458822\n```\n:::\n:::\n\n\n2.7 Case and rice_field\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-28_c903c493e25182fd386441043b9554a0'}\n\n````{.cell-code .numberLines}\n```{{r}}\nGLM7 <- glm(formula = case ~ factor(rice_field), family = binomial, data = VL_Bihar)\n    summary(GLM7)\n    exp(coef(GLM7))\n    exp(confint(GLM7))\n```\n````\n\n::: {.cell-output .cell-output-stderr}\n```\nWaiting for profiling to be done...\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = case ~ factor(rice_field), family = binomial, data = VL_Bihar)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-0.4949  -0.4949  -0.4949  -0.4336   2.1960  \n\nCoefficients:\n                    Estimate Std. Error z value Pr(>|z|)    \n(Intercept)          -2.3172     0.1797 -12.894   <2e-16 ***\nfactor(rice_field)1   0.2790     0.1970   1.416    0.157    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1303.7  on 1879  degrees of freedom\nResidual deviance: 1301.6  on 1878  degrees of freedom\nAIC: 1305.6\n\nNumber of Fisher Scoring iterations: 4\n\n        (Intercept) factor(rice_field)1 \n         0.09855074          1.32186819 \n                         2.5 %    97.5 %\n(Intercept)         0.06804181 0.1379605\nfactor(rice_field)1 0.90960592 1.9741271\n```\n:::\n:::\n\n\n2.8 Case and permanent_water_body\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-29_d59a4e9f2d8ce9b853a00781ce98fc98'}\n\n````{.cell-code .numberLines}\n```{{r}}\nGLM8 <- glm(formula = case ~ factor(permanent_water_body), family = binomial, data = VL_Bihar)\n    summary(GLM8)\n    exp(coef(GLM8))\n    exp(confint(GLM8))\n```\n````\n\n::: {.cell-output .cell-output-stderr}\n```\nWaiting for profiling to be done...\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = case ~ factor(permanent_water_body), family = binomial, \n    data = VL_Bihar)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-0.4846  -0.4846  -0.4812  -0.4812   2.1040  \n\nCoefficients:\n                              Estimate Std. Error z value Pr(>|z|)    \n(Intercept)                   -2.08281    0.10065 -20.693   <2e-16 ***\nfactor(permanent_water_body)1 -0.01469    0.14773  -0.099    0.921    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1303.7  on 1879  degrees of freedom\nResidual deviance: 1303.7  on 1878  degrees of freedom\nAIC: 1307.7\n\nNumber of Fisher Scoring iterations: 4\n\n                  (Intercept) factor(permanent_water_body)1 \n                    0.1245791                     0.9854151 \n                                  2.5 %   97.5 %\n(Intercept)                   0.1017388 0.151011\nfactor(permanent_water_body)1 0.7368210 1.315789\n```\n:::\n:::\n\n\n2.9 Case and granaries_in_hh\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-30_a90d488793215d1a3b9f6195fd9839ba'}\n\n````{.cell-code .numberLines}\n```{{r}}\nGLM9 <- glm(formula = case ~ factor(granaries_in_hh), family = binomial, data = VL_Bihar)\n    summary(GLM9)\n    exp(coef(GLM9))\n    exp(confint(GLM9))\n```\n````\n\n::: {.cell-output .cell-output-stderr}\n```\nWaiting for profiling to be done...\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = case ~ factor(granaries_in_hh), family = binomial, \n    data = VL_Bihar)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-0.4838  -0.4838  -0.4825  -0.4825   2.1016  \n\nCoefficients:\n                          Estimate Std. Error z value Pr(>|z|)    \n(Intercept)              -2.086439   0.112383 -18.565   <2e-16 ***\nfactor(granaries_in_hh)1 -0.005634   0.148829  -0.038     0.97    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1303.7  on 1879  degrees of freedom\nResidual deviance: 1303.7  on 1878  degrees of freedom\nAIC: 1307.7\n\nNumber of Fisher Scoring iterations: 4\n\n             (Intercept) factor(granaries_in_hh)1 \n               0.1241283                0.9943820 \n                              2.5 %    97.5 %\n(Intercept)              0.09893469 0.1537828\nfactor(granaries_in_hh)1 0.74366989 1.3337585\n```\n:::\n:::\n\n\n2.10 Case and owngoat\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-31_04f222c911637e529045b1896eb2debc'}\n\n````{.cell-code .numberLines}\n```{{r}}\nGLM10 <- glm(formula = case ~ factor(owngoat), family = binomial, data = VL_Bihar)\n    summary(GLM10)\n    exp(coef(GLM10))\n    exp(confint(GLM10))\n```\n````\n\n::: {.cell-output .cell-output-stderr}\n```\nWaiting for profiling to be done...\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = case ~ factor(owngoat), family = binomial, data = VL_Bihar)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-0.5065  -0.5065  -0.4717  -0.4717   2.1218  \n\nCoefficients:\n                 Estimate Std. Error z value Pr(>|z|)    \n(Intercept)      -2.13963    0.09099 -23.516   <2e-16 ***\nfactor(owngoat)1  0.15100    0.15514   0.973     0.33    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1303.7  on 1879  degrees of freedom\nResidual deviance: 1302.8  on 1878  degrees of freedom\nAIC: 1306.8\n\nNumber of Fisher Scoring iterations: 4\n\n     (Intercept) factor(owngoat)1 \n       0.1176983        1.1629911 \n                      2.5 %    97.5 %\n(Intercept)      0.09804742 0.1401079\nfactor(owngoat)1 0.85459470 1.5712859\n```\n:::\n:::\n\n\n2.11 Case and ownpoul\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-32_9861aee4b284f726e9c8fb75322b01b2'}\n\n````{.cell-code .numberLines}\n```{{r}}\nGLM11 <- glm(formula = case ~ factor(ownpoul), family = binomial, data = VL_Bihar)\n    summary(GLM11)\n    exp(coef(GLM11))\n    exp(confint(GLM11))\n```\n````\n\n::: {.cell-output .cell-output-stderr}\n```\nWaiting for profiling to be done...\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = case ~ factor(ownpoul), family = binomial, data = VL_Bihar)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-0.5915  -0.4777  -0.4777  -0.4777   2.1105  \n\nCoefficients:\n                 Estimate Std. Error z value Pr(>|z|)    \n(Intercept)      -2.11302    0.07601 -27.800   <2e-16 ***\nfactor(ownpoul)1  0.45846    0.31210   1.469    0.142    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1303.7  on 1879  degrees of freedom\nResidual deviance: 1301.8  on 1878  degrees of freedom\nAIC: 1305.8\n\nNumber of Fisher Scoring iterations: 4\n\n     (Intercept) factor(ownpoul)1 \n       0.1208723        1.5816404 \n                     2.5 %    97.5 %\n(Intercept)      0.1038311 0.1398946\nfactor(ownpoul)1 0.8221058 2.8219122\n```\n:::\n:::\n\n\n2.12 Case and ownbov\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-33_aa83529a54a741f4f33d40b482c1ef4a'}\n\n````{.cell-code .numberLines}\n```{{r}}\nGLM12 <- glm(formula = case ~ factor(ownbov), family = binomial, data = VL_Bihar)\n    summary(GLM12)\n    exp(coef(GLM12))\n    exp(confint(GLM12))\n```\n````\n\n::: {.cell-output .cell-output-stderr}\n```\nWaiting for profiling to be done...\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = case ~ factor(ownbov), family = binomial, data = VL_Bihar)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-0.4889  -0.4889  -0.4793  -0.4793   2.1075  \n\nCoefficients:\n                Estimate Std. Error z value Pr(>|z|)    \n(Intercept)     -2.10587    0.09435 -22.320   <2e-16 ***\nfactor(ownbov)1  0.04199    0.15105   0.278    0.781    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1303.7  on 1879  degrees of freedom\nResidual deviance: 1303.7  on 1878  degrees of freedom\nAIC: 1307.7\n\nNumber of Fisher Scoring iterations: 4\n\n    (Intercept) factor(ownbov)1 \n      0.1217391       1.0428795 \n                    2.5 %    97.5 %\n(Intercept)     0.1007174 0.1458382\nfactor(ownbov)1 0.7734163 1.3992746\n```\n:::\n:::\n\n\n2.13 Case and bednet\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-34_05c32e9058d1b4c24f974b1e26decb80'}\n\n````{.cell-code .numberLines}\n```{{r}}\nGLM13 <- glm(formula = case ~ factor(bednet), family = binomial, data = VL_Bihar)\n    summary(GLM13)\n    exp(coef(GLM13))\n    exp(confint(GLM13))\n```\n````\n\n::: {.cell-output .cell-output-stderr}\n```\nWaiting for profiling to be done...\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = case ~ factor(bednet), family = binomial, data = VL_Bihar)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-0.5103  -0.5103  -0.5103  -0.3568   2.3605  \n\nCoefficients:\n                Estimate Std. Error z value Pr(>|z|)    \n(Intercept)     -1.97272    0.07868 -25.073  < 2e-16 ***\nfactor(bednet)1 -0.74972    0.22918  -3.271  0.00107 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1303.7  on 1879  degrees of freedom\nResidual deviance: 1291.2  on 1878  degrees of freedom\nAIC: 1295.2\n\nNumber of Fisher Scoring iterations: 5\n\n    (Intercept) factor(bednet)1 \n      0.1390779       0.4725000 \n                    2.5 %    97.5 %\n(Intercept)     0.1188343 0.1617957\nfactor(bednet)1 0.2941532 0.7252757\n```\n:::\n:::\n\n\n2.14 Case and asset_index\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-35_6d7eeaeb56af41fe2d844b33fe5e4d2a'}\n\n````{.cell-code .numberLines}\n```{{r}}\nGLM14 <- glm(formula = case ~ factor(asset_index), family = binomial, data = VL_Bihar)\n    summary(GLM14)\n    exp(coef(GLM14))\n    exp(confint(GLM14))\n```\n````\n\n::: {.cell-output .cell-output-stderr}\n```\nWaiting for profiling to be done...\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = case ~ factor(asset_index), family = binomial, \n    data = VL_Bihar)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-0.5882  -0.5860  -0.4628  -0.2995   2.5007  \n\nCoefficients:\n                      Estimate Std. Error z value Pr(>|z|)    \n(Intercept)          -1.666909   0.129399 -12.882  < 2e-16 ***\nfactor(asset_index)2 -0.008126   0.192010  -0.042 0.966243    \nfactor(asset_index)3 -0.513337   0.224659  -2.285 0.022315 *  \nfactor(asset_index)4 -0.860198   0.232339  -3.702 0.000214 ***\nfactor(asset_index)5 -1.415001   0.294023  -4.813 1.49e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1303.7  on 1879  degrees of freedom\nResidual deviance: 1260.9  on 1875  degrees of freedom\nAIC: 1270.9\n\nNumber of Fisher Scoring iterations: 5\n\n         (Intercept) factor(asset_index)2 factor(asset_index)3 \n           0.1888298            0.9919070            0.5984951 \nfactor(asset_index)4 factor(asset_index)5 \n           0.4230784            0.2429255 \n                         2.5 %    97.5 %\n(Intercept)          0.1454019 0.2416577\nfactor(asset_index)2 0.6793381 1.4439490\nfactor(asset_index)3 0.3813144 0.9223585\nfactor(asset_index)4 0.2647424 0.6603038\nfactor(asset_index)5 0.1317253 0.4204629\n```\n:::\n:::\n\n\n2.15 Case and riskwall\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-36_99c06ebbe7eb250fca6acee77d898045'}\n\n````{.cell-code .numberLines}\n```{{r}}\nGLM15 <- glm(formula = case ~ factor(riskwall), family = binomial, data = VL_Bihar)\n    summary(GLM15)\n    exp(coef(GLM15))\n    exp(confint(GLM15))\n```\n````\n\n::: {.cell-output .cell-output-stderr}\n```\nWaiting for profiling to be done...\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = case ~ factor(riskwall), family = binomial, data = VL_Bihar)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-0.5717  -0.5717  -0.4124  -0.4124   2.2391  \n\nCoefficients:\n                  Estimate Std. Error z value Pr(>|z|)    \n(Intercept)        -2.4218     0.1100 -22.019  < 2e-16 ***\nfactor(riskwall)1   0.6933     0.1489   4.657 3.21e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1303.7  on 1879  degrees of freedom\nResidual deviance: 1281.8  on 1878  degrees of freedom\nAIC: 1285.8\n\nNumber of Fisher Scoring iterations: 5\n\n      (Intercept) factor(riskwall)1 \n        0.0887574         2.0003035 \n                     2.5 %    97.5 %\n(Intercept)       0.071064 0.1094251\nfactor(riskwall)1 1.495792 2.6830202\n```\n:::\n:::\n\n\n2.16 Case and earthfloor\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-37_091ef47fdeedf63cce2af48361b2983c'}\n\n````{.cell-code .numberLines}\n```{{r}}\nGLM16 <- glm(formula = case ~ factor(earthfloor), family = binomial, data = VL_Bihar)\n    summary(GLM16)\n    exp(coef(GLM16))\n    exp(confint(GLM16))\n```\n````\n\n::: {.cell-output .cell-output-stderr}\n```\nWaiting for profiling to be done...\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = case ~ factor(earthfloor), family = binomial, data = VL_Bihar)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-0.5002  -0.5002  -0.5002  -0.5002   2.5884  \n\nCoefficients:\n                    Estimate Std. Error z value Pr(>|z|)    \n(Intercept)          -3.3142     0.4154  -7.979 1.47e-15 ***\nfactor(earthfloor)1   1.2990     0.4221   3.077  0.00209 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1303.7  on 1879  degrees of freedom\nResidual deviance: 1289.8  on 1878  degrees of freedom\nAIC: 1293.8\n\nNumber of Fisher Scoring iterations: 5\n\n        (Intercept) factor(earthfloor)1 \n         0.03636366          3.66544816 \n                         2.5 %     97.5 %\n(Intercept)         0.01429586 0.07505732\nfactor(earthfloor)1 1.74657291 9.41739018\n```\n:::\n:::\n\n\n2.17 Case and sc_caste\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-38_3fff2d6a2c47aa11f3187f33a9a84e4e'}\n\n````{.cell-code .numberLines}\n```{{r}}\nGLM17 <- glm(formula = case ~ factor(sc_caste), family = binomial, data = VL_Bihar)\n    summary(GLM17)\n    exp(coef(GLM17))\n    exp(confint(GLM17))\n```\n````\n\n::: {.cell-output .cell-output-stderr}\n```\nWaiting for profiling to be done...\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = case ~ factor(sc_caste), family = binomial, data = VL_Bihar)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-1.0842  -0.4512  -0.4512  -0.4512   2.1611  \n\nCoefficients:\n                  Estimate Std. Error z value Pr(>|z|)    \n(Intercept)       -2.23339    0.07954 -28.079  < 2e-16 ***\nfactor(sc_caste)1  2.01024    0.25015   8.036 9.28e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1303.7  on 1879  degrees of freedom\nResidual deviance: 1248.7  on 1878  degrees of freedom\nAIC: 1252.7\n\nNumber of Fisher Scoring iterations: 5\n\n      (Intercept) factor(sc_caste)1 \n        0.1071647         7.4651429 \n                       2.5 %     97.5 %\n(Intercept)       0.09138689  0.1248467\nfactor(sc_caste)1 4.54860989 12.1710268\n```\n:::\n:::\n\n\n##### 3. Multivariate analysis. Association between incidence of visceral leshmanis and regular use of bednet and which factors are potential confounders\n\nWe will do the \"Change in Estimate Model\"\n\nStep 1. We select the factor that can be the main exposure and the other exposures that have logic\n\n::: callout-note\nMain exposure: regular use of bed net\n\nExclude: Died\n:::\n\nStep 2. First do the crude odd ratio (bivariate)\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-39_e4e32777812b9d6804994e922a696b97'}\n\n````{.cell-code .numberLines}\n```{{r}}\nML1 <- glm(factor(case) ~ factor(bednet), family=binomial, data=VL_Bihar)\nsummary(ML1)\nexp(coef(ML1))\nexp(confint(ML1))\n```\n````\n\n::: {.cell-output .cell-output-stderr}\n```\nWaiting for profiling to be done...\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = factor(case) ~ factor(bednet), family = binomial, \n    data = VL_Bihar)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-0.5103  -0.5103  -0.5103  -0.3568   2.3605  \n\nCoefficients:\n                Estimate Std. Error z value Pr(>|z|)    \n(Intercept)     -1.97272    0.07868 -25.073  < 2e-16 ***\nfactor(bednet)1 -0.74972    0.22918  -3.271  0.00107 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1303.7  on 1879  degrees of freedom\nResidual deviance: 1291.2  on 1878  degrees of freedom\nAIC: 1295.2\n\nNumber of Fisher Scoring iterations: 5\n\n    (Intercept) factor(bednet)1 \n      0.1390779       0.4725000 \n                    2.5 %    97.5 %\n(Intercept)     0.1188343 0.1617957\nfactor(bednet)1 0.2941532 0.7252757\n```\n:::\n:::\n\n\nStep 3. Then adding each other variable and writing it down. And doing the table of how much change the OR\n\nCase - bednet + sex\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-40_43effb2b23d65ff53cafd6348f6b1c74'}\n\n````{.cell-code .numberLines}\n```{{r}}\nML2 <- glm(factor(case) ~ factor(bednet) + factor(sex), family=binomial, data=VL_Bihar)\nexp(coef(ML2))\nexp(confint(ML2))\n```\n````\n\n::: {.cell-output .cell-output-stderr}\n```\nWaiting for profiling to be done...\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n    (Intercept) factor(bednet)1    factor(sex)2 \n      0.1497557       0.4737404       0.8623835 \n                    2.5 %    97.5 %\n(Intercept)     0.1208915 0.1836368\nfactor(bednet)1 0.2948994 0.7272629\nfactor(sex)2    0.6449093 1.1523372\n```\n:::\n:::\n\n\nCase - bednet + age\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-41_6499054a0546c5f78489d767441e8800'}\n\n````{.cell-code .numberLines}\n```{{r}}\nML3 <- glm(factor(case) ~ factor(bednet) + age, family=binomial, data=VL_Bihar)\nexp(coef(ML3))\nexp(confint(ML3))\n```\n````\n\n::: {.cell-output .cell-output-stderr}\n```\nWaiting for profiling to be done...\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n    (Intercept) factor(bednet)1             age \n      0.1689851       0.4963053       0.9909758 \n                    2.5 %    97.5 %\n(Intercept)     0.1331263 0.2129796\nfactor(bednet)1 0.3083839 0.7636801\nage             0.9824605 0.9991968\n```\n:::\n:::\n\n\nCase - bednet + groupage\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-42_36ef1ec3c1a7603284dcd0aeda619ab5'}\n\n````{.cell-code .numberLines}\n```{{r}}\nML3_2 <- glm(factor(case) ~ factor(bednet) + groupage, family=binomial, data=VL_Bihar)\nexp(coef(ML3_2))\nexp(confint(ML3_2))\n```\n````\n\n::: {.cell-output .cell-output-stderr}\n```\nWaiting for profiling to be done...\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n    (Intercept) factor(bednet)1       groupage1       groupage2 \n      0.1613022       0.4961901       0.8078296       0.6846378 \n                    2.5 %    97.5 %\n(Intercept)     0.1293122 0.1990533\nfactor(bednet)1 0.3082705 0.7636340\ngroupage1       0.5745769 1.1285375\ngroupage2       0.4659519 0.9917488\n```\n:::\n:::\n\n\nCase - bednet + neem_tree\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-43_829b4705d2f4198a33997fc22721685b'}\n\n````{.cell-code .numberLines}\n```{{r}}\nML4 <- glm(factor(case) ~ factor(bednet) + factor(neem_tree), family=binomial, data=VL_Bihar)\nexp(coef(ML4))\nexp(confint(ML4))\n```\n````\n\n::: {.cell-output .cell-output-stderr}\n```\nWaiting for profiling to be done...\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n       (Intercept)    factor(bednet)1 factor(neem_tree)1 \n         0.1507119          0.4740451          0.8096511 \n                       2.5 %    97.5 %\n(Intercept)        0.1242335 0.1813191\nfactor(bednet)1    0.2950723 0.7277817\nfactor(neem_tree)1 0.5967055 1.0911650\n```\n:::\n:::\n\n\nCase - bednet + bamboo_tree\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-44_e5670b4ea16813e0c9ed2c103a17e2fb'}\n\n````{.cell-code .numberLines}\n```{{r}}\nML5 <- glm(factor(case) ~ factor(bednet) + factor(bamboo_tree), family=binomial, data=VL_Bihar)\nexp(coef(ML5))\nexp(confint(ML5))\n```\n````\n\n::: {.cell-output .cell-output-stderr}\n```\nWaiting for profiling to be done...\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n         (Intercept)      factor(bednet)1 factor(bamboo_tree)1 \n           0.1218403            0.4833793            1.3557781 \n                          2.5 %    97.5 %\n(Intercept)          0.09872222 0.1488309\nfactor(bednet)1      0.30071367 0.7426603\nfactor(bamboo_tree)1 1.01175573 1.8139321\n```\n:::\n:::\n\n\nCase - bednet + banana_tree\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-45_8e4a6fc5abc25df4f555ff26f6b98f64'}\n\n````{.cell-code .numberLines}\n```{{r}}\nML6 <- glm(factor(case) ~ factor(bednet) + factor(banana_tree), family=binomial, data=VL_Bihar)\nexp(coef(ML6))\nexp(confint(ML6))\n```\n````\n\n::: {.cell-output .cell-output-stderr}\n```\nWaiting for profiling to be done...\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n         (Intercept)      factor(bednet)1 factor(banana_tree)1 \n           0.1481994            0.4736328            0.9261514 \n                         2.5 %    97.5 %\n(Intercept)          0.1025907 0.2077231\nfactor(bednet)1      0.2948139 0.7271530\nfactor(banana_tree)1 0.6381431 1.3772929\n```\n:::\n:::\n\n\nCase - bednet + rice_field\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-46_ade1cc1b3bf7572bed3d0b5b05774c41'}\n\n````{.cell-code .numberLines}\n```{{r}}\nML7 <- glm(factor(case) ~ factor(bednet) + factor(rice_field), family=binomial, data=VL_Bihar)\nexp(coef(ML7))\nexp(confint(ML7))\n```\n````\n\n::: {.cell-output .cell-output-stderr}\n```\nWaiting for profiling to be done...\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n        (Intercept)     factor(bednet)1 factor(rice_field)1 \n          0.1144057           0.4800229           1.2666583 \n                         2.5 %    97.5 %\n(Intercept)         0.07841589 0.1615314\nfactor(bednet)1     0.29863762 0.7374461\nfactor(rice_field)1 0.86999235 1.8945309\n```\n:::\n:::\n\n\nCase - bednet + permanent_water_body\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-47_72721c836be87325613822dce14eeeb7'}\n\n````{.cell-code .numberLines}\n```{{r}}\nML8 <- glm(factor(case) ~ factor(bednet) + factor(permanent_water_body), family=binomial, data=VL_Bihar)\nexp(coef(ML8))\nexp(confint(ML8))\n```\n````\n\n::: {.cell-output .cell-output-stderr}\n```\nWaiting for profiling to be done...\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n                  (Intercept)               factor(bednet)1 \n                    0.1386849                     0.4723452 \nfactor(permanent_water_body)1 \n                    1.0062094 \n                                  2.5 %    97.5 %\n(Intercept)                   0.1125509 0.1691994\nfactor(bednet)1               0.2939865 0.7252469\nfactor(permanent_water_body)1 0.7516130 1.3449976\n```\n:::\n:::\n\n\nCase - bednet + granaries_in_hh\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-48_8b9087be6f2548ee92b390892b3728fc'}\n\n````{.cell-code .numberLines}\n```{{r}}\nML9 <- glm(factor(case) ~ factor(bednet) + factor(granaries_in_hh), family=binomial, data=VL_Bihar)\nexp(coef(ML9))\nexp(confint(ML9))\n```\n````\n\n::: {.cell-output .cell-output-stderr}\n```\nWaiting for profiling to be done...\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n             (Intercept)          factor(bednet)1 factor(granaries_in_hh)1 \n               0.1385799                0.4724105                1.0063584 \n                             2.5 %    97.5 %\n(Intercept)              0.1097963 0.1727742\nfactor(bednet)1          0.2940746 0.7252060\nfactor(granaries_in_hh)1 0.7519452 1.3510593\n```\n:::\n:::\n\n\nCase - bednet + owngoat\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-49_cd2fee3c81270bbd8e20619df786a601'}\n\n````{.cell-code .numberLines}\n```{{r}}\nML10 <- glm(factor(case) ~ factor(bednet) + factor(owngoat), family=binomial, data=VL_Bihar)\nexp(coef(ML10))\nexp(confint(ML10))\n```\n````\n\n::: {.cell-output .cell-output-stderr}\n```\nWaiting for profiling to be done...\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n     (Intercept)  factor(bednet)1 factor(owngoat)1 \n       0.1348600        0.4785828        1.0907549 \n                     2.5 %    97.5 %\n(Intercept)      0.1110257 0.1623881\nfactor(bednet)1  0.2973262 0.7365004\nfactor(owngoat)1 0.7996930 1.4770939\n```\n:::\n:::\n\n\nCase - bednet + ownpoul\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-50_7b088a3f55b31cf40f38a011baf3949c'}\n\n````{.cell-code .numberLines}\n```{{r}}\nML11 <- glm(factor(case) ~ factor(bednet) + factor(ownpoul), family=binomial, data=VL_Bihar)\nexp(coef(ML11))\nexp(confint(ML11))\n```\n````\n\n::: {.cell-output .cell-output-stderr}\n```\nWaiting for profiling to be done...\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n     (Intercept)  factor(bednet)1 factor(ownpoul)1 \n       0.1359797        0.4769139        1.5118321 \n                     2.5 %    97.5 %\n(Intercept)      0.1156162 0.1589157\nfactor(bednet)1  0.2968099 0.7323453\nfactor(ownpoul)1 0.7844602 2.7032767\n```\n:::\n:::\n\n\nCase - bednet + ownbov\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-51_47b62d54c611b544ee063b6b24142e31'}\n\n````{.cell-code .numberLines}\n```{{r}}\nML12 <- glm(factor(case) ~ factor(bednet) + factor(ownbov), family=binomial, data=VL_Bihar)\nexp(coef(ML12))\nexp(confint(ML12))\n```\n````\n\n::: {.cell-output .cell-output-stderr}\n```\nWaiting for profiling to be done...\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n    (Intercept) factor(bednet)1 factor(ownbov)1 \n      0.1344998       0.4674983       1.0953236 \n                    2.5 %    97.5 %\n(Intercept)     0.1106581 0.1620431\nfactor(bednet)1 0.2906619 0.7186983\nfactor(ownbov)1 0.8108404 1.4725822\n```\n:::\n:::\n\n\nCase - bednet + asset_index\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-52_90cc59d3fea79d21c3e5bee86176f174'}\n\n````{.cell-code .numberLines}\n```{{r}}\nML13 <- glm(factor(case) ~ factor(bednet) + factor(asset_index), family=binomial, data=VL_Bihar)\nsummary(ML13)\nexp(coef(ML13))\nexp(confint(ML13))\n```\n````\n\n::: {.cell-output .cell-output-stderr}\n```\nWaiting for profiling to be done...\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = factor(case) ~ factor(bednet) + factor(asset_index), \n    family = binomial, data = VL_Bihar)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-0.5955  -0.5941  -0.4723  -0.3225   2.5833  \n\nCoefficients:\n                     Estimate Std. Error z value Pr(>|z|)    \n(Intercept)          -1.64489    0.13006 -12.647  < 2e-16 ***\nfactor(bednet)1      -0.37012    0.24058  -1.538 0.123934    \nfactor(asset_index)2  0.00511    0.19228   0.027 0.978800    \nfactor(asset_index)3 -0.49232    0.22509  -2.187 0.028725 *  \nfactor(asset_index)4 -0.79317    0.23566  -3.366 0.000763 ***\nfactor(asset_index)5 -1.28561    0.30390  -4.230 2.33e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1303.7  on 1879  degrees of freedom\nResidual deviance: 1258.3  on 1874  degrees of freedom\nAIC: 1270.3\n\nNumber of Fisher Scoring iterations: 5\n\n         (Intercept)      factor(bednet)1 factor(asset_index)2 \n           0.1930338            0.6906510            1.0051226 \nfactor(asset_index)3 factor(asset_index)4 factor(asset_index)5 \n           0.6112062            0.4524071            0.2764830 \n                         2.5 %    97.5 %\n(Intercept)          0.1484556 0.2473784\nfactor(bednet)1      0.4214821 1.0867165\nfactor(asset_index)2 0.6880463 1.4639808\nfactor(asset_index)3 0.3891080 0.9427867\nfactor(asset_index)4 0.2813302 0.7108052\nfactor(asset_index)5 0.1472895 0.4884626\n```\n:::\n:::\n\n\nCase - bednet + riskwall\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-53_8b34a019d27b621dff6fda6be9ca7a42'}\n\n````{.cell-code .numberLines}\n```{{r}}\nML14 <- glm(factor(case) ~ factor(bednet) + factor(riskwall), family=binomial, data=VL_Bihar)\nexp(coef(ML14))\nexp(confint(ML14))\n```\n````\n\n::: {.cell-output .cell-output-stderr}\n```\nWaiting for profiling to be done...\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n      (Intercept)   factor(bednet)1 factor(riskwall)1 \n        0.1011328         0.5528385         1.8463805 \n                       2.5 %    97.5 %\n(Intercept)       0.07972857 0.1265816\nfactor(bednet)1   0.34181591 0.8561327\nfactor(riskwall)1 1.37410587 2.4884630\n```\n:::\n:::\n\n\nCase - bednet + earthfloor\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-54_fe645a281e6e0de6ccb32457a872131d'}\n\n````{.cell-code .numberLines}\n```{{r}}\nML15 <- glm(factor(case) ~ factor(bednet) + factor(earthfloor), family=binomial, data=VL_Bihar)\nexp(coef(ML15))\nexp(confint(ML15))\n```\n````\n\n::: {.cell-output .cell-output-stderr}\n```\nWaiting for profiling to be done...\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n        (Intercept)     factor(bednet)1 factor(earthfloor)1 \n         0.04606946          0.52529186          3.16935398 \n                         2.5 %     97.5 %\n(Intercept)         0.01793912 0.09657055\nfactor(bednet)1     0.32593161 0.80963385\nfactor(earthfloor)1 1.49945482 8.17768200\n```\n:::\n:::\n\n\nCase - bednet + sc_caste\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-55_0bccbde90e134718447ec659af552096'}\n\n````{.cell-code .numberLines}\n```{{r}}\nML16 <- glm(factor(case) ~ factor(bednet) + factor(sc_caste), family=binomial, data=VL_Bihar)\nexp(coef(ML16))\nexp(confint(ML16))\n```\n````\n\n::: {.cell-output .cell-output-stderr}\n```\nWaiting for profiling to be done...\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n      (Intercept)   factor(bednet)1 factor(sc_caste)1 \n        0.1186469         0.5475738         6.7960195 \n                       2.5 %     97.5 %\n(Intercept)       0.09993218  0.1398283\nfactor(bednet)1   0.33945784  0.8451291\nfactor(sc_caste)1 4.12689597 11.1198834\n```\n:::\n:::\n\n\nTable of how much change the OR\n\n| Factor   | Co factor             | OR       | 95IC                  | Change-in-estimate |\n|---------------|---------------|---------------|---------------|---------------|\n| Bed nets |                       | 0.4725   | 0.2941532 0.7252757   | Ref                |\n| Bed nets | factor(sex)           | 0.47374  | 0.2948994 0.7272629   | -0.3%              |\n| Bed nets | age                   | 0.496305 | 0.3083839 0.7636801   | -5.0%              |\n| Bed nets | group age             | 0.49619  | 0.3082705 0.7636340   | -5.0%              |\n| Bed nets | under5                | 0.482438 | 0.3000965 0.7413054   | -2.1%              |\n| Bed nets | factor(neem_tree), f  | 0.474045 | 0.2950723 0.7277817   | -0.3%              |\n| Bed nets | factor(bamboo_tree),  | 0.483379 | 0.30071367 0.7426603  | -2.3%              |\n| Bed nets | factor(banana_tree),  | 0.473633 | 0.2948139 0.7271530   | -0.2%              |\n| Bed nets | factor(rice_field),   | 0.480023 | 0.29863762 0.7374461  | -1.6%              |\n| Bed nets | factor(permanent_wat  | 0.472345 | 0.2939865 0.7252469   | 0.0%               |\n| Bed nets | factor(granaries_in\\_ | 0.472411 | 0.2940746 0.7252060   | 0.0%               |\n| Bed nets | factor(owngoat),      | 0.478583 | 0.2973262 0.7365004   | -1.3%              |\n| Bed nets | factor(ownpoul),      | 0.476914 | 0.2968099 0.7323453   | -0.9%              |\n| Bed nets | factor(ownbov),       | 0.467498 | 0.2906619 0.7186983   | 1.1%               |\n| Bed nets | factor(asset_index)   | 0.690651 | 0.4214821 1.0867165   | -46.2%             |\n| Bed nets | factor(riskwall), f   | 0.552839 | 0.34181591 0.8561327  | -17.0%             |\n| Bed nets | factor(earthfloor),   | 0.525292 | 0.32593161 0.80963385 | -11.2%             |\n| Bed nets | factor(sc_caste), f   | 0.547574 | 0.33945784 0.8451291  | -15.9%             |\n\n::: callout-note\nSo far we know that assess index, riskwall, earthfloor and sccastle have more than 10% of change in the OR of bednet\n\n        Assess index : change of 46.2%\n        Riskwall : change of 17%\n        earthfloor: 11.2%\n        sccastle : 15.9 ( Castle is similar to assess index, so we won´t take in to account)\n:::\n\nSo the model so far is:\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-56_a4dc5fc94cee623a897a92c2756aa488'}\n\n```{.r .cell-code .numberLines}\nML17 <- glm(factor(case) ~ factor(bednet) + factor(asset_index) + factor(riskwall) + factor(earthfloor) , family=binomial, data=VL_Bihar)\n```\n:::\n\n\nStep 4: We are going to exclude factors removing one by one (starting with the one with less change: earthfloor)\n\nWe will star removing earthfloor:\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-57_685206b1364fd5b86c1d3a04211ff0ce'}\n\n````{.cell-code .numberLines}\n```{{r}}\nML18 <- glm(factor(case) ~ factor(bednet) + factor(asset_index) + factor(riskwall) , family=binomial, data=VL_Bihar)\nsummary(ML18)\nexp(coef(ML18))\nexp(confint(ML18))\n```\n````\n\n::: {.cell-output .cell-output-stderr}\n```\nWaiting for profiling to be done...\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = factor(case) ~ factor(bednet) + factor(asset_index) + \n    factor(riskwall), family = binomial, data = VL_Bihar)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-0.6197  -0.5569  -0.4514  -0.3220   2.5816  \n\nCoefficients:\n                     Estimate Std. Error z value Pr(>|z|)    \n(Intercept)          -1.82815    0.19068  -9.588  < 2e-16 ***\nfactor(bednet)1      -0.36266    0.24083  -1.506 0.132088    \nfactor(asset_index)2  0.04281    0.19434   0.220 0.825645    \nfactor(asset_index)3 -0.40452    0.23418  -1.727 0.084100 .  \nfactor(asset_index)4 -0.66343    0.25476  -2.604 0.009212 ** \nfactor(asset_index)5 -1.10510    0.33366  -3.312 0.000926 ***\nfactor(riskwall)1     0.23261    0.17392   1.337 0.181078    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1303.7  on 1879  degrees of freedom\nResidual deviance: 1256.5  on 1873  degrees of freedom\nAIC: 1270.5\n\nNumber of Fisher Scoring iterations: 5\n\n         (Intercept)      factor(bednet)1 factor(asset_index)2 \n           0.1607100            0.6958205            1.0437402 \nfactor(asset_index)3 factor(asset_index)4 factor(asset_index)5 \n           0.6672951            0.5150839            0.3311786 \n   factor(riskwall)1 \n           1.2618946 \n                         2.5 %    97.5 %\n(Intercept)          0.1096759 0.2317313\nfactor(bednet)1      0.4244549 1.0954504\nfactor(asset_index)2 0.7116732 1.5265074\nfactor(asset_index)3 0.4176057 1.0483734\nfactor(asset_index)4 0.3091537 0.8414938\nfactor(asset_index)5 0.1675919 0.6242947\nfactor(riskwall)1    0.8990299 1.7791027\n```\n:::\n:::\n\n\nAnd then comparing both models (ML17 vs ML18)\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-58_03aaae445ee6feb9d26d6cc7909a42b1'}\n\n```{.r .cell-code .numberLines}\nanova(ML17, ML18, test=\"Chisq\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAnalysis of Deviance Table\n\nModel 1: factor(case) ~ factor(bednet) + factor(asset_index) + factor(riskwall) + \n    factor(earthfloor)\nModel 2: factor(case) ~ factor(bednet) + factor(asset_index) + factor(riskwall)\n  Resid. Df Resid. Dev Df Deviance Pr(>Chi)\n1      1872     1254.1                     \n2      1873     1256.5 -1  -2.4739   0.1157\n```\n:::\n:::\n\n\n::: callout-note\nBecause the Likelihood ratio test was not significant (p = 0.1157) there is not significant difference between LM17 an ML18, so we keep the simplest model ML18: factor(case) - factor(bednet) + factor(asset_index) + factor(riskwall)\n:::\n\nNow we will try to remove other factor (riskwall)\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-59_34d34339e5b86c6f07b491f648e3607a'}\n\n```{.r .cell-code .numberLines}\n  ML19 <- glm(factor(case) ~ factor(bednet) + factor(asset_index) , family=binomial, data=VL_Bihar)\n```\n:::\n\n\nAnd then comparing both (ML18 vs ML19)\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-60_27db6033a3f93d1688a374256d9b7204'}\n\n```{.r .cell-code .numberLines}\nanova(ML18, ML19, test=\"Chisq\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAnalysis of Deviance Table\n\nModel 1: factor(case) ~ factor(bednet) + factor(asset_index) + factor(riskwall)\nModel 2: factor(case) ~ factor(bednet) + factor(asset_index)\n  Resid. Df Resid. Dev Df Deviance Pr(>Chi)\n1      1873     1256.5                     \n2      1874     1258.3 -1  -1.8029   0.1794\n```\n:::\n:::\n\n\n::: callout-note\nBecause the Likelihood ratio test was not significant (p = 0.1794) there is not significant difference between LM18 an ML19, so we keep the simplest model LM19: factor(case) - factor(bednet) + factor(asset_index)\n:::\n\nNow we will try to remove the other factor (assest_index)\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-61_11649281cd1bf2d177e1292c4f6be7a4'}\n\n```{.r .cell-code .numberLines}\nML20 <- glm(factor(case) ~ factor(bednet) , family=binomial, data=VL_Bihar)\n```\n:::\n\n\nAnd then comparing both (ML19 vs ML20)\n\n\n::: {.cell hash='2023-02-09-CaseAssigment_cache/html/unnamed-chunk-62_6a2e98660927f624067461a9b1139182'}\n\n```{.r .cell-code .numberLines}\nanova(ML19, ML20, test=\"Chisq\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAnalysis of Deviance Table\n\nModel 1: factor(case) ~ factor(bednet) + factor(asset_index)\nModel 2: factor(case) ~ factor(bednet)\n  Resid. Df Resid. Dev Df Deviance  Pr(>Chi)    \n1      1874     1258.3                          \n2      1878     1291.2 -4  -32.812 1.305e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\n::: callout-note\nBecause the Likelihood ratio test was significant (1.305e-06 ) there is a significant difference between LM18 an ML19, so we keep the complex model: factor(case) - factor(bednet) + factor(asset_index)\n\nSo the final model should include: Bednet and asset_index\n\nNow the question is if those factors are ok like that or there is an interaction between them?\n:::\n\nStep 5: Analyzing the interaction\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}