{
  "hash": "6e5ca46be62fc88df94b090b5135e615",
  "result": {
    "markdown": "---\ntitle: \"2023-02-03 Sessión 4\"\nformat: \n  html:\n    self-contained: true\n---\n\n\n-   Instituut Voor Tropische Geneeskunde - Antwerp, Belgium\n-   Javier Silva-Valencia\n\n## Step by Step - Selection of variables for modeling\n\n##### Import data\n\nImporting a CSV database under the name of \"sandfly\", with \",\" as separator:\n\n\n::: {.cell hash='2023-02-03-Linear-Regresion,-Sessión-4_cache/html/unnamed-chunk-1_a8f0bcba63fb6cedb4bace226cdbfe54'}\n\n```{.r .cell-code .numberLines}\nsandfly <- read.csv(\"C:/Users/pined/OneDrive - Universidad Nacional Mayor de San Marcos/Javier 2022/Belgica/AC2/Linear Regresion Exercise Database/Datasets/sandfly.csv\", sep=\",\")\n```\n:::\n\n\n------------------------------------------------------------------------\n\n------------------------------------------------------------------------\n\n##### Spoiler alert\n\n::: callout-note\nWhat we are going to do today is a multivariate linear regression and selecting the variables that will be included in this regression with the \"Classical model selection\"\n\nSo, so far we know that the steps to the \"Classical model selection\" are:\n\n| ***Steps***                                                                                                                                                                                                                                                  | ***Example***                                                                                                                                                                                                                                                                                                                                         |\n|------------------------------------|------------------------------------|\n|                                                                                                                                                                                                                                                              | *Imagine that you have 6 independent variables and 1 dependent variable. And you want to create a linear regression.*                                                                                                                                                                                                                                 |\n| *1. Do a simple linear regression (bivariate) which each independent variable*                                                                                                                                                                               | So we will have 6 models                                                                                                                                                                                                                                                                                                                              |\n| *2. Note the models with a p-value less than 0.10. Those are the variables we are going to start working with. Exclude the others*                                                                                                                           | Imagine that only 4 models had a p-value less than 0.10. So we keep those independent variables                                                                                                                                                                                                                                                       |\n| *3. Now create a multivariate linear regression model with all the remaining variables*                                                                                                                                                                      | So we will create 01 model with the 4 remaining independent variables. (multivariate model 1)                                                                                                                                                                                                                                                         |\n| *4. Check in the results if any on the variables have a p-value higher than 0.05. If yes, exclude the one with the highest value and create a new model with the remaining variables. Repeat until all variables has a significant p-value (less than 0.05)* | Imagine that in the results we see that two variables had a p-value bigger than 0.05. We exclude the highest and create a (multivariate model 2). In the new results we still see that one variable had a p-value bigger than 0.05. So we exclude it and create a (multivariate model 3). In the new results all variables has a significant p value. |\n| *Now you have the variables that, no matter what happens, they have to be in your model. But, are they ok in that way? or it would be better to put them as interaction?*                                                                                    | The remaining model (multivariate model 3) only includes 2 independent variables: lm(DependVariabl\\~ IndepVariab1 + IndependVariable2                                                                                                                                                                                                                 |\n| *5. Create another model(s) with the remaining variables but as an interaction*                                                                                                                                                                              | So, we create another model (multivariate model 4) but as an interaction lm(DependVariabl\\~ IndepVariab1 \\* IndependVariable2                                                                                                                                                                                                                         |\n| *6. Check if the model(s) with interaction is significantly better than the one without interaction. For this perform an F test (anova table)*                                                                                                               | We will compare the (multivariate model 3) vs the (multivariate model 4) in an anova table.                                                                                                                                                                                                                                                           |\n| *7. If the results show that no model is better than the other, we keep the model more simple (the one without interaction). Otherwise, we keep the model with interaction*                                                                                  | Imagine that the p-value of the ANOVA table is not significant (less than 0.05). This means that no model is better than the other. So we keep the more simple model (the one without interaction)                                                                                                                                                    |\n|                                                                                                                                                                                                                                                              | So in this case the final model would be the (multivariate model 3)                                                                                                                                                                                                                                                                                   |\n:::\n\n------------------------------------------------------------------------\n\n------------------------------------------------------------------------\n\n### Starting the Exercise (Ex05-2023):\n\n<sub> In Bihar, India, visceral Leishmaniasis or Kala Azar is transmitted by the phlebotomine sand fly p.argentipes. The disease is known to disproportionally affect the poorest segments of society, this could be due to increased exposure to sand flies as a result of poor housing and environmental conditions. To assess the independent contributions of different factors, a study team conducted an entomological survey and collected information on housing and environmental conditions as well as on assets owned. Five hundred houses from a rural block were randomly sampled and light traps were installed simultaneously for a total of 6 nights in each house. Per house the total number of p. argentipes sand flies captured was determined. The data can be found in sandfly.csv. </sub>\n\n###### 1. The outcome variable is tot_parg (total numbers of p.argentipes sandflyes captured per house) Is tot_parg normally distributed?\n\n\n::: {.cell hash='2023-02-03-Linear-Regresion,-Sessión-4_cache/html/unnamed-chunk-2_d10a0095f2a23f2e04c336ab72e14a97'}\n\n```{.r .cell-code .numberLines}\nhist(sandfly$tot_parg,main=\"Total number of p.argentipes sandflies captured in a house distribution\", \n     xlab=\"Total number of p.argentipes sandflies captured\", ylab=\"nb\", col=\"green\", border=\"dark green\")\n```\n\n::: {.cell-output-display}\n![](2023-02-03-Linear-Regresion,-Sessión-4_files/figure-html/unnamed-chunk-2-1.png){width=70%}\n:::\n:::\n\n\n::: callout-note\nIt is not normally distributed\n:::\n\n###### 2. Generate a new variable \"log_parg\" which is the natural logarithm of tot_parg. Is normally distributed?\n\n\n::: {.cell hash='2023-02-03-Linear-Regresion,-Sessión-4_cache/html/unnamed-chunk-3_f11ff34cbab286a7d207262c3a10c58d'}\n\n```{.r .cell-code .numberLines}\nsandfly$log_parg <- log(sandfly$tot_parg)    #Creating the natural logarith variable\n```\n:::\n\n::: {.cell hash='2023-02-03-Linear-Regresion,-Sessión-4_cache/html/unnamed-chunk-4_6509fd9ac7624924277c83449c86ec31'}\n\n```{.r .cell-code .numberLines}\nhist(sandfly$log_parg,main=\"Log of p.argentipes sandflies captured in a house distribution\", \n     xlab=\"Log of p.argentipes sandflies captured\", ylab=\"nb\", col=\"green\", border=\"dark green\")\n```\n\n::: {.cell-output-display}\n![](2023-02-03-Linear-Regresion,-Sessión-4_files/figure-html/unnamed-chunk-4-1.png){width=70%}\n:::\n:::\n\n\n::: callout-note\nIt seems normally distributed\n:::\n\n###### 3. Explored in simple linear regression whether each of the independent variables is associated with log_parg. Make a table listing each factor, the number and proportion of households in which it is present\n\n<sub> This is the Classical model selection. So, we need bivariate regressions for each independent variable with log_parg </sub>\n\n3.1 Animals\n\n\n::: {.cell hash='2023-02-03-Linear-Regresion,-Sessión-4_cache/html/unnamed-chunk-5_c5ad7970c1593960c8269b22d220a372'}\n\n```{.r .cell-code .numberLines}\n  sandfly$animals <- factor(sandfly$animals)      #Factor because is a categorical variable\n  #table (sandfly$animals, useNA=\"always\")         #To explore the frequency and missing values\n  lm1 = lm(log_parg ~ animals, data = sandfly)    #Simple linear regression (bivariate)\n  summary(lm1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = log_parg ~ animals, data = sandfly)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.1944 -0.7965 -0.0164  0.7226  3.3292 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  3.19440    0.05053  63.218  < 2e-16 ***\nanimals1     0.81025    0.25265   3.207  0.00143 ** \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.107 on 498 degrees of freedom\nMultiple R-squared:  0.02023,\tAdjusted R-squared:  0.01827 \nF-statistic: 10.29 on 1 and 498 DF,  p-value: 0.001427\n```\n:::\n:::\n\n\n3.2 Stove\n\n\n::: {.cell hash='2023-02-03-Linear-Regresion,-Sessión-4_cache/html/unnamed-chunk-6_49d9e878bd1afd24fb314a5b6cc71caf'}\n\n```{.r .cell-code .numberLines}\n  sandfly$stove <- factor(sandfly$stove)        #Factor because is a categorical variable\n  #table (sandfly$stove, useNA=\"always\")         #To explore the frequency and missing values\n  lm2 = lm(log_parg ~ stove, data = sandfly)    #Simple linear regression (bivariate)\n  summary(lm2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = log_parg ~ stove, data = sandfly)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.4602 -0.8197 -0.0395  0.7336  3.3060 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  3.21760    0.05095  63.150   <2e-16 ***\nstove1       0.24261    0.26138   0.928    0.354    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.117 on 498 degrees of freedom\nMultiple R-squared:  0.001727,\tAdjusted R-squared:  -0.0002775 \nF-statistic: 0.8615 on 1 and 498 DF,  p-value: 0.3538\n```\n:::\n:::\n\n\n3.3 Ventilation\n\n\n::: {.cell hash='2023-02-03-Linear-Regresion,-Sessión-4_cache/html/unnamed-chunk-7_9303100d1545a37cbc6f5632c0b0dbe6'}\n\n```{.r .cell-code .numberLines}\n  sandfly$ventilation <- factor(sandfly$ventilation)    #Factor because is a categorical variable\n  #table (sandfly$ventilation, useNA=\"always\")           #To explore the frequency and missing values\n  lm3 = lm(log_parg ~ ventilation, data = sandfly)      #Simple linear regression (bivariate)\n  summary(lm3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = log_parg ~ ventilation, data = sandfly)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.3918 -0.6837 -0.0740  0.7756  3.1318 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   3.39179    0.06271  54.084  < 2e-16 ***\nventilation1 -0.42741    0.10094  -4.234 2.73e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.099 on 498 degrees of freedom\nMultiple R-squared:  0.03475,\tAdjusted R-squared:  0.03281 \nF-statistic: 17.93 on 1 and 498 DF,  p-value: 2.731e-05\n```\n:::\n:::\n\n\n3.4 Light\n\n\n::: {.cell hash='2023-02-03-Linear-Regresion,-Sessión-4_cache/html/unnamed-chunk-8_1e8cdb5eba68526041f2d4d1c70ae405'}\n\n```{.r .cell-code .numberLines}\n  sandfly$light <- factor(sandfly$light)          #Factor because is a categorical variable\n  #table (sandfly$light, useNA=\"always\")           #To explore the frequency and missing values\n  lm4 = lm(log_parg ~ light, data = sandfly)      #Simple linear regression (bivariate)\n  summary(lm4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = log_parg ~ light, data = sandfly)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.2306 -0.8216 -0.0118  0.7425  3.2929 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  3.23063    0.06166  52.394   <2e-16 ***\nlight1      -0.01115    0.10544  -0.106    0.916    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.118 on 498 degrees of freedom\nMultiple R-squared:  2.244e-05,\tAdjusted R-squared:  -0.001986 \nF-statistic: 0.01118 on 1 and 498 DF,  p-value: 0.9158\n```\n:::\n:::\n\n\n3.5 Cowdung\n\n\n::: {.cell hash='2023-02-03-Linear-Regresion,-Sessión-4_cache/html/unnamed-chunk-9_cff95ba417a374c50ded550ba45a8122'}\n\n```{.r .cell-code .numberLines}\n  sandfly$cowdung <- factor(sandfly$cowdung)        #Factor because is a categorical variable\n  #table (sandfly$cowdung, useNA=\"always\")           #To explore the frequency and missing values\n  lm5 = lm(log_parg ~ cowdung, data = sandfly)      #Simple linear regression (bivariate)\n  summary(lm5)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = log_parg ~ cowdung, data = sandfly)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.2419 -0.7570 -0.0230  0.7284  3.2817 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   2.7388     0.2879   9.512   <2e-16 ***\ncowdung1      0.5031     0.2923   1.721   0.0859 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.115 on 498 degrees of freedom\nMultiple R-squared:  0.005912,\tAdjusted R-squared:  0.003916 \nF-statistic: 2.962 on 1 and 498 DF,  p-value: 0.08588\n```\n:::\n:::\n\n\n3.6 Water\n\n\n::: {.cell hash='2023-02-03-Linear-Regresion,-Sessión-4_cache/html/unnamed-chunk-10_ea18044b4ba8b1760605a1323877800b'}\n\n```{.r .cell-code .numberLines}\n  sandfly$water <- factor(sandfly$water)         #Factor because is a categorical variable\n  #table (sandfly$water, useNA=\"always\")          #To explore the frequency and missing values\n  lm6 = lm(log_parg ~ water, data = sandfly)     #Simple linear regression (bivariate)\n  summary(lm6)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = log_parg ~ water, data = sandfly)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.3342 -0.8027 -0.0305  0.7452  3.3229 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  3.20064    0.05572  57.443   <2e-16 ***\nwater1       0.13354    0.12586   1.061    0.289    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.117 on 498 degrees of freedom\nMultiple R-squared:  0.002256,\tAdjusted R-squared:  0.0002522 \nF-statistic: 1.126 on 1 and 498 DF,  p-value: 0.2892\n```\n:::\n:::\n\n\n3.7 Asset_index\n\n\n::: {.cell hash='2023-02-03-Linear-Regresion,-Sessión-4_cache/html/unnamed-chunk-11_ff208131e1716196d140c2d2cf3c8602'}\n\n```{.r .cell-code .numberLines}\n  sandfly$asset_index <- factor(sandfly$asset_index)   #Factor because is a categorical variable}\n  #we don't need to relevel\n  #table (sandfly$asset_index, useNA=\"always\")          #To explore the frequency and missing values\n  lm7 = lm(log_parg ~ asset_index, data = sandfly)     #Simple linear regression (bivariate)\n  summary(lm7)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = log_parg ~ asset_index, data = sandfly)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.5065 -0.7242  0.0206  0.7371  3.2189 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   3.50646    0.10664  32.882  < 2e-16 ***\nasset_index2  0.03697    0.16667   0.222   0.8245    \nasset_index3 -0.33546    0.15196  -2.208   0.0278 *  \nasset_index4 -0.30015    0.15276  -1.965   0.0500 .  \nasset_index5 -0.70187    0.14556  -4.822 1.92e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.072 on 477 degrees of freedom\n  (18 observations deleted due to missingness)\nMultiple R-squared:  0.06171,\tAdjusted R-squared:  0.05384 \nF-statistic: 7.843 on 4 and 477 DF,  p-value: 3.968e-06\n```\n:::\n:::\n\n\n3.8 House_type\n\n\n::: {.cell hash='2023-02-03-Linear-Regresion,-Sessión-4_cache/html/unnamed-chunk-12_ee1fb679159174a0213f339417877b91'}\n\n```{.r .cell-code .numberLines}\n  #Already a character (categorical) variable no need to factor\n  #table(sandfly$house_type, useNA=\"always\")             #To explore the frequency and missing values\n  lm8 = lm(log_parg ~ house_type, data = sandfly)       #Simple linear regression (bivariate)\n  summary(lm8)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = log_parg ~ house_type, data = sandfly)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.1259 -0.6913 -0.0121  0.6752  3.2067 \n\nCoefficients:\n                        Estimate Std. Error t value Pr(>|t|)    \n(Intercept)              2.88012    0.12215  23.578  < 2e-16 ***\nhouse_typepbrick_efloor  0.02238    0.15798   0.142    0.887    \nhouse_typethatched       0.83198    0.14821   5.614  3.3e-08 ***\nhouse_typeupbrick        0.24579    0.14994   1.639    0.102    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.065 on 496 degrees of freedom\nMultiple R-squared:  0.09706,\tAdjusted R-squared:  0.0916 \nF-statistic: 17.77 on 3 and 496 DF,  p-value: 5.686e-11\n```\n:::\n:::\n\n\n3.9 Completing the requested table and checking witch models has a p value higher than 0.10\n\n<sub> We do this checking all the results above </sub>\n\n::: callout-note\n| Factor                               | Number (%) | Coefficient | p-value                   |\n|-----------------------|-----------------|-----------------|-----------------|\n| Animals in the house                 | 20 (4.0)   | 0.81        | 0.001                     |\n| Traditional stove                    | 19 (3.8)   | 0.24        | [0.35]{style=\"color:red\"} |\n| Ventilation                          | 193 (38.6) | -0.43       | \\<0.001                   |\n| Adequate light                       | 171 (34.2) | -0.01       | [0.92]{style=\"color:red\"} |\n| Cow dung                             | 485 (97.0) | 0.50        | 0.09                      |\n| Water body                           | 98 (19.6)  | 0.13        | [0.29]{style=\"color:red\"} |\n| Asset index\\*                        |            |             |                           |\n| -----1 (poorest)                     | 101 (21.0) | ref         | ref                       |\n| -----2                               | 70 (14.5)  | 0.04        | 0.82                      |\n| -----3                               | 98 (20.3)  | -0.34       | 0.03                      |\n| -----4                               | 96 (19.9)  | -0.30       | 0.05                      |\n| -----5 (wealthiest)                  | 117 (24.3) | -0.70       | \\<0.001                   |\n| -----Missing                         | 18         |             |                           |\n| House type                           |            |             |                           |\n| -----Plastered brick, cemented floor | 76 (15.2)  | ref         | ref                       |\n| -----Thatched                        | 161 (32.2) | 0.83        | \\<0.001                   |\n| -----Unplastered brick               | 150 (30.0) | 0.25        | 0.10                      |\n| -----Plastered brick, earth floor    | 113 (22.6) | 0.02        | 0.89                      |\n:::\n\n::: callout-note\nThere are 3 models that have a p value higher than 0.10 (the ones in red) Those variables are not going to enter to the final model\n:::\n\n###### 4. Construct a multiple linear regresion with all variables that were significant. Which variables will you include?\n\n<sub> We will incude those who obtained a p value less than 0.10: animals, ventilation, cowdung, asset index and house_type. The regresion model is: </sub>\n\n\n::: {.cell hash='2023-02-03-Linear-Regresion,-Sessión-4_cache/html/unnamed-chunk-13_7ef16bac7b950de9d108010fe9cd2d17'}\n\n```{.r .cell-code .numberLines}\nlm9 = lm(log_parg ~ animals + ventilation + cowdung + asset_index + house_type, data = sandfly)\nsummary(lm9)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = log_parg ~ animals + ventilation + cowdung + asset_index + \n    house_type, data = sandfly)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.2528 -0.6406 -0.0122  0.7067  3.2542 \n\nCoefficients:\n                        Estimate Std. Error t value Pr(>|t|)    \n(Intercept)              3.03255    0.31616   9.592  < 2e-16 ***\nanimals1                 0.54503    0.24444   2.230  0.02624 *  \nventilation1            -0.14492    0.10974  -1.321  0.18728    \ncowdung1                 0.17978    0.28358   0.634  0.52641    \nasset_index2             0.12385    0.16411   0.755  0.45082    \nasset_index3            -0.20495    0.14927  -1.373  0.17040    \nasset_index4            -0.13879    0.15207  -0.913  0.36187    \nasset_index5            -0.33856    0.16225  -2.087  0.03746 *  \nhouse_typepbrick_efloor -0.02115    0.16290  -0.130  0.89678    \nhouse_typethatched       0.51342    0.17465   2.940  0.00345 ** \nhouse_typeupbrick        0.04044    0.16383   0.247  0.80514    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.04 on 471 degrees of freedom\n  (18 observations deleted due to missingness)\nMultiple R-squared:  0.1274,\tAdjusted R-squared:  0.1089 \nF-statistic: 6.876 on 10 and 471 DF,  p-value: 4.592e-10\n```\n:::\n:::\n\n\n###### 5. Which is the weaksest factor (highest p-value) and how high is its p-value?\n\n::: callout-note\nCowndown (has the higher pvalue 0.52641)\n\nClarification: If we see the previous results, In fact the one with the highest p-value is one category of house_type (brick_efloor: 0.89678). But because there are other categories of the same variable that are significant (has p value less than 0.05), we cannot eliminate that variable.\n:::\n\n###### 6. Remove 'cowdung', which is now the weakest factor and what is its p-value?\n\n<sub> So the next model is: </sub>\n\n\n::: {.cell hash='2023-02-03-Linear-Regresion,-Sessión-4_cache/html/unnamed-chunk-14_ed1ef43d14ebe4da200fce902ad967f9'}\n\n```{.r .cell-code .numberLines}\nlm10 = lm(log_parg ~ animals + ventilation + asset_index + house_type, data = sandfly)\nsummary(lm10)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = log_parg ~ animals + ventilation + asset_index + \n    house_type, data = sandfly)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.2535 -0.6438 -0.0135  0.6956  3.2634 \n\nCoefficients:\n                         Estimate Std. Error t value Pr(>|t|)    \n(Intercept)              3.195702   0.183532  17.412  < 2e-16 ***\nanimals1                 0.539125   0.244108   2.209  0.02769 *  \nventilation1            -0.151368   0.109200  -1.386  0.16636    \nasset_index2             0.124507   0.163999   0.759  0.44812    \nasset_index3            -0.208963   0.149044  -1.402  0.16157    \nasset_index4            -0.135136   0.151862  -0.890  0.37399    \nasset_index5            -0.342134   0.162053  -2.111  0.03528 *  \nhouse_typepbrick_efloor -0.004478   0.160663  -0.028  0.97778    \nhouse_typethatched       0.530562   0.172439   3.077  0.00221 ** \nhouse_typeupbrick        0.057824   0.161416   0.358  0.72033    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.039 on 472 degrees of freedom\n  (18 observations deleted due to missingness)\nMultiple R-squared:  0.1266,\tAdjusted R-squared:   0.11 \nF-statistic: 7.605 on 9 and 472 DF,  p-value: 1.904e-10\n```\n:::\n:::\n\n\n::: callout-note\nVentilation (has now the higher pvalue 0.16636)\n\nClarification: If we see the previous results, in fact are others with a highest p-value (ej: asset_index2 or house_typepbrick_efloor). But because there are other categories of the same variable that are significant (has p value less than 0.05, we cannot eliminate that variable.\n:::\n\n###### 7. Remove 'ventilation'. Is there still another factor of which no category is significant at the 5% level ? Which factors do you keep in your final model?\n\n<sub> So the new model is: </sub>\n\n\n::: {.cell hash='2023-02-03-Linear-Regresion,-Sessión-4_cache/html/unnamed-chunk-15_ed493385434ee7330465773c84375835'}\n\n```{.r .cell-code .numberLines}\nlm11 = lm(log_parg ~ animals + asset_index + house_type, data = sandfly)\nsummary(lm11)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = log_parg ~ animals + asset_index + house_type, data = sandfly)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.2045 -0.6371 -0.0027  0.6814  3.2001 \n\nCoefficients:\n                         Estimate Std. Error t value Pr(>|t|)    \n(Intercept)              3.129930   0.177465  17.637  < 2e-16 ***\nanimals1                 0.505096   0.243107   2.078 0.038279 *  \nasset_index2             0.114276   0.163992   0.697 0.486246    \nasset_index3            -0.215243   0.149120  -1.443 0.149563    \nasset_index4            -0.137779   0.151997  -0.906 0.365156    \nasset_index5            -0.381083   0.159754  -2.385 0.017451 *  \nhouse_typepbrick_efloor -0.006961   0.160810  -0.043 0.965490    \nhouse_typethatched       0.586305   0.167848   3.493 0.000522 ***\nhouse_typeupbrick        0.074528   0.161122   0.463 0.643897    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.04 on 473 degrees of freedom\n  (18 observations deleted due to missingness)\nMultiple R-squared:  0.1231,\tAdjusted R-squared:  0.1083 \nF-statistic: 8.299 on 8 and 473 DF,  p-value: 1.493e-10\n```\n:::\n:::\n\n\n::: callout-note\nAll have at least one category with a p-value \\< 0.05, So there is not another factor no significant and I dont have to exclude another variable\n\nSo, This factors are the ones who are going to stay in the final model: House_type, asset_index and animals.\n:::\n\n###### 8. To test for interactions generate the following binary variables:\n\n<sub> - rich, 'yes' if asset_index = 5, 'no' if asset-index = 1-4 (beware of missing values!) </sub>\n\n<sub> - thatched, 'yes' if house_type = 'thatched, else 'no'</sub>\n\n<sub> Run the model with 'animals', 'rich' and 'thatched' as predictors, note down the equation. Are all three factors statistically significant? </sub>\n\n8.1 Creating the variable Rich\n\n\n::: {.cell hash='2023-02-03-Linear-Regresion,-Sessión-4_cache/html/unnamed-chunk-16_e7b45555955c6403b9c9c78723414216'}\n\n```{.r .cell-code .numberLines}\n#Variable Rich\n      #table(sandfly$asset_index, useNA = \"always\")\n      sandfly$rich <- ifelse(sandfly$asset_index==5,1,0)\n        table(sandfly$rich, useNA = \"always\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   0    1 <NA> \n 365  117   18 \n```\n:::\n:::\n\n\n8.2 Creating the variable thatched\n\n\n::: {.cell hash='2023-02-03-Linear-Regresion,-Sessión-4_cache/html/unnamed-chunk-17_c082f5b0abe5f692d3422cd0424795a0'}\n\n```{.r .cell-code .numberLines}\n#Variable thatched\n      #table(sandfly$house_type, useNA = \"always\")\n      sandfly$thatched <- ifelse(sandfly$house_type==\"thatched\",1,0)\n        table(sandfly$thatched, useNA = \"always\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   0    1 <NA> \n 339  161    0 \n```\n:::\n:::\n\n\n8.3 With this variables, the regresion model is:\n\n\n::: {.cell hash='2023-02-03-Linear-Regresion,-Sessión-4_cache/html/unnamed-chunk-18_1ec1c0e7c1018e52becc35ce3a02dcce'}\n\n```{.r .cell-code .numberLines}\n  mod12 <- lm(log_parg ~ animals+rich+thatched, data=sandfly)\n  summary(mod12)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = log_parg ~ animals + rich + thatched, data = sandfly)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.1078 -0.6820  0.0068  0.6770  3.2620 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  3.08869    0.06985  44.217  < 2e-16 ***\nanimals1     0.55419    0.24126   2.297  0.02205 *  \nrich        -0.32729    0.11664  -2.806  0.00522 ** \nthatched     0.56358    0.10836   5.201 2.95e-07 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.041 on 478 degrees of freedom\n  (18 observations deleted due to missingness)\nMultiple R-squared:  0.1128,\tAdjusted R-squared:  0.1072 \nF-statistic: 20.25 on 3 and 478 DF,  p-value: 2.277e-12\n```\n:::\n:::\n\n\n::: callout-note\nWe can see that all variables are still significant The equation of this model is: log_parg = 3.09 + 0.55\\* animals -- 0.33\\* rich + 0.56\\* thatched\n:::\n\n###### 9. Theoretically there could be interactions between rich and thatched, rich and animals and animals and thatched. Is any of these interaction terms statistically significant?\n\n<sub> Check for Possible interactions (pairs)</sub>\n\n<sub>mod13 \\<- lm(log_parg \\~ animals+rich\\*thatched, data=sandfly)</sub>\n\n<sub>mod14 \\<- lm(log_parg \\~ rich+thatched\\*animals, data=sandfly)</sub>\n\n<sub>mod15 \\<- lm(log_parg \\~ animals\\*rich+thatched, data=sandfly)</sub>\n\n\n::: {.cell hash='2023-02-03-Linear-Regresion,-Sessión-4_cache/html/unnamed-chunk-19_d3e0d82662f3b47f19b14d86d4d160bb'}\n\n```{.r .cell-code .numberLines}\nmod13 <- lm(log_parg ~ animals+rich*thatched, data=sandfly)\nsummary(mod13)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = log_parg ~ animals + rich * thatched, data = sandfly)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.1053 -0.6899 -0.0030  0.6862  3.2730 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)    3.09408    0.07087  43.659  < 2e-16 ***\nanimals1       0.56026    0.24181   2.317  0.02093 *  \nrich          -0.34365    0.12195  -2.818  0.00503 ** \nthatched       0.54954    0.11259   4.881 1.44e-06 ***\nrich:thatched  0.19563    0.42168   0.464  0.64291    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.042 on 477 degrees of freedom\n  (18 observations deleted due to missingness)\nMultiple R-squared:  0.1132,\tAdjusted R-squared:  0.1057 \nF-statistic: 15.22 on 4 and 477 DF,  p-value: 1.019e-11\n```\n:::\n\n```{.r .cell-code .numberLines}\nmod14 <- lm(log_parg ~ rich+thatched*animals, data=sandfly)\nsummary(mod14)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = log_parg ~ rich + thatched * animals, data = sandfly)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.0775 -0.6796 -0.0034  0.6854  3.2755 \n\nCoefficients:\n                  Estimate Std. Error t value Pr(>|t|)    \n(Intercept)        3.07750    0.06994  43.999  < 2e-16 ***\nrich              -0.32953    0.11636  -2.832  0.00482 ** \nthatched           0.60208    0.11010   5.469 7.33e-08 ***\nanimals1           1.20517    0.42790   2.817  0.00506 ** \nthatched:animals1 -0.95217    0.51750  -1.840  0.06640 .  \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.038 on 477 degrees of freedom\n  (18 observations deleted due to missingness)\nMultiple R-squared:  0.119,\tAdjusted R-squared:  0.1116 \nF-statistic: 16.11 on 4 and 477 DF,  p-value: 2.206e-12\n```\n:::\n\n```{.r .cell-code .numberLines}\nmod15 <- lm(log_parg ~ animals*rich+thatched, data=sandfly)\nsummary(mod15)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = log_parg ~ animals * rich + thatched, data = sandfly)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.0898 -0.6869  0.0029  0.6843  3.2723 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)    3.08981    0.06989  44.210  < 2e-16 ***\nanimals1       0.48546    0.25532   1.901  0.05785 .  \nrich          -0.33865    0.11749  -2.882  0.00413 ** \nthatched       0.56918    0.10861   5.241 2.41e-07 ***\nanimals1:rich  0.64829    0.78580   0.825  0.40978    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.041 on 477 degrees of freedom\n  (18 observations deleted due to missingness)\nMultiple R-squared:  0.114,\tAdjusted R-squared:  0.1066 \nF-statistic: 15.35 on 4 and 477 DF,  p-value: 8.137e-12\n```\n:::\n:::\n\n\n::: callout-note\nNone of them are statistically significant. So this models are not good\n\n      - rich*thatched       p= 0.64\n      - thatched*animals    p = 0.07\n      - animals*rich        p = 0.41\n\nClarification: To see if some model is better than another, we should perform a F test (anova table), but it will not be done in this exercise\n:::\n\n###### 10. As our final model we keep the model with type of house, asset-index and presence of animals. Please make a table presenting this final model.\n\n<sub> They are talking about lm11 = lm(log_parg \\~ animals + asset_index + house_type, data = sandfly) </sub>\n\n\n::: {.cell hash='2023-02-03-Linear-Regresion,-Sessión-4_cache/html/unnamed-chunk-20_977350fb30272a2f1cff9651e6a4e076'}\n\n```{.r .cell-code .numberLines}\nlm11 = lm(log_parg ~ animals + asset_index + house_type, data = sandfly)\nsummary(lm11)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = log_parg ~ animals + asset_index + house_type, data = sandfly)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.2045 -0.6371 -0.0027  0.6814  3.2001 \n\nCoefficients:\n                         Estimate Std. Error t value Pr(>|t|)    \n(Intercept)              3.129930   0.177465  17.637  < 2e-16 ***\nanimals1                 0.505096   0.243107   2.078 0.038279 *  \nasset_index2             0.114276   0.163992   0.697 0.486246    \nasset_index3            -0.215243   0.149120  -1.443 0.149563    \nasset_index4            -0.137779   0.151997  -0.906 0.365156    \nasset_index5            -0.381083   0.159754  -2.385 0.017451 *  \nhouse_typepbrick_efloor -0.006961   0.160810  -0.043 0.965490    \nhouse_typethatched       0.586305   0.167848   3.493 0.000522 ***\nhouse_typeupbrick        0.074528   0.161122   0.463 0.643897    \n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.04 on 473 degrees of freedom\n  (18 observations deleted due to missingness)\nMultiple R-squared:  0.1231,\tAdjusted R-squared:  0.1083 \nF-statistic: 8.299 on 8 and 473 DF,  p-value: 1.493e-10\n```\n:::\n:::\n\n\n::: callout-note\n      Intercept: 3.129930   \n      R2 : 0.1231\n      P-value of the model: 1.493e-10 (less than 0.05)\n:::\n\n10.1 The table should be like this:\n\n::: callout-note\n| Factor                          | Coefficient | p-value |\n|---------------------------------|-------------|---------|\n| Animals in the house            | 0.51        | 0.04    |\n| Asset index                     |             |         |\n| -1 (poorest)                    | ref         | ref     |\n| -2                              | 0.11        | 0.49    |\n| -3                              | -0.22       | 0.15    |\n| -4                              | -0.14       | 0.37    |\n| -5 (wealthiest)                 | -0.38       | 0.02    |\n| House type                      |             |         |\n| -Thatched                       | 0.59        | 0.0005  |\n| -Unplastered brick              | 0.07        | 0.64    |\n| -Plastered brick earth floor    | -0.007      | 0.97    |\n| -Plastered brick cemented floor | ref         | ref     |\n:::\n\n###### 11. How much of the variability in sand fly exposure is explained by the three factors retained? What would be your conclusion about exposure to sand flies in this rural area.\n\n::: callout-note\nR squared = 0.1231, so the model explains only 12% of the total variability.\n\n    - Being rich and living in a good house (Plastered brick earth floor or cemented\n      floor) reduces outcome, but far from being factors that play an important role.\n    - Could be other factors that play a role. \n:::\n\n###### 12. What is the predicted total number of sandflies in a thatched house with animals inside of a family belonging to the poorest quintile? And in a plastered brick house with cemented floor without animals and belonging to the wealthiest quintile?\n\n12.1 For the first condition:\n\n::: callout-note\nSo the conditions are:\n\n    - Animals in the hous: Yes\n    - House type: thatched house\n    - Assest index: 1 (poorest)\n\nSo the equation for lm11 should be\n\n      y = a + b1X1 + b2x2 + b3x3\n      y = a + b1(animals) + b2(assest_index) + b3 (house_type)\n      y = 3.129930 + 0.51(animals) + 0(assest_index:poorest) + 0.59(house_type:thatched)\n      y = 3.13     + 0.51(1)       + 0                       + 0.59(1)\n    log_parg = 4.23\n      #The \"log of parg\" is 4.23, but I need the value of parg\n    exp(log_parg) = exp(4.23)\n    parg = 69\n      #parg is 69 with this conditions\n:::\n\n12.2 For the second condition:\n\n::: callout-note\nSo the conditions are:\n\n    - Animals in the house: No\n    - House type: Plastered brick cemented floor\n    - Assest index: 5 (wealthiest)\n\nSo the equation for lm11 should be\n\n      y = a + b1X1 + b2x2 + b3x3\n      y = a + b1(animals) + b2(assest_index) + b3 (house_type)\n      y = 3.129930 + 0.51(animals) -0.38(wealthiest) + 0(Plastered brick cemented floor)\n      y = 3.13     + 0.51(0)       -0.38(1)          + 0\n    log_parg = 2.75\n      #The \"log of parg\" is 2.75 , but I need the value of parg\n    exp(log_parg) = exp(2.75)\n    parg = 16\n      #parg is 16 with this conditions\n:::\n\n------------------------------------------------------------------------\n\n------------------------------------------------------------------------\n\n##### Extra\n\n::: callout-note\nIf we want to really check witch model is best than another (like in the step 9), we need to do a f test - anova function and see the p value:\n\n    anova(lm11, mod13)\n\nBut an error may show. When one of the variables that are in one model have missing values, R eliminate those rows when doing the model. So then if we want to compare, the models might not have the same number of rows and the test will fail.\n\nFor this is better to work with a subset of the data with no missing data in all the variables:\n\nSo if I know that asset_index has missing value, then:\n\n    sandfly_complete <- subset(sandfly, !is.na(sandfly$asset_index))\n    or\n    sandfly_complete <- subset(sandfly, complete.cases(sandfly))\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}