{
  "hash": "649f324c918ded58d56ac29832931c2e",
  "result": {
    "markdown": "---\ntitle: \"2023-02-08 Sessión 3\"\nformat: \n  html:\n    self-contained: true\n    theme: cosmo\n    smooth-scroll: true\neditor: visual\n#toc: true\n#toc-depth: 6\n#number-sections: true\n---\n\n\n-   Instituut Voor Tropische Geneeskunde - Antwerp, Belgium\n-   Javier Silva-Valencia\n\n## Step by Step - Selection of variables for modeling\n\n##### Import data\n\nImporting a CSV database under the name of \"onch1302\", with \",\" as separator:\n\n\n::: {.cell hash='2023-02-08-Logistic-Regresion,-Sessión-3_cache/html/unnamed-chunk-1_572bceb2ed1a73766603edae4124b208'}\n\n```{.r .cell-code .numberLines}\nonch1302 <- read.csv(\"C:/Users/pined/OneDrive - Universidad Nacional Mayor de San Marcos/Javier 2022/Belgica/AC2/Logistic Regresion Exercise Database/Datasets/onch1302.csv\", sep=\",\")\n```\n:::\n\n\n------------------------------------------------------------------------\n\n------------------------------------------------------------------------\n\n### Starting the Exercise (MVA_LogReg_Ex1-2023):\n\n<sub> Onchocerciasis (commonly known as River Blindness) is a chronic filarial disease found in sub-Saharan Africa and some parts of Central and South America. An onchocerciasis project was set up in 1982 in the Bo district of Sierra Leone. The aims of the project were to study epidemiological, clin-ical, immunological and entomological aspects of the disease. Prevalence surveys were undertaken in villages selected on the basis of potential high endemicity, being situated on or near rivers which are the breeding sites for the Simulium damnosum blackfly. Of the twelve villages included in the present dataset, five were situated in the south and east of the country in the `forest' zone and the other seven were in the`savannah' zone of the country. A census was taken of each village, and all villagers over the age of five years were asked to participate in the study. Coverage was over 90% in all but one of the selected villages. Diagnosis was made by taking a skin-snip, and clinical and an ocular examination were also performed. The file ONCH1302 contains data for all 1,302 subjects. </sub>\n\n<sub> This time you are asked to make two logistic regression models, first using classical model selection, then change-in-estimate model selection for the effect of area of residence (forest or savannah). Please answer the questions below. </sub>\n\n#### Part 1\n\n###### 1. Which are the steps you will go through for classical model selection?\n\nWe did this in previous excercises\n\n###### 2. Please start by making a table describing the study population. Remember that to get tables with percentages you can use the \"proportions\" or \"prop.table\" function around a table (both functions are the same)\n\n2.1 Modifing variables to work correctly\n\n\n::: {.cell hash='2023-02-08-Logistic-Regresion,-Sessión-3_cache/html/unnamed-chunk-2_c1ebcf2fb82fdd6832cc4b823e65c0f3'}\n\n```{.r .cell-code .numberLines}\nonch1302$female <- factor(onch1302$sex, labels = c(\"male\", \"female\"))\nonch1302$forest <- factor(onch1302$area, labels = c(\"savanna\", \"forest\"))\n\nonch1302$agegrp <- factor(onch1302$agegrp, labels = c(\"(5-9)\", \"(10-19)\", \"(20-29)\", \"(40+)\"))\nonch1302$mf <- factor(onch1302$mf, labels = c(\"non-cases\", \"cases\"))\nonch1302$mfload <- factor(onch1302$mfload, labels = c(\"(none)\", \"(1-9)\", \"(10-49)\", \"(50+)\"))\nonch1302$lesions <- factor(onch1302$lesions, labels = c(\"no\", \"yes\"))\n```\n:::\n\n::: {.cell hash='2023-02-08-Logistic-Regresion,-Sessión-3_cache/html/unnamed-chunk-3_f4d59a690ee646499da1b2ce265dd0e4'}\n\n```{.r .cell-code .numberLines}\n#Lesions\ntable(onch1302$lesions, useNA = \"always\")     #frecuency\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  no  yes <NA> \n1101  201    0 \n```\n:::\n\n```{.r .cell-code .numberLines}\nprop.table(table(onch1302$lesions))           #proportion\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n       no       yes \n0.8456221 0.1543779 \n```\n:::\n\n```{.r .cell-code .numberLines}\n#female\ntable(onch1302$female, useNA = \"always\")     #frecuency\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  male female   <NA> \n   616    686      0 \n```\n:::\n\n```{.r .cell-code .numberLines}\nprop.table(table(onch1302$female))           #proportion\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n     male    female \n0.4731183 0.5268817 \n```\n:::\n\n```{.r .cell-code .numberLines}\n#Forest\ntable(onch1302$forest, useNA = \"always\")     #frecuency\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nsavanna  forest    <NA> \n    548     754       0 \n```\n:::\n\n```{.r .cell-code .numberLines}\nprop.table(table(onch1302$forest))           #proportion\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  savanna    forest \n0.4208909 0.5791091 \n```\n:::\n\n```{.r .cell-code .numberLines}\n#Agegr\ntable(onch1302$agegrp, useNA = \"always\")     #frecuency\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  (5-9) (10-19) (20-29)   (40+)    <NA> \n    202     218     424     458       0 \n```\n:::\n\n```{.r .cell-code .numberLines}\nprop.table(table(onch1302$agegrp))           #proportion\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n    (5-9)   (10-19)   (20-29)     (40+) \n0.1551459 0.1674347 0.3256528 0.3517665 \n```\n:::\n\n```{.r .cell-code .numberLines}\n#Microfilaria\ntable(onch1302$mf, useNA = \"always\")     #frecuency\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nnon-cases     cases      <NA> \n      480       822         0 \n```\n:::\n\n```{.r .cell-code .numberLines}\nprop.table(table(onch1302$mf))           #proportion\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nnon-cases     cases \n0.3686636 0.6313364 \n```\n:::\n\n```{.r .cell-code .numberLines}\n#Microfilaria Load\ntable(onch1302$mfload, useNA = \"always\")     #frecuency\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n (none)   (1-9) (10-49)   (50+)    <NA> \n    480     367     277     178       0 \n```\n:::\n\n```{.r .cell-code .numberLines}\nprop.table(table(onch1302$mfload))           #proportion\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   (none)     (1-9)   (10-49)     (50+) \n0.3686636 0.2818740 0.2127496 0.1367127 \n```\n:::\n:::\n\n\n::: callout-note\n| Factor                  | N (%)      |\n|-------------------------|------------|\n| Total                   | 1302 (100) |\n| Female gender           | 686 (52.7) |\n| Age group               |            |\n| 5-9                     | 202 (15.5) |\n| 10-19                   | 218 (16.7) |\n| 20-39                   | 424 (32.6) |\n| 40+                     | 458 (35.2) |\n| Living in Forest        | 754 (57.9) |\n| Micro filaria infected  | 822 (63.1) |\n| Micro-filarial load     |            |\n| None                    | 480 (36.8) |\n| 1-9                     | 367 (28.1) |\n| 10-49                   | 277 (21.2) |\n| 50+                     | 178 (13.6) |\n| Eyes affected (lesions) | 201 (15.4) |\n:::\n\n###### 3. Next step is to explore the bivariate associations with the outcome variable, microfilarial infection. Please explore these associations using bivariate logistic regression models and construct an appropriate table. Though odds ratios with 95% confidence intervals show which coefficients are significant, please add a column with p-values from the likelihood ratio test so we can decide which factors to test in our multivariate mode\n\n\n::: {.cell hash='2023-02-08-Logistic-Regresion,-Sessión-3_cache/html/unnamed-chunk-4_cd198d8402aaff96f4160f7d0d80fba1'}\n\n```{.r .cell-code .numberLines}\nlibrary(EpiStats)\n```\n:::\n\n\n3.1 Frecuency tables\n\n\n::: {.cell hash='2023-02-08-Logistic-Regresion,-Sessión-3_cache/html/unnamed-chunk-5_3d6c7504a63202bdbfbd97acf4b14731'}\n\n```{.r .cell-code .numberLines}\n#Total\n#table (onch1302$mf)\nprop.table(table (onch1302$mf))  #Porcentajes totales\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nnon-cases     cases \n0.3686636 0.6313364 \n```\n:::\n\n```{.r .cell-code .numberLines}\n#Female\n#table (onch1302$female, onch1302$mf)\nprop.table(table (onch1302$female, onch1302$mf), margin=2)  #Porcentajes por column\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n        \n         non-cases     cases\n  male   0.3958333 0.5182482\n  female 0.6041667 0.4817518\n```\n:::\n\n```{.r .cell-code .numberLines}\n#Age group\n#table (onch1302$agegrp, onch1302$mf)\nprop.table(table (onch1302$agegrp, onch1302$mf), margin=2)  #Porcentajes por fila\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         \n           non-cases      cases\n  (5-9)   0.32500000 0.05596107\n  (10-19) 0.24791667 0.12043796\n  (20-29) 0.26041667 0.36374696\n  (40+)   0.16666667 0.45985401\n```\n:::\n\n```{.r .cell-code .numberLines}\n#forest\n#table (onch1302$forest, onch1302$mf)\nprop.table(table (onch1302$forest, onch1302$mf), margin=2)  #Porcentajes por fila\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         \n          non-cases     cases\n  savanna 0.5562500 0.3418491\n  forest  0.4437500 0.6581509\n```\n:::\n\n```{.r .cell-code .numberLines}\n#lesions\n#table (onch1302$lesions, onch1302$mf)\nprop.table(table (onch1302$lesions, onch1302$mf), margin=2)  #Porcentajes por fila\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     \n       non-cases      cases\n  no  0.96041667 0.77858881\n  yes 0.03958333 0.22141119\n```\n:::\n:::\n\n\n3.2 For calculatin the OR and the p-value of the likelihood ratio test\n\nLogistic model: mf \\~ female\n\n\n::: {.cell hash='2023-02-08-Logistic-Regresion,-Sessión-3_cache/html/unnamed-chunk-6_a3837620ec06f7132a7d0b27bf47cb85'}\n\n```{.r .cell-code .numberLines}\nlm1 <- glm(mf ~ female, family=binomial, data=onch1302)\n#summary(lm1)\nexp(coef(lm1))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n (Intercept) femalefemale \n   2.2421053    0.6090335 \n```\n:::\n\n```{.r .cell-code .numberLines}\nexp(confint(lm1))\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWaiting for profiling to be done...\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n                 2.5 %    97.5 %\n(Intercept)  1.8930554 2.6654704\nfemalefemale 0.4842344 0.7647899\n```\n:::\n\n```{.r .cell-code .numberLines}\nanova(lm1, test=\"Chisq\")  #To check for the p value of the likelihood ratio test\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAnalysis of Deviance Table\n\nModel: binomial, link: logit\n\nResponse: mf\n\nTerms added sequentially (first to last)\n\n       Df Deviance Resid. Df Resid. Dev  Pr(>Chi)    \nNULL                    1301     1714.1              \nfemale  1   18.317      1300     1695.7 1.871e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\nLogistic model: mf \\~ agegrp\n\n\n::: {.cell hash='2023-02-08-Logistic-Regresion,-Sessión-3_cache/html/unnamed-chunk-7_feba543072f5b1e2c1e560af6972ab90'}\n\n```{.r .cell-code .numberLines}\nlm2 <- glm(mf ~ agegrp, family=binomial, data=onch1302)\n#summary(lm2)\nexp(coef(lm2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  (Intercept) agegrp(10-19) agegrp(20-29)   agegrp(40+) \n    0.2948718     2.8213372     8.1120000    16.0239130 \n```\n:::\n\n```{.r .cell-code .numberLines}\nexp(confint(lm2))\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWaiting for profiling to be done...\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n                   2.5 %     97.5 %\n(Intercept)    0.2099851  0.4059964\nagegrp(10-19)  1.8566452  4.3348741\nagegrp(20-29)  5.5353487 12.0770820\nagegrp(40+)   10.7442422 24.3134387\n```\n:::\n\n```{.r .cell-code .numberLines}\nanova(lm2, test=\"Chisq\")  #To check for the p value of the likelihood ratio test\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAnalysis of Deviance Table\n\nModel: binomial, link: logit\n\nResponse: mf\n\nTerms added sequentially (first to last)\n\n       Df Deviance Resid. Df Resid. Dev  Pr(>Chi)    \nNULL                    1301     1714.1              \nagegrp  3    258.4      1298     1455.7 < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\nLogistic model: mf \\~ forest\n\n\n::: {.cell hash='2023-02-08-Logistic-Regresion,-Sessión-3_cache/html/unnamed-chunk-8_df67390a55a6fd306b30b66536697b96'}\n\n```{.r .cell-code .numberLines}\nlm3 <- glm(mf ~ forest, family=binomial, data=onch1302)\nsummary(lm3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = mf ~ forest, family = binomial, data = onch1302)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-1.5900  -1.1992   0.8148   0.8148   1.1558  \n\nCoefficients:\n             Estimate Std. Error z value Pr(>|z|)    \n(Intercept)   0.05111    0.08546   0.598     0.55    \nforestforest  0.88102    0.11767   7.487 7.05e-14 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1714.1  on 1301  degrees of freedom\nResidual deviance: 1657.0  on 1300  degrees of freedom\nAIC: 1661\n\nNumber of Fisher Scoring iterations: 4\n```\n:::\n\n```{.r .cell-code .numberLines}\nexp(coef(lm3))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n (Intercept) forestforest \n    1.052434     2.413363 \n```\n:::\n\n```{.r .cell-code .numberLines}\nexp(confint(lm3))\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWaiting for profiling to be done...\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n                 2.5 %   97.5 %\n(Intercept)  0.8901384 1.244620\nforestforest 1.9176644 3.042055\n```\n:::\n\n```{.r .cell-code .numberLines}\nanova(lm3, test=\"Chisq\")  #To check for the p value of the likelihood ratio test\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAnalysis of Deviance Table\n\nModel: binomial, link: logit\n\nResponse: mf\n\nTerms added sequentially (first to last)\n\n       Df Deviance Resid. Df Resid. Dev  Pr(>Chi)    \nNULL                    1301     1714.1              \nforest  1   57.025      1300     1657.0 4.302e-14 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\nLogistic model: mf \\~ lesions\n\n\n::: {.cell hash='2023-02-08-Logistic-Regresion,-Sessión-3_cache/html/unnamed-chunk-9_64ef8e1033de6b16fc83115229aa86dd'}\n\n```{.r .cell-code .numberLines}\nlm4 <- glm(mf ~ lesions, family=binomial, data=onch1302)\nsummary(lm4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = mf ~ lesions, family = binomial, data = onch1302)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-2.1720  -1.3195   0.4456   1.0416   1.0416  \n\nCoefficients:\n            Estimate Std. Error z value Pr(>|z|)    \n(Intercept)  0.32807    0.06109   5.370 7.85e-08 ***\nlesionsyes   1.93150    0.24868   7.767 8.03e-15 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1714.1  on 1301  degrees of freedom\nResidual deviance: 1622.9  on 1300  degrees of freedom\nAIC: 1626.9\n\nNumber of Fisher Scoring iterations: 4\n```\n:::\n\n```{.r .cell-code .numberLines}\nexp(coef(lm4))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n(Intercept)  lesionsyes \n   1.388286    6.899835 \n```\n:::\n\n```{.r .cell-code .numberLines}\nexp(confint(lm4))\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWaiting for profiling to be done...\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n               2.5 %    97.5 %\n(Intercept) 1.232067  1.565531\nlesionsyes  4.348729 11.590217\n```\n:::\n\n```{.r .cell-code .numberLines}\nanova(lm4, test=\"Chisq\")  #To check for the p value of the likelihood ratio test\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAnalysis of Deviance Table\n\nModel: binomial, link: logit\n\nResponse: mf\n\nTerms added sequentially (first to last)\n\n        Df Deviance Resid. Df Resid. Dev  Pr(>Chi)    \nNULL                     1301     1714.1              \nlesions  1   91.198      1300     1622.9 < 2.2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\n| Factor                 | Cases (% col) | Non-cases (% col) | OR (95% CI)                        | p-value of LRTest          |\n|---------------|---------------|---------------|---------------|---------------|\n| Total                  | 480 (36.9)    | 822 (63.1)        |                                    |                            |\n| Female gender (yes)    | 396 (48.1)    | 290 (60.4)        | 0.6090335 (0.4842344 0.7647899)    | 1.871e-05 \\*\\*\\* (\\<0.001) |\n| Female gender (no)     | 426 (51.8)    | 190 (39.5)        | Ref                                |                            |\n| Age group              |               |                   |                                    |                            |\n| 5-9                    | 46 (5.5)      | 156 (32.5)        | Ref                                | 2.2e-16 \\*\\*\\* (\\<0.001)   |\n| 10-19                  | 99 (12.0)     | 119 (24.7)        | 2.8213372 (1.8566452 4.3348741)    |                            |\n| 20-39                  | 299 (36.3)    | 125 (26.0)        | 8.1120000 (5.5353487 12.0770820)   |                            |\n| 40+                    | 378 (45.9)    | 80 (16.6)         | 16.0239130 (10.7442422 24.3134387) |                            |\n| Living in Forest (yes) | 541 (65.8)    | 213 (44.3)        | 2.413363 (1.9176644 3.042055)      | 4.302e-14 \\*\\*\\* (\\<0.001) |\n| Living in Forest (no)  | 281 (34.1)    | 267 (55.6)        | Ref                                |                            |\n| Lesions (yes)          | 19 (22.1)     | 182 (3.9)         | 6.899835 (4.348729 11.590217)      | 2.2e-16 \\*\\*\\* (\\<0.001)   |\n| Lesions (no)           | 461 (77.8)    | 640 (96.1)        | Ref                                |                            |\n\n::: callout-note\nExample of interpretation: Among the non-cases only 3.9% had lesions\n:::\n\n###### 4. Which variables will you include in the multivariate model? Should eye lesions be included?\n\n::: callout-note\nAll variable had a p-value of the LRTest less than 0.10 Even though because of the nature of the research, we are looking for epidemiological exposures of microfilaria, eye lesions are not an exposure are more a symptom/sign\n:::\n\n###### 5. Fit the model with 'age group' as factor, 'forest' and 'female', which is now the weakest factor (highest p-value)? Does dropping it make the model significantly less precise? Present the final model in a table.\n\n\n::: {.cell hash='2023-02-08-Logistic-Regresion,-Sessión-3_cache/html/unnamed-chunk-10_7f6b086997e08ed7c6f32bae5419d4e4'}\n\n```{.r .cell-code .numberLines}\nlm5 <- glm(mf ~ agegrp + forest + female, family=binomial, data=onch1302)\nsummary(lm5)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nglm(formula = mf ~ agegrp + forest + female, family = binomial, \n    data = onch1302)\n\nDeviance Residuals: \n    Min       1Q   Median       3Q      Max  \n-2.2212  -0.7666   0.5392   0.7081   2.1459  \n\nCoefficients:\n              Estimate Std. Error z value Pr(>|z|)    \n(Intercept)    -1.6157     0.2066  -7.820 5.30e-15 ***\nagegrp(10-19)   0.9429     0.2239   4.211 2.54e-05 ***\nagegrp(20-29)   2.3478     0.2108  11.138  < 2e-16 ***\nagegrp(40+)     2.8713     0.2171  13.225  < 2e-16 ***\nforestforest    1.1227     0.1386   8.099 5.52e-16 ***\nfemalefemale   -0.5813     0.1356  -4.286 1.82e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\n(Dispersion parameter for binomial family taken to be 1)\n\n    Null deviance: 1714.1  on 1301  degrees of freedom\nResidual deviance: 1366.1  on 1296  degrees of freedom\nAIC: 1378.1\n\nNumber of Fisher Scoring iterations: 4\n```\n:::\n\n```{.r .cell-code .numberLines}\nexp(coef(lm5))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  (Intercept) agegrp(10-19) agegrp(20-29)   agegrp(40+)  forestforest \n    0.1987542     2.5673568    10.4623748    17.6593452     3.0731378 \n femalefemale \n    0.5591696 \n```\n:::\n\n```{.r .cell-code .numberLines}\nexp(confint(lm5))\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWaiting for profiling to be done...\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n                   2.5 %     97.5 %\n(Intercept)    0.1312769  0.2954028\nagegrp(10-19)  1.6627984  4.0044862\nagegrp(20-29)  6.9776128 15.9588558\nagegrp(40+)   11.6370517 27.2821110\nforestforest   2.3475876  4.0437091\nfemalefemale   0.4279198  0.7284977\n```\n:::\n:::\n\n\n::: callout-note\nIn lm5 the variable with the highest p-value is female (p value = 1.82e-05). So we will do a new model without female and then compare it with lm5 to see if it caused a significant change\n:::\n\n\n::: {.cell hash='2023-02-08-Logistic-Regresion,-Sessión-3_cache/html/unnamed-chunk-11_462ac6bcd2a4e562639ea5fc8faa0a36'}\n\n```{.r .cell-code .numberLines}\nlm6 <- glm(mf ~ agegrp + forest, family=binomial, data=onch1302)\nanova(lm5, lm6, test=\"Chisq\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAnalysis of Deviance Table\n\nModel 1: mf ~ agegrp + forest + female\nModel 2: mf ~ agegrp + forest\n  Resid. Df Resid. Dev Df Deviance  Pr(>Chi)    \n1      1296     1366.1                          \n2      1297     1384.8 -1  -18.712 1.521e-05 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\n::: callout-note\nThe p value of the Likelihood ratio test is 1.521e-05 (p \\< 0.001), So, when I eliminate female, it changes the model significant making it less precise. So we cannot eliminate female.\n\nThe model we will stick with is the more complex lm5 (mf \\~ agegrp + forest + female) The table of OR of lm5 is:\n\n| Factor (n=1302)      | OR (95% CI)                        |\n|----------------------|------------------------------------|\n| Female gender        | 0.5591696 (0.4279198 0.7284977)    |\n| Age group: 5-9 years | 2.5673568 (1.6627984 4.0044862)    |\n| 10-19 years          | 2.5673568 (1.6627984 4.0044862)    |\n| 20-39 year           | 10.4623748 (6.9776128 15.9588558)  |\n| 40 years and above   | 17.6593452 (11.6370517 27.2821110) |\n| Living in forest     | 3.0731378 (2.3475876 4.0437091)    |\n:::\n\n###### 6. Which are the three potential interactions? Does any of them significantly improve the model? If so, make a table with the odds ratio's in which you have taken into account the interaction.\n\nFor this section we need to test is the variables are ok in that way (lm5) or there are interaction. We will compare lm5 with models with interactions\n\n6.1 Model with forest\\*female as interaction\n\n\n::: {.cell hash='2023-02-08-Logistic-Regresion,-Sessión-3_cache/html/unnamed-chunk-12_597420b8e9c18c0529d8fce867b1a11d'}\n\n```{.r .cell-code .numberLines}\nlm7 <- glm(mf ~ agegrp + forest*female , family=binomial, data=onch1302)\nanova(lm5, lm7, test=\"Chisq\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAnalysis of Deviance Table\n\nModel 1: mf ~ agegrp + forest + female\nModel 2: mf ~ agegrp + forest * female\n  Resid. Df Resid. Dev Df Deviance Pr(>Chi)  \n1      1296     1366.1                       \n2      1295     1361.7  1   4.4028  0.03588 *\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n```\n:::\n:::\n\n\n::: callout-note\nThe p-value of the Likelihood ratio test is 0.03588 (Lower than 0.05). So, it changes the model significant. So there is an interaction between forest\\*female We will keep this model\n:::\n\n6.2 Model with agegrp\\*forest as interaction\n\n\n::: {.cell hash='2023-02-08-Logistic-Regresion,-Sessión-3_cache/html/unnamed-chunk-13_ad91be8497a9a1a3cbd9b7c5b6553fda'}\n\n```{.r .cell-code .numberLines}\nlm8 <- glm(mf ~ agegrp*forest + female , family=binomial, data=onch1302)\nanova(lm5, lm8, test=\"Chisq\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAnalysis of Deviance Table\n\nModel 1: mf ~ agegrp + forest + female\nModel 2: mf ~ agegrp * forest + female\n  Resid. Df Resid. Dev Df Deviance Pr(>Chi)\n1      1296     1366.1                     \n2      1293     1360.8  3   5.2497   0.1544\n```\n:::\n:::\n\n\n::: callout-note\nThe p-value of the Likelihood ratio test is 0.1544 (Higher than 0.05). So, it does not changes the model significant. So there is not an interaction between agegrp\\*forest\n:::\n\n6.3 Model with agegrp\\*female as interaction\n\n\n::: {.cell hash='2023-02-08-Logistic-Regresion,-Sessión-3_cache/html/unnamed-chunk-14_e7f33931a0de8c67c5583a388e4198df'}\n\n```{.r .cell-code .numberLines}\nlm9 <- glm(mf ~ forest + agegrp*female , family=binomial, data=onch1302)\nanova(lm5, lm9, test=\"Chisq\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nAnalysis of Deviance Table\n\nModel 1: mf ~ agegrp + forest + female\nModel 2: mf ~ forest + agegrp * female\n  Resid. Df Resid. Dev Df Deviance Pr(>Chi)\n1      1296     1366.1                     \n2      1293     1361.2  3    4.873   0.1813\n```\n:::\n:::\n\n\n::: callout-note\nThe p-value of the Likelihood ratio test is 0.1813 (Higher than 0.05). So, it does not changes the model significant. So there is not an interaction between agegrp\\*female\n:::\n\n6.3 Filling the table requested Because we now know that we have an interaction : forest\\*female, is better to calculate the OR by categories of the interaction. We could decide to split the data by (women-men) or by (living/ not living in the forest). The most usual is present the results by sex, so:\n\n\n::: {.cell hash='2023-02-08-Logistic-Regresion,-Sessión-3_cache/html/unnamed-chunk-15_8e000f9869a7692afcabbff826b1b48b'}\n\n```{.r .cell-code .numberLines}\ntable(onch1302$female)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  male female \n   616    686 \n```\n:::\n\n```{.r .cell-code .numberLines}\nwomen  <-  subset(onch1302, female==\"female\")  #Creating a database for only women\nmen  <-  subset(onch1302, female==\"male\")    #Creating a database for only male\n```\n:::\n\n\nThe model in women\n\n\n::: {.cell hash='2023-02-08-Logistic-Regresion,-Sessión-3_cache/html/unnamed-chunk-16_4394d2d912023907e8f16f10ce6b4057'}\n\n```{.r .cell-code .numberLines}\nlm10 <- glm(mf ~ agegrp + forest , family=binomial, data=women)\nexp(coef(lm10))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  (Intercept) agegrp(10-19) agegrp(20-29)   agegrp(40+)  forestforest \n   0.09191677    2.13748276   10.48287813   23.11558852    4.15267371 \n```\n:::\n\n```{.r .cell-code .numberLines}\nexp(confint(lm10))\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWaiting for profiling to be done...\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n                    2.5 %     97.5 %\n(Intercept)    0.05060697  0.1596338\nagegrp(10-19)  1.13270252  4.1137899\nagegrp(20-29)  5.97014423 19.1384989\nagegrp(40+)   12.62532875 44.0769379\nforestforest   2.85704938  6.1178354\n```\n:::\n:::\n\n\nThe model in man\n\n\n::: {.cell hash='2023-02-08-Logistic-Regresion,-Sessión-3_cache/html/unnamed-chunk-17_cc36a81abb5cf50467996e93b6eacedd'}\n\n```{.r .cell-code .numberLines}\nlm11 <- glm(mf ~ agegrp + forest , family=binomial, data=men)\nexp(coef(lm11))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  (Intercept) agegrp(10-19) agegrp(20-29)   agegrp(40+)  forestforest \n    0.2392317     3.1894477    11.5596717    13.8388609     2.1425002 \n```\n:::\n\n```{.r .cell-code .numberLines}\nexp(confint(lm11))\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWaiting for profiling to be done...\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n                  2.5 %     97.5 %\n(Intercept)   0.1395508  0.3959848\nagegrp(10-19) 1.7572835  5.9066602\nagegrp(20-29) 6.4172108 21.4996506\nagegrp(40+)   7.8746659 25.0737487\nforestforest  1.4425398  3.1999460\n```\n:::\n:::\n\n\n::: callout-note\n| Factor (n=1302)     | Women (n=686) OR (95% CI)            | Men (N=616) OR (95% CI)           |\n|------------------|----------------------------|--------------------------|\n| Age group:5-9 years |                                      |                                   |\n| 10-19 year          | 2.13748276 (1.13270252 4.1137899)    | 3.1894477 (1.7572835 5.9066602)   |\n| 20-39 year          | 10.48287813 (5.97014423 19.1384989)  | 11.5596717 (6.4172108 21.4996506) |\n| 40 years +          | 23.11558852 (12.62532875 44.0769379) | 13.8388609 (7.8746659 25.0737487) |\n| Living in forest    | 4.15267371 (2.85704938 6.1178354)    | 2.1425002 (1.4425398 3.1999460)   |\n\nThe effect of living in the forest is different for women from men The Odds of having the disease is 4. times as high if you are women living in the forest than women living in savana The Odds of having the disease is 2. times as high if you are men living in the forest than men living in savana\n\nThis is because female is an interaction factor (The interaction test (likelihood ratio test) was significant)\n:::\n\n#### Part 2\n\nChange-in-Estimate model (it change the primary OR exposure) 1. We select the factor that can be exposures and the main exposure: Can we change it? 2. First the crude odd ratio bivariate outcome - primary exposure\n\n\n::: {.cell hash='2023-02-08-Logistic-Regresion,-Sessión-3_cache/html/unnamed-chunk-18_76c1c769cca90161e406bd98cbe20e01'}\n\n```{.r .cell-code .numberLines}\nmod_crude <- glm(mf ~ forest, family=binomial, data=onch1302)\n```\n:::\n\n\n3.  Then adding one variable at the time and writing it down.\n\n\n::: {.cell hash='2023-02-08-Logistic-Regresion,-Sessión-3_cache/html/unnamed-chunk-19_132be89a74bb7c9ca99ffaa64a3c27f4'}\n\n```{.r .cell-code .numberLines}\nmod_1 <- glm(mf ~ forest + sex, family=binomial, data=onch1302)\nmod_2 <- glm(mf ~ forest + agegrp, family=binomial, data=onch1302)\n```\n:::\n\n\n| Factor           | Co-factor     | OR   | Change (Original OR - New OR)/Original OR |\n|-----------------|-----------------|-----------------|----------------------|\n| Living in forest |               | 2.41 |                                           |\n| Living in forest | Female gender | 2.40 | = (2.41 - 2-40)/ 2.41                     |\n|                  |               |      | = 0.4%                                    |\n| Living in forest | Age group     | 3.08 | = (3.08 - 2-41)/ 2.41                     |\n|                  |               |      | = 27.8%                                   |\n\n4.  So the final model for now is: mod_2 \\<- glm(mf \\~ forest + agegrp, family=binomial, data=onch1302)\n\n5.  Tring adding interaction effects If we want to check for interaction, is better to have no so may categories. So we will dichotomize agegroup\n\n\n::: {.cell hash='2023-02-08-Logistic-Regresion,-Sessión-3_cache/html/unnamed-chunk-20_71dd528e91f43da21e098222daf95350'}\n\n```{.r .cell-code .numberLines}\n#Adult variable (adult=1, non adult=0)\n  onch1302$adult <- ifelse(onch1302$agegrp>1,1,0)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in Ops.factor(onch1302$agegrp, 1): '>' not meaningful for factors\n```\n:::\n:::\n\n\nWe compare with the likelihood ratio test the one without interaction (mf \\~ forest + agegrp) and the one with interaction (mf \\~ forest \\* agegrp)\n\nThe p value is not significant, so we keep with te more simple (mf \\~ forest \\* agegrp)\n\n###### 7.Now that you have made the final predictive model (using the classical moldel), let's continue with an explanatory model for the effect of living in the forest versus the savannah. Which factors should we consider? We will follow these steps:\n\n1.  Fit a model containing only the primary exposure variable of interest; write down the effect size, which is the crude OR.\n2.  construct models with two variables, including the primary exposure and another exposure; identify confounders by comparing crude with adjusted ORs\n3.  construct saturated model containing all exposure variables which resulted in a 10% change in effect size of the primary exposure (ref. step 2)\n4.  eliminate exposure variables one after the other, but do not eliminate established confounders; retain exposure variable if removing it resulted in a 10% change in effect size of the primary exposure (ref. step 3)\n5.  Explore interaction between primary exposure and other exposure variables; neglect other types of interaction\n\n###### 8. Present a table with results of logistic regressions on forest alone, forest + female and forest + age group. Did the odds ratios of forest change as a result of this control for confounding?\n\n###### 9. Gender is not a confounder, but age group is. Normally this would be the end of our procedure. However, we would also like to explore interaction effects between the primary exposure and each of the confounders. This is best done by recoding age group to two levels, creating a variable 'adult' set to 'FALSE' if age is 0-19 years and 'TRUE' if age is 20 years or above. Is 'adult' or 'female' an effect modifier in the association between 'forest' and disease?\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}