{
  "hash": "a5738fda70e8d0b7e3c7f968de9ad6db",
  "result": {
    "markdown": "---\ntitle: \"Data Analysis Wk2\"\nformat: \n  html:\n    self-contained: true\n    code-line-numbers: true\n  pdf: \n    documentclass: article\ncustom_title_page: false\nfilters:\n  - lightbox\nlightbox: auto\n---\n\n---\nsubtitle: \"Data Analysis Week - Session 2\"\ndate: 2023-02-28\n\nauthor:\n  - name: Javier Silva-Valencia\n    orcid: 0000-0002-5982-2821\n    email: javier.silva@unmsm.edu.pe\n    affiliations:\n      - name: Instituut Voor Tropische Geneeskunde. Antwerp-Belgium\n\nlanguage: \n  title-block-author-single: \"Writer\"\n  \nabstract: Today we are going to create an index/score. For this we have a lot of variables of socioeconomical aspects and we are going to clean and select the ones we are going to use to create the index/score\n---\n\n\n------------------------------------------------------------------------\n\n------------------------------------------------------------------------\n\n\n### Exercise 1\n\n#### 0. Import CSV\n\n0.1 Set working directory: We are not going to do it now, but this is useful to say to R that all the files we are going to work is that one directory.\n\n0.2 Importing the CSV database under the name of Q1_B_106, with \",\" as separator, and with \".\" as decimal:\n\n\n::: {.cell hash='Data-Analysis-Wk2_cache/html/unnamed-chunk-1_d7fb7de396d238b82b2fcaf4a0a9afde'}\n\n```{.r .cell-code .numberLines}\nQ1_B_106 <- read.csv(\"C:/Users/pined/OneDrive - Universidad Nacional Mayor de San Marcos/Javier 2022/Belgica/AC2_DataAnalysis_ThWk/Material/Q1_B_106.csv\", sep=\",\", dec= \".\")\n```\n:::\n\n\n\n#### 1. Cleaning the dataset\n\n1.1 Seeing the structure of the dataset\n\n::: {.cell hash='Data-Analysis-Wk2_cache/html/unnamed-chunk-2_454aca5e1876f38db77c280b15777aaf'}\n\n```{.r .cell-code .numberLines}\nstr(Q1_B_106)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t13377 obs. of  25 variables:\n $ FSN             : int  45001 45002 45003 45004 45005 45006 45007 45008 45009 45010 ...\n $ Radio           : int  1 1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ CD_Player       : int  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ BW_Television   : int  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Color_Television: int  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Video_DVD_Player: int  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Mobile          : int  -1 -1 -1 -1 -1 1 -1 -1 -1 -1 ...\n $ Non_Mobile_Phone: int  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Refrigerator    : int  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Iron            : int  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Sewing_Machine  : int  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Watch           : int  -1 -1 -1 -1 -1 1 -1 -1 -1 -1 ...\n $ Pressure_Cooker : int  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Chairs          : int  1 -1 -1 -1 1 1 -1 -1 2 -1 ...\n $ Sofas           : int  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Tables          : int  -1 -1 -1 -1 -1 1 -1 -1 -1 -1 ...\n $ Cot_Bed         : int  2 2 3 -1 2 1 2 1 2 -1 ...\n $ Cupboards       : int  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Bicycle         : int  1 1 1 -1 -1 2 -1 -1 1 -1 ...\n $ Motor_Cycle     : int  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Animal_Draw_Cart: int  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Car             : int  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Tractor         : int  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Computer        : int  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Electric_Fan    : int  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n```\n:::\n:::\n\n\n::: callout-tip\nAccording to diccionary\n\n-1 : Missing or not available\n\n0, 1, 2, 3 : Number of items they have\n::: \n\n\n\n::: {.cell hash='Data-Analysis-Wk2_cache/html/unnamed-chunk-3_801f4ef4e824042c5c6ba1fe43ee2be3'}\n\n```{.r .cell-code .numberLines}\nsummary(Q1_B_106)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n      FSN            Radio           CD_Player       BW_Television    \n Min.   :45001   Min.   :-1.0000   Min.   :-1.0000   Min.   :-1.0000  \n 1st Qu.:48527   1st Qu.:-1.0000   1st Qu.:-1.0000   1st Qu.:-1.0000  \n Median :52032   Median :-1.0000   Median :-1.0000   Median :-1.0000  \n Mean   :52110   Mean   :-0.7555   Mean   :-0.9517   Mean   :-0.9015  \n 3rd Qu.:55671   3rd Qu.:-1.0000   3rd Qu.:-1.0000   3rd Qu.:-1.0000  \n Max.   :59606   Max.   : 6.0000   Max.   : 3.0000   Max.   : 2.0000  \n Color_Television  Video_DVD_Player      Mobile         Non_Mobile_Phone \n Min.   :-1.0000   Min.   :-1.0000   Min.   :-1.00000   Min.   :-1.0000  \n 1st Qu.:-1.0000   1st Qu.:-1.0000   1st Qu.:-1.00000   1st Qu.:-1.0000  \n Median :-1.0000   Median :-1.0000   Median :-1.00000   Median :-1.0000  \n Mean   :-0.9217   Mean   :-0.9785   Mean   : 0.01323   Mean   :-0.9885  \n 3rd Qu.:-1.0000   3rd Qu.:-1.0000   3rd Qu.: 1.00000   3rd Qu.:-1.0000  \n Max.   : 2.0000   Max.   : 1.0000   Max.   :10.00000   Max.   : 1.0000  \n  Refrigerator          Iron         Sewing_Machine        Watch        \n Min.   :-1.0000   Min.   :-1.0000   Min.   :-1.0000   Min.   :-1.0000  \n 1st Qu.:-1.0000   1st Qu.:-1.0000   1st Qu.:-1.0000   1st Qu.:-1.0000  \n Median :-1.0000   Median :-1.0000   Median :-1.0000   Median :-1.0000  \n Mean   :-0.9937   Mean   :-0.9415   Mean   :-0.8969   Mean   :-0.3998  \n 3rd Qu.:-1.0000   3rd Qu.:-1.0000   3rd Qu.:-1.0000   3rd Qu.: 1.0000  \n Max.   : 1.0000   Max.   : 4.0000   Max.   : 3.0000   Max.   :12.0000  \n Pressure_Cooker       Chairs            Sofas             Tables       \n Min.   :-1.0000   Min.   :-1.0000   Min.   :-1.0000   Min.   :-1.0000  \n 1st Qu.:-1.0000   1st Qu.:-1.0000   1st Qu.:-1.0000   1st Qu.:-1.0000  \n Median :-1.0000   Median :-1.0000   Median :-1.0000   Median :-1.0000  \n Mean   :-0.8435   Mean   : 0.4572   Mean   :-0.9602   Mean   :-0.2501  \n 3rd Qu.:-1.0000   3rd Qu.: 2.0000   3rd Qu.:-1.0000   3rd Qu.: 1.0000  \n Max.   : 5.0000   Max.   :40.0000   Max.   : 8.0000   Max.   :10.0000  \n    Cot_Bed         Cupboards          Bicycle          Motor_Cycle     \n Min.   :-1.000   Min.   :-1.0000   Min.   :-1.00000   Min.   :-1.0000  \n 1st Qu.: 2.000   1st Qu.:-1.0000   1st Qu.:-1.00000   1st Qu.:-1.0000  \n Median : 2.000   Median :-1.0000   Median : 1.00000   Median :-1.0000  \n Mean   : 2.599   Mean   :-0.9624   Mean   : 0.09793   Mean   :-0.8656  \n 3rd Qu.: 3.000   3rd Qu.:-1.0000   3rd Qu.: 1.00000   3rd Qu.:-1.0000  \n Max.   :24.000   Max.   : 7.0000   Max.   : 6.00000   Max.   : 5.0000  \n Animal_Draw_Cart       Car             Tractor           Computer      \n Min.   :-1.0000   Min.   :-1.0000   Min.   :-1.0000   Min.   :-1.0000  \n 1st Qu.:-1.0000   1st Qu.:-1.0000   1st Qu.:-1.0000   1st Qu.:-1.0000  \n Median :-1.0000   Median :-1.0000   Median :-1.0000   Median :-1.0000  \n Mean   :-0.9919   Mean   :-0.9938   Mean   :-0.9874   Mean   :-0.9982  \n 3rd Qu.:-1.0000   3rd Qu.:-1.0000   3rd Qu.:-1.0000   3rd Qu.:-1.0000  \n Max.   : 1.0000   Max.   : 2.0000   Max.   : 3.0000   Max.   : 1.0000  \n  Electric_Fan    \n Min.   :-1.0000  \n 1st Qu.:-1.0000  \n Median :-1.0000  \n Mean   :-0.6872  \n 3rd Qu.:-1.0000  \n Max.   :11.0000  \n```\n:::\n:::\n\n::: callout-tip\nExample of what we can see: The maximum number of radios in a household is 6\n::: \n\n#### 2. Replace values\n\n2.1 We need that all ‘-1’  be converting to ‘0’ \n\nand all value more than ‘≥ 1’ be converting to ‘1’\n\n\n::: {.cell hash='Data-Analysis-Wk2_cache/html/unnamed-chunk-4_a966b852736b041bd0439ab0afcb8787'}\n\n```{.r .cell-code .numberLines}\n#We can do it by using \"if else\":\nQ1_B_106$own_Radio <- ifelse(Q1_B_106$Radio>0,1,0)\n\n\n#But other way is: \n#Q1_B_106$own_Radio <- as.numeric(Q1_B_106$Radio > 0)\n#Ask to create a variable called \"own_Radio\" only TRUE when \"Radio\" is more than 0 and converting that into a number (as.numeric) (1:true,0:false)\n\n\n#Checking if it works\ntable(Q1_B_106$own_Radio, Q1_B_106$Radio, useNA = \"always\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n      \n          -1     1     2     3     6  <NA>\n  0    11753     0     0     0     0     0\n  1        0  1608    12     3     1     0\n  <NA>     0     0     0     0     0     0\n```\n:::\n\n```{.r .cell-code .numberLines}\nsummary(Q1_B_106$own_Radio)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n 0.0000  0.0000  0.0000  0.1214  0.0000  1.0000 \n```\n:::\n:::\n\n::: callout-tip\n12.14% of households have at least one radio.\nWhen we only have 0 and 1, The mean is the proportion of individuals having the exposure.\n::: \n\nWe need to do that for every variable\n\n\n::: {.cell hash='Data-Analysis-Wk2_cache/html/unnamed-chunk-5_75984609d315bcf4881bc8ddde9c65f5'}\n\n```{.r .cell-code .numberLines}\nQ1_B_106$own_Radio <- ifelse(Q1_B_106$Radio>0,1,0)\nQ1_B_106$own_CD_Player <- ifelse(Q1_B_106$CD_Player>0,1,0)\nQ1_B_106$own_BW_Television <- ifelse(Q1_B_106$BW_Television>0,1,0)\nQ1_B_106$own_Color_Television <- ifelse(Q1_B_106$Color_Television>0,1,0)\nQ1_B_106$own_Video_DVD_Player <- ifelse(Q1_B_106$Video_DVD_Player>0,1,0)\nQ1_B_106$own_Mobile <- ifelse(Q1_B_106$Mobile>0,1,0)\nQ1_B_106$own_Non_Mobile_Phone <- ifelse(Q1_B_106$Non_Mobile_Phone>0,1,0)\nQ1_B_106$own_Refrigerator <- ifelse(Q1_B_106$Refrigerator>0,1,0)\nQ1_B_106$own_Iron <- ifelse(Q1_B_106$Iron>0,1,0)\nQ1_B_106$own_Sewing_Machine <- ifelse(Q1_B_106$Sewing_Machine>0,1,0)\nQ1_B_106$own_Watch <- ifelse(Q1_B_106$Watch>0,1,0)\nQ1_B_106$own_Pressure_Cooker <- ifelse(Q1_B_106$Pressure_Cooker>0,1,0)\nQ1_B_106$own_Chairs <- ifelse(Q1_B_106$Chairs>0,1,0)\nQ1_B_106$own_Sofas <- ifelse(Q1_B_106$Sofas>0,1,0)\nQ1_B_106$own_Tables <- ifelse(Q1_B_106$Tables>0,1,0)\nQ1_B_106$own_Cot_Bed <- ifelse(Q1_B_106$Cot_Bed>0,1,0)\nQ1_B_106$own_Cupboards <- ifelse(Q1_B_106$Cupboards>0,1,0)\nQ1_B_106$own_Bicycle <- ifelse(Q1_B_106$Bicycle>0,1,0)\nQ1_B_106$own_Motor_Cycle <- ifelse(Q1_B_106$Motor_Cycle>0,1,0)\nQ1_B_106$own_Animal_Draw_Cart <- ifelse(Q1_B_106$Animal_Draw_Cart>0,1,0)\nQ1_B_106$own_Car <- ifelse(Q1_B_106$Car>0,1,0)\nQ1_B_106$own_Tractor <- ifelse(Q1_B_106$Tractor>0,1,0)\nQ1_B_106$own_Computer <- ifelse(Q1_B_106$Computer>0,1,0)\nQ1_B_106$own_Electric_Fan <- ifelse(Q1_B_106$Electric_Fan>0,1,0)\n```\n:::\n\n\n\n2.2 Now we will make a subset containing only the ‘own’ variables and  FSN\n\n::: {.cell hash='Data-Analysis-Wk2_cache/html/unnamed-chunk-6_cc024dda9adef05835d387d7c96f837c'}\n\n```{.r .cell-code .numberLines}\nassets <- subset(Q1_B_106, select = grepl(\"own|FSN\", names(Q1_B_106)))\nstr(assets)  \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t13377 obs. of  25 variables:\n $ FSN                 : int  45001 45002 45003 45004 45005 45006 45007 45008 45009 45010 ...\n $ own_Radio           : num  1 1 0 0 0 0 0 0 0 0 ...\n $ own_CD_Player       : num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_BW_Television   : num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Color_Television: num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Video_DVD_Player: num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Mobile          : num  0 0 0 0 0 1 0 0 0 0 ...\n $ own_Non_Mobile_Phone: num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Refrigerator    : num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Iron            : num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Sewing_Machine  : num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Watch           : num  0 0 0 0 0 1 0 0 0 0 ...\n $ own_Pressure_Cooker : num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Chairs          : num  1 0 0 0 1 1 0 0 1 0 ...\n $ own_Sofas           : num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Tables          : num  0 0 0 0 0 1 0 0 0 0 ...\n $ own_Cot_Bed         : num  1 1 1 0 1 1 1 1 1 0 ...\n $ own_Cupboards       : num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Bicycle         : num  1 1 1 0 0 1 0 0 1 0 ...\n $ own_Motor_Cycle     : num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Animal_Draw_Cart: num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Car             : num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Tractor         : num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Computer        : num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Electric_Fan    : num  0 0 0 0 0 0 0 0 0 0 ...\n```\n:::\n:::\n\n\n2.3 Now we will focus only in those variables whose mean have a value between 5-95% (0.05-0.95)\n\nwhy?:\nBecause the mean is the proportion of individuals having the exposure, we are going to exclude the variables that nobody has (less than 5%) and the variables that all people has (more than 95%)\n\n\n::: {.cell hash='Data-Analysis-Wk2_cache/html/unnamed-chunk-7_19036f65ca8e31de4e888984f3d2608f'}\n\n```{.r .cell-code .numberLines}\n#summary(assets)\nround(sapply(assets, FUN=mean),3)   #To display the mean of each variable with 3 decimals\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                 FSN            own_Radio        own_CD_Player \n           52110.000                0.121                0.024 \n   own_BW_Television own_Color_Television own_Video_DVD_Player \n               0.049                0.039                0.011 \n          own_Mobile own_Non_Mobile_Phone     own_Refrigerator \n               0.476                0.006                0.003 \n            own_Iron   own_Sewing_Machine            own_Watch \n               0.028                0.051                0.264 \n own_Pressure_Cooker           own_Chairs            own_Sofas \n               0.072                0.429                0.017 \n          own_Tables          own_Cot_Bed        own_Cupboards \n               0.329                0.968                0.013 \n         own_Bicycle      own_Motor_Cycle own_Animal_Draw_Cart \n               0.524                0.065                0.004 \n             own_Car          own_Tractor         own_Computer \n               0.003                0.006                0.001 \n    own_Electric_Fan \n               0.110 \n```\n:::\n:::\n\n::: callout-tip\nBesides FSN, 10 variables have a value between 5-95% (0.05-0.95) \n::: \n\n\n2.3 We are going to create a new subset (assets2) with only in those variables whose mean have a value between 5-95% (0.05-0.95)\n\n\n::: {.cell hash='Data-Analysis-Wk2_cache/html/unnamed-chunk-8_cfbc15fef71a99cb405da1492813b2aa'}\n\n```{.r .cell-code .numberLines}\nassets2 <- subset(assets, select = c(FSN, own_Radio,own_Mobile, own_Sewing_Machine, own_Watch, own_Pressure_Cooker, own_Chairs, own_Tables, own_Bicycle, own_Motor_Cycle, own_Electric_Fan))\nstr(assets2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t13377 obs. of  11 variables:\n $ FSN                : int  45001 45002 45003 45004 45005 45006 45007 45008 45009 45010 ...\n $ own_Radio          : num  1 1 0 0 0 0 0 0 0 0 ...\n $ own_Mobile         : num  0 0 0 0 0 1 0 0 0 0 ...\n $ own_Sewing_Machine : num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Watch          : num  0 0 0 0 0 1 0 0 0 0 ...\n $ own_Pressure_Cooker: num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Chairs         : num  1 0 0 0 1 1 0 0 1 0 ...\n $ own_Tables         : num  0 0 0 0 0 1 0 0 0 0 ...\n $ own_Bicycle        : num  1 1 1 0 0 1 0 0 1 0 ...\n $ own_Motor_Cycle    : num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Electric_Fan   : num  0 0 0 0 0 0 0 0 0 0 ...\n```\n:::\n:::\n\n\n#### 3. Adding animals variable\n\nThe researchers noticed that having a \"bovines animals\" variable is important, so we need to incorporate it. The only problem is that the animals information is in another dataset.\n\n’own_bov’ for each household = whether or not it owns cows or buffaloes\n\n\n::: {.cell hash='Data-Analysis-Wk2_cache/html/unnamed-chunk-9_9cb4cd2fc0678dafb4340268c857e616'}\n\n```{.r .cell-code .numberLines}\nanimals = readRDS(\"animals.RDS\")\nhlp1 <- subset(animals, select=c(FSN, count_Cow, count_Buf))\nhlp1$own_bov <- NA\nhlp1$own_bov[hlp1$count_Cow== 0 & hlp1$count_Buf==0] <- 0\nhlp1$own_bov[hlp1$count_Cow> 0 | hlp1$count_Buf>0] <- 1 \nstr(hlp1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t7147 obs. of  4 variables:\n $ FSN      : int  45001 45002 45003 45004 45006 45009 45021 45024 45025 45027 ...\n $ count_Cow: int  NA NA 1 NA 2 NA 3 NA NA NA ...\n $ count_Buf: int  NA 1 NA NA NA NA NA NA NA NA ...\n $ own_bov  : num  NA 1 1 NA 1 NA 1 NA NA NA ...\n```\n:::\n:::\n\n\n#### 4. Adding brick wall variable\n\nThe researchers noticed that having a \"brick_wall\" variable is important, so we need to incorporate it. The only problem is that the brick_wall information is in another dataset.\n\n\n4.1 Opening Q1_B dataset\n\n::: {.cell hash='Data-Analysis-Wk2_cache/html/unnamed-chunk-10_059d55851e8f365b874a6cf48d53c766'}\n\n```{.r .cell-code .numberLines}\nQ1_B <- read.csv(\"C:/Users/pined/OneDrive - Universidad Nacional Mayor de San Marcos/Javier 2022/Belgica/AC2_DataAnalysis_ThWk/Material/Q1_B.csv\", sep=\",\", dec= \".\")\n```\n:::\n\n\n4.2 Checking the variable Wall_Material in the Q1_B dataset\n\n::: {.cell hash='Data-Analysis-Wk2_cache/html/unnamed-chunk-11_5135b7d6d1cc94a19b082dc2675fb51e'}\n\n```{.r .cell-code .numberLines}\ntable(Q1_B$Wall_Material)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   6  162  163  164  165  166 \n   4 4498  169 5791 2914    1 \n```\n:::\n:::\n\n::: callout-tip\nAccording the code list:\n\n    6= Other\n    163= Grass\n    163= Bamboo\n    164, 165, 166= Brick\n\nSo we only need those who had the value 164 or 165 in the Wall_Material variable\n::: \n\n4.3. I only need \"FSN\" and \"WallMaterial\" variables\n\n::: {.cell hash='Data-Analysis-Wk2_cache/html/unnamed-chunk-12_ec67e032813a4e2f31a2815d8ed9c9ff'}\n\n```{.r .cell-code .numberLines}\nhlp2 <- subset(Q1_B, select = c(FSN, Wall_Material))\n```\n:::\n\n\n4.4  Creating a new variable called brickwall according to what I need\n\n::: {.cell hash='Data-Analysis-Wk2_cache/html/unnamed-chunk-13_daddc92f152b34242e05c80b977171c5'}\n\n```{.r .cell-code .numberLines}\nhlp2$brick_wall <- NA\nhlp2$brick_wall[hlp2$Wall_Material %in% c(6,162,163)] <- 0\nhlp2$brick_wall[hlp2$Wall_Material %in% c(164:166)] <- 1\n\ntable(hlp2$brick_wall, Q1_B$Wall_Material)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   \n       6  162  163  164  165  166\n  0    4 4498  169    0    0    0\n  1    0    0    0 5791 2914    1\n```\n:::\n:::\n\n\n#### 5. Merging datasets\n\n![Merging planning](mergingdatsets.png)\n\n\n5.1 Merging hlp1 and hlp2\n\n::: {.cell hash='Data-Analysis-Wk2_cache/html/unnamed-chunk-14_17494ba5a2bc79bdb2bd971bc027924c'}\n\n```{.r .cell-code .numberLines}\nstr(hlp1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t7147 obs. of  4 variables:\n $ FSN      : int  45001 45002 45003 45004 45006 45009 45021 45024 45025 45027 ...\n $ count_Cow: int  NA NA 1 NA 2 NA 3 NA NA NA ...\n $ count_Buf: int  NA 1 NA NA NA NA NA NA NA NA ...\n $ own_bov  : num  NA 1 1 NA 1 NA 1 NA NA NA ...\n```\n:::\n\n```{.r .cell-code .numberLines}\nstr(hlp2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t13377 obs. of  3 variables:\n $ FSN          : num  45001 45002 45003 45004 45005 ...\n $ Wall_Material: num  164 164 164 162 163 163 162 164 164 162 ...\n $ brick_wall   : num  1 1 1 0 0 0 0 1 1 0 ...\n```\n:::\n\n```{.r .cell-code .numberLines}\nhlp  <-  merge(hlp2, hlp1, all=TRUE, by = \"FSN\")\nstr(hlp)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t13377 obs. of  6 variables:\n $ FSN          : num  45001 45002 45003 45004 45005 ...\n $ Wall_Material: num  164 164 164 162 163 163 162 164 164 162 ...\n $ brick_wall   : num  1 1 1 0 0 0 0 1 1 0 ...\n $ count_Cow    : int  NA NA 1 NA NA 2 NA NA NA NA ...\n $ count_Buf    : int  NA 1 NA NA NA NA NA NA NA NA ...\n $ own_bov      : num  NA 1 1 NA NA 1 NA NA NA NA ...\n```\n:::\n\n```{.r .cell-code .numberLines}\n#View(hlp)\n```\n:::\n\nwe Dont need countCow, count_Buf or Wall_Material\n\n::: {.cell hash='Data-Analysis-Wk2_cache/html/unnamed-chunk-15_d4fc69956c8bb2666ae9667eca159910'}\n\n```{.r .cell-code .numberLines}\nhlp <- subset(hlp, select=-c(count_Cow,count_Buf,Wall_Material))\nstr(hlp)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t13377 obs. of  3 variables:\n $ FSN       : num  45001 45002 45003 45004 45005 ...\n $ brick_wall: num  1 1 1 0 0 0 0 1 1 0 ...\n $ own_bov   : num  NA 1 1 NA NA 1 NA NA NA NA ...\n```\n:::\n:::\n\n\n5.2 Merging hlp2 to assets2\n\n::: {.cell hash='Data-Analysis-Wk2_cache/html/unnamed-chunk-16_32ea637a0d38ebf11ced4e4fad1bea81'}\n\n```{.r .cell-code .numberLines}\nstr(hlp)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t13377 obs. of  3 variables:\n $ FSN       : num  45001 45002 45003 45004 45005 ...\n $ brick_wall: num  1 1 1 0 0 0 0 1 1 0 ...\n $ own_bov   : num  NA 1 1 NA NA 1 NA NA NA NA ...\n```\n:::\n\n```{.r .cell-code .numberLines}\nstr(assets2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t13377 obs. of  11 variables:\n $ FSN                : int  45001 45002 45003 45004 45005 45006 45007 45008 45009 45010 ...\n $ own_Radio          : num  1 1 0 0 0 0 0 0 0 0 ...\n $ own_Mobile         : num  0 0 0 0 0 1 0 0 0 0 ...\n $ own_Sewing_Machine : num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Watch          : num  0 0 0 0 0 1 0 0 0 0 ...\n $ own_Pressure_Cooker: num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Chairs         : num  1 0 0 0 1 1 0 0 1 0 ...\n $ own_Tables         : num  0 0 0 0 0 1 0 0 0 0 ...\n $ own_Bicycle        : num  1 1 1 0 0 1 0 0 1 0 ...\n $ own_Motor_Cycle    : num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Electric_Fan   : num  0 0 0 0 0 0 0 0 0 0 ...\n```\n:::\n\n```{.r .cell-code .numberLines}\nassets3  <-  merge(assets2, hlp, all=TRUE, by = \"FSN\")\nstr(assets3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t13377 obs. of  13 variables:\n $ FSN                : int  45001 45002 45003 45004 45005 45006 45007 45008 45009 45010 ...\n $ own_Radio          : num  1 1 0 0 0 0 0 0 0 0 ...\n $ own_Mobile         : num  0 0 0 0 0 1 0 0 0 0 ...\n $ own_Sewing_Machine : num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Watch          : num  0 0 0 0 0 1 0 0 0 0 ...\n $ own_Pressure_Cooker: num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Chairs         : num  1 0 0 0 1 1 0 0 1 0 ...\n $ own_Tables         : num  0 0 0 0 0 1 0 0 0 0 ...\n $ own_Bicycle        : num  1 1 1 0 0 1 0 0 1 0 ...\n $ own_Motor_Cycle    : num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Electric_Fan   : num  0 0 0 0 0 0 0 0 0 0 ...\n $ brick_wall         : num  1 1 1 0 0 0 0 1 1 0 ...\n $ own_bov            : num  NA 1 1 NA NA 1 NA NA NA NA ...\n```\n:::\n\n```{.r .cell-code .numberLines}\n#View(assets3)\n```\n:::\n\n5.3 Check NA values\n\nThe merging creates NA values (ex: in own_bov), but that values are because that household doesnt have a bovine animal, so it should be 0\n\nChecking NA\n\n::: {.cell hash='Data-Analysis-Wk2_cache/html/unnamed-chunk-17_ae04cf6a75bc285d591d6ba9c618dc7f'}\n\n```{.r .cell-code .numberLines}\ntable (assets3$own_bov)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   0    1 \n   1 4331 \n```\n:::\n\n```{.r .cell-code .numberLines}\ntable (assets3$own_bov, useNA = \"ifany\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   0    1 <NA> \n   1 4331 9045 \n```\n:::\n\n```{.r .cell-code .numberLines}\ntable (assets3$own_bov, useNA = \"always\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   0    1 <NA> \n   1 4331 9045 \n```\n:::\n\n```{.r .cell-code .numberLines}\nstr(assets3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t13377 obs. of  13 variables:\n $ FSN                : int  45001 45002 45003 45004 45005 45006 45007 45008 45009 45010 ...\n $ own_Radio          : num  1 1 0 0 0 0 0 0 0 0 ...\n $ own_Mobile         : num  0 0 0 0 0 1 0 0 0 0 ...\n $ own_Sewing_Machine : num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Watch          : num  0 0 0 0 0 1 0 0 0 0 ...\n $ own_Pressure_Cooker: num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Chairs         : num  1 0 0 0 1 1 0 0 1 0 ...\n $ own_Tables         : num  0 0 0 0 0 1 0 0 0 0 ...\n $ own_Bicycle        : num  1 1 1 0 0 1 0 0 1 0 ...\n $ own_Motor_Cycle    : num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Electric_Fan   : num  0 0 0 0 0 0 0 0 0 0 ...\n $ brick_wall         : num  1 1 1 0 0 0 0 1 1 0 ...\n $ own_bov            : num  NA 1 1 NA NA 1 NA NA NA NA ...\n```\n:::\n:::\n\n\n5.4 Replacing NA\n\n::: {.cell hash='Data-Analysis-Wk2_cache/html/unnamed-chunk-18_d650a00feb11cc8da5f3638367c9034e'}\n\n```{.r .cell-code .numberLines}\nassets3$own_bov[is.na(assets3$own_bov)]<- 0\n#View(assets3)\ntable (assets3$own_bov, useNA = \"always\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   0    1 <NA> \n9046 4331    0 \n```\n:::\n:::\n\n\n\n#### 6. Principle component analysis\n\n::: {.callout-tip collapse=\"true\"}\n## What is a Principle component analysis (PCA)?\n\n*Principal Component Analysis (PCA)* is a statistical technique that is used to transform a large number of variables into a smaller number (or just 1) new variable. Is often used for making scores or index.\n\nWhen we do a score/index we tend to put equal weight to every variable because we think that every variable is equal important. But is that true? Usually no. So in *Principle component analysis* we try to put a weight to every variable depending the variance. It is useful to also put in in order to know which first component we need to work. (Which variables are representatives and in what measure)\n\nThe idea behind PCA is to find the underlying patterns in the data using its variances. The analysis will create a first (principal) component, then a second, third, and so on. Each component captures a different aspect of the variation in the data, with the first  component capturing the most variation, and subsequent components capturing progressively less. \n\nUsually we use the first component and with that then create a weighted variable for each individual.\n\n::: \n\n\n::: {.cell hash='Data-Analysis-Wk2_cache/html/unnamed-chunk-19_6a883c482f0746aa9e1016b7fc325fa0'}\n\n```{.r .cell-code .numberLines}\nnames(assets3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"FSN\"                 \"own_Radio\"           \"own_Mobile\"         \n [4] \"own_Sewing_Machine\"  \"own_Watch\"           \"own_Pressure_Cooker\"\n [7] \"own_Chairs\"          \"own_Tables\"          \"own_Bicycle\"        \n[10] \"own_Motor_Cycle\"     \"own_Electric_Fan\"    \"brick_wall\"         \n[13] \"own_bov\"            \n```\n:::\n:::\n\n6.1 PCA code\n\n::: {.cell hash='Data-Analysis-Wk2_cache/html/unnamed-chunk-20_9a6b161e6debe78208d81ea456a52eb5'}\n\n```{.r .cell-code .numberLines}\npcamod <- princomp(~own_Radio+own_Mobile+own_Sewing_Machine++own_Watch+own_Pressure_Cooker+own_Chairs+own_Tables+own_Bicycle+own_Motor_Cycle+own_Electric_Fan+brick_wall+ own_bov, cor=TRUE, data= assets3)\n```\n:::\n\n\n6.2 Inspect the component loadings of Comp.1\n\n::: {.cell hash='Data-Analysis-Wk2_cache/html/unnamed-chunk-21_7bef8b75b40aaeab6b650bdc85b14927'}\n\n```{.r .cell-code .numberLines}\npcamod$loadings\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nLoadings:\n                    Comp.1 Comp.2 Comp.3 Comp.4 Comp.5 Comp.6 Comp.7 Comp.8\nown_Radio            0.235  0.106  0.288  0.506  0.724         0.208       \nown_Mobile           0.321  0.245 -0.106  0.173               -0.415 -0.498\nown_Sewing_Machine   0.235 -0.274  0.302  0.125 -0.210 -0.799  0.203 -0.131\nown_Watch            0.351                0.120               -0.199  0.427\nown_Pressure_Cooker  0.310 -0.348  0.220                      -0.195  0.415\nown_Chairs           0.357  0.183 -0.334        -0.198         0.388       \nown_Tables           0.362        -0.333        -0.216  0.115  0.420       \nown_Bicycle          0.246  0.501  0.137               -0.150 -0.448       \nown_Motor_Cycle      0.296 -0.280  0.277 -0.205         0.309        -0.588\nown_Electric_Fan     0.328 -0.299        -0.228         0.286 -0.159  0.101\nbrick_wall           0.215        -0.452 -0.540  0.563 -0.357              \nown_bov                     0.523  0.485 -0.523                0.317  0.121\n                    Comp.9 Comp.10 Comp.11 Comp.12\nown_Radio                                         \nown_Mobile          -0.289  0.508  -0.162         \nown_Sewing_Machine                  0.140         \nown_Watch           -0.676 -0.420                 \nown_Pressure_Cooker  0.310  0.280  -0.573         \nown_Chairs           0.132                 -0.711 \nown_Tables           0.147                  0.696 \nown_Bicycle          0.516 -0.379   0.145         \nown_Motor_Cycle            -0.479  -0.186         \nown_Electric_Fan            0.260   0.745         \nbrick_wall                                        \nown_bov             -0.225  0.196                 \n\n               Comp.1 Comp.2 Comp.3 Comp.4 Comp.5 Comp.6 Comp.7 Comp.8 Comp.9\nSS loadings     1.000  1.000  1.000  1.000  1.000  1.000  1.000  1.000  1.000\nProportion Var  0.083  0.083  0.083  0.083  0.083  0.083  0.083  0.083  0.083\nCumulative Var  0.083  0.167  0.250  0.333  0.417  0.500  0.583  0.667  0.750\n               Comp.10 Comp.11 Comp.12\nSS loadings      1.000   1.000   1.000\nProportion Var   0.083   0.083   0.083\nCumulative Var   0.833   0.917   1.000\n```\n:::\n:::\n\n::: callout-tip\nWe have to choose one model (one component) to select their scores\n::: \n\n\n6.3 Extract the component scores\n\nCreate a variable named PC1 in assets3 from the scores un pcamod\n\n::: {.cell hash='Data-Analysis-Wk2_cache/html/unnamed-chunk-22_96d9b0f376ed3a35e1b15b352318c86c'}\n\n```{.r .cell-code .numberLines}\nassets3$PC1 <- pcamod$scores[ ,1]\n#View(assets3)\n```\n:::\n\n\n\n6.4 Check the quintiles\n\n::: {.cell hash='Data-Analysis-Wk2_cache/html/unnamed-chunk-23_ca6c74ca872636f7ff0ed2a8e35e2189'}\n\n```{.r .cell-code .numberLines}\nquantile(assets3$PC1, probs = seq(0,1, 1/5))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         0%         20%         40%         60%         80%        100% \n-2.11118368 -1.66100172 -0.98271146 -0.06987735  1.45281527  7.18120558 \n```\n:::\n:::\n\n\n6.5 Create a new categorical variable ‘asset_index’ with values 1-5 by quintile\n\n::: {.cell hash='Data-Analysis-Wk2_cache/html/unnamed-chunk-24_bb24c45f97c2aa45c86e5620dd9f909f'}\n\n```{.r .cell-code .numberLines}\nassets3$asset_index <- NA\nassets3$asset_index[assets3$PC1 >= -2.11118368   & assets3$PC1 <=-1.66100172  ] <- \"1\"\nassets3$asset_index[assets3$PC1 >-1.66100172    & assets3$PC1 <=-0.98271146   ] <- \"2\"\nassets3$asset_index[assets3$PC1 >-0.98271146    & assets3$PC1 <=-0.06987735    ] <- \"3\"\nassets3$asset_index[assets3$PC1 >-0.06987735     & assets3$PC1 <=1.45281527    ] <- \"4\"\nassets3$asset_index[assets3$PC1 >1.45281527     & assets3$PC1 <=7.18120558  ] <- \"5\"\n```\n:::\n\n\n\n6.6 Drop unnecessary variables by making a subset\n\nOr final dataset (with the Asset index) only need to have FSN and asset_index\n\n::: {.cell hash='Data-Analysis-Wk2_cache/html/unnamed-chunk-25_2d7d494dd4519afea2ae462f5991fcdf'}\n\n```{.r .cell-code .numberLines}\nassets4 <- subset(assets3, select= c(FSN,asset_index))\nstr(assets4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t13377 obs. of  2 variables:\n $ FSN        : int  45001 45002 45003 45004 45005 45006 45007 45008 45009 45010 ...\n $ asset_index: chr  \"4\" \"3\" \"2\" \"1\" ...\n```\n:::\n\n```{.r .cell-code .numberLines}\ntable(assets4$asset_index)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   1    2    3    4    5 \n3243 2254 2581 2632 2667 \n```\n:::\n:::\n\n\n#### 7. Merging with the other databases\n\n7.1 Opening Questionnaire_1\n\n::: {.cell hash='Data-Analysis-Wk2_cache/html/unnamed-chunk-26_d7fc54e1e277e4de3a5358514986f8b6'}\n\n```{.r .cell-code .numberLines}\nQuestionnaire_1 <- read.csv(\"C:/Users/pined/OneDrive - Universidad Nacional Mayor de San Marcos/Javier 2022/Belgica/AC2_DataAnalysis_ThWk/Material/Questionnaire_1.csv\", sep=\",\", dec= \".\")\n```\n:::\n\n::: {.cell hash='Data-Analysis-Wk2_cache/html/unnamed-chunk-27_767b66ad5d025b2869cb78c22c447954'}\n\n```{.r .cell-code .numberLines}\nstr(Questionnaire_1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t13377 obs. of  10 variables:\n $ FSN                    : int  45001 45002 45003 45004 45005 45006 45007 45008 45009 45010 ...\n $ panchyat_id            : int  2 2 2 2 2 2 2 2 2 2 ...\n $ village_id             : int  11 11 11 11 11 11 11 11 11 11 ...\n $ ward_no                : int  1 1 1 1 1 1 1 1 1 1 ...\n $ household_no           : int  21 680 290 3390 181 3501 1401 2330 3750 2371 ...\n $ household_head_age     : int  50 35 60 35 40 40 60 23 25 40 ...\n $ household_head_sex     : int  2 2 2 2 2 2 2 2 2 3 ...\n $ household_head_religion: int  4 4 4 4 4 4 4 4 4 4 ...\n $ household_head_caste   : int  9 9 9 9 9 9 9 9 9 9 ...\n $ household_head_subcaste: chr  \"PASWAN\" \"PASWAN\" \"PASWAN\" \"PASWAN\" ...\n```\n:::\n:::\n\n7.2 Merging with the assets\n\n::: {.cell hash='Data-Analysis-Wk2_cache/html/unnamed-chunk-28_c0110c556f5ea2fa628a0c4eb4095a1e'}\n\n```{.r .cell-code .numberLines}\nQuest1_assets4  <-  merge(assets4, Questionnaire_1, all=TRUE, by = \"FSN\")\nstr(Quest1_assets4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t13377 obs. of  11 variables:\n $ FSN                    : int  45001 45002 45003 45004 45005 45006 45007 45008 45009 45010 ...\n $ asset_index            : chr  \"4\" \"3\" \"2\" \"1\" ...\n $ panchyat_id            : int  2 2 2 2 2 2 2 2 2 2 ...\n $ village_id             : int  11 11 11 11 11 11 11 11 11 11 ...\n $ ward_no                : int  1 1 1 1 1 1 1 1 1 1 ...\n $ household_no           : int  21 680 290 3390 181 3501 1401 2330 3750 2371 ...\n $ household_head_age     : int  50 35 60 35 40 40 60 23 25 40 ...\n $ household_head_sex     : int  2 2 2 2 2 2 2 2 2 3 ...\n $ household_head_religion: int  4 4 4 4 4 4 4 4 4 4 ...\n $ household_head_caste   : int  9 9 9 9 9 9 9 9 9 9 ...\n $ household_head_subcaste: chr  \"PASWAN\" \"PASWAN\" \"PASWAN\" \"PASWAN\" ...\n```\n:::\n:::\n\n7.3 Merging with animals\n\n::: {.cell hash='Data-Analysis-Wk2_cache/html/unnamed-chunk-29_89a310aa06105e35e35a2b0cf2f8839c'}\n\n```{.r .cell-code .numberLines}\nstr(animals)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t7147 obs. of  29 variables:\n $ FSN       : int  45001 45002 45003 45004 45006 45009 45021 45024 45025 45027 ...\n $ count_Goa : int  3 NA NA 2 NA 7 1 3 3 NA ...\n $ dist_Goa  : int  5 NA NA 5 NA 0 5 15 0 NA ...\n $ indor_Goa : int  1 NA NA 1 NA 1 1 1 1 NA ...\n $ daysin_Goa: int  120 NA NA 180 NA 360 150 90 90 NA ...\n $ count_Pou : int  1 NA NA NA NA NA NA NA NA 2 ...\n $ dist_Pou  : int  0 NA NA NA NA NA NA NA NA 0 ...\n $ indor_Pou : int  1 NA NA NA NA NA NA NA NA 1 ...\n $ daysin_Pou: int  365 NA NA NA NA NA NA NA NA 360 ...\n $ count_Buf : int  NA 1 NA NA NA NA NA NA NA NA ...\n $ dist_Buf  : int  NA 4 NA NA NA NA NA NA NA NA ...\n $ indor_Buf : int  NA 0 NA NA NA NA NA NA NA NA ...\n $ daysin_Buf: int  NA -1 NA NA NA NA NA NA NA NA ...\n $ count_Cow : int  NA NA 1 NA 2 NA 3 NA NA NA ...\n $ dist_Cow  : int  NA NA 3 NA 0 NA 15 NA NA NA ...\n $ indor_Cow : int  NA NA 1 NA 1 NA 0 NA NA NA ...\n $ daysin_Cow: int  NA NA 210 NA 360 NA -1 NA NA NA ...\n $ count_Pig : int  NA NA NA NA NA NA NA NA NA NA ...\n $ dist_Pig  : int  NA NA NA NA NA NA NA NA NA NA ...\n $ indor_Pig : int  NA NA NA NA NA NA NA NA NA NA ...\n $ daysin_Pig: int  NA NA NA NA NA NA NA NA NA NA ...\n $ count_Dog : int  NA NA NA NA NA NA NA NA NA NA ...\n $ dist_Dog  : int  NA NA NA NA NA NA NA NA NA NA ...\n $ indor_Dog : int  NA NA NA NA NA NA NA NA NA NA ...\n $ daysin_Dog: int  NA NA NA NA NA NA NA NA NA NA ...\n $ count_Oth : int  NA NA NA NA NA NA NA NA NA NA ...\n $ dist_Oth  : int  NA NA NA NA NA NA NA NA NA NA ...\n $ indor_Oth : int  NA NA NA NA NA NA NA NA NA NA ...\n $ daysin_Oth: int  NA NA NA NA NA NA NA NA NA NA ...\n - attr(*, \"reshapeWide\")=List of 5\n  ..$ v.names: chr [1:4] \"count\" \"dist\" \"indor\" \"daysin\"\n  ..$ timevar: chr \"anim\"\n  ..$ idvar  : chr \"FSN\"\n  ..$ times  : chr [1:7] \"Goa\" \"Pou\" \"Buf\" \"Cow\" ...\n  ..$ varying: chr [1:4, 1:7] \"count_Goa\" \"dist_Goa\" \"indor_Goa\" \"daysin_Goa\" ...\n```\n:::\n\n```{.r .cell-code .numberLines}\nstr(Quest1_assets4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t13377 obs. of  11 variables:\n $ FSN                    : int  45001 45002 45003 45004 45005 45006 45007 45008 45009 45010 ...\n $ asset_index            : chr  \"4\" \"3\" \"2\" \"1\" ...\n $ panchyat_id            : int  2 2 2 2 2 2 2 2 2 2 ...\n $ village_id             : int  11 11 11 11 11 11 11 11 11 11 ...\n $ ward_no                : int  1 1 1 1 1 1 1 1 1 1 ...\n $ household_no           : int  21 680 290 3390 181 3501 1401 2330 3750 2371 ...\n $ household_head_age     : int  50 35 60 35 40 40 60 23 25 40 ...\n $ household_head_sex     : int  2 2 2 2 2 2 2 2 2 3 ...\n $ household_head_religion: int  4 4 4 4 4 4 4 4 4 4 ...\n $ household_head_caste   : int  9 9 9 9 9 9 9 9 9 9 ...\n $ household_head_subcaste: chr  \"PASWAN\" \"PASWAN\" \"PASWAN\" \"PASWAN\" ...\n```\n:::\n\n```{.r .cell-code .numberLines}\nQuest1_assets4_animals <-  merge(Quest1_assets4, animals, all=TRUE, by = \"FSN\")\nstr(Quest1_assets4_animals)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t13377 obs. of  39 variables:\n $ FSN                    : int  45001 45002 45003 45004 45005 45006 45007 45008 45009 45010 ...\n $ asset_index            : chr  \"4\" \"3\" \"2\" \"1\" ...\n $ panchyat_id            : int  2 2 2 2 2 2 2 2 2 2 ...\n $ village_id             : int  11 11 11 11 11 11 11 11 11 11 ...\n $ ward_no                : int  1 1 1 1 1 1 1 1 1 1 ...\n $ household_no           : int  21 680 290 3390 181 3501 1401 2330 3750 2371 ...\n $ household_head_age     : int  50 35 60 35 40 40 60 23 25 40 ...\n $ household_head_sex     : int  2 2 2 2 2 2 2 2 2 3 ...\n $ household_head_religion: int  4 4 4 4 4 4 4 4 4 4 ...\n $ household_head_caste   : int  9 9 9 9 9 9 9 9 9 9 ...\n $ household_head_subcaste: chr  \"PASWAN\" \"PASWAN\" \"PASWAN\" \"PASWAN\" ...\n $ count_Goa              : int  3 NA NA 2 NA NA NA NA 7 NA ...\n $ dist_Goa               : int  5 NA NA 5 NA NA NA NA 0 NA ...\n $ indor_Goa              : int  1 NA NA 1 NA NA NA NA 1 NA ...\n $ daysin_Goa             : int  120 NA NA 180 NA NA NA NA 360 NA ...\n $ count_Pou              : int  1 NA NA NA NA NA NA NA NA NA ...\n $ dist_Pou               : int  0 NA NA NA NA NA NA NA NA NA ...\n $ indor_Pou              : int  1 NA NA NA NA NA NA NA NA NA ...\n $ daysin_Pou             : int  365 NA NA NA NA NA NA NA NA NA ...\n $ count_Buf              : int  NA 1 NA NA NA NA NA NA NA NA ...\n $ dist_Buf               : int  NA 4 NA NA NA NA NA NA NA NA ...\n $ indor_Buf              : int  NA 0 NA NA NA NA NA NA NA NA ...\n $ daysin_Buf             : int  NA -1 NA NA NA NA NA NA NA NA ...\n $ count_Cow              : int  NA NA 1 NA NA 2 NA NA NA NA ...\n $ dist_Cow               : int  NA NA 3 NA NA 0 NA NA NA NA ...\n $ indor_Cow              : int  NA NA 1 NA NA 1 NA NA NA NA ...\n $ daysin_Cow             : int  NA NA 210 NA NA 360 NA NA NA NA ...\n $ count_Pig              : int  NA NA NA NA NA NA NA NA NA NA ...\n $ dist_Pig               : int  NA NA NA NA NA NA NA NA NA NA ...\n $ indor_Pig              : int  NA NA NA NA NA NA NA NA NA NA ...\n $ daysin_Pig             : int  NA NA NA NA NA NA NA NA NA NA ...\n $ count_Dog              : int  NA NA NA NA NA NA NA NA NA NA ...\n $ dist_Dog               : int  NA NA NA NA NA NA NA NA NA NA ...\n $ indor_Dog              : int  NA NA NA NA NA NA NA NA NA NA ...\n $ daysin_Dog             : int  NA NA NA NA NA NA NA NA NA NA ...\n $ count_Oth              : int  NA NA NA NA NA NA NA NA NA NA ...\n $ dist_Oth               : int  NA NA NA NA NA NA NA NA NA NA ...\n $ indor_Oth              : int  NA NA NA NA NA NA NA NA NA NA ...\n $ daysin_Oth             : int  NA NA NA NA NA NA NA NA NA NA ...\n```\n:::\n\n```{.r .cell-code .numberLines}\n#View(Quest1_assets4_animals)\n```\n:::\n\n7.4 Changuing the NA to 0\n\n\n::: {.cell hash='Data-Analysis-Wk2_cache/html/unnamed-chunk-30_bf803a16faf44018bb146d172636affa'}\n\n:::\n\n\n#### 7. Merging with Q1_B\n\n::: {.cell hash='Data-Analysis-Wk2_cache/html/unnamed-chunk-31_cdf271335a7823e632ddbbf62ed564b5'}\n\n```{.r .cell-code .numberLines}\nQ1_B <- read.csv(\"C:/Users/pined/OneDrive - Universidad Nacional Mayor de San Marcos/Javier 2022/Belgica/AC2_DataAnalysis_ThWk/Material/Q1_B.csv\", sep=\",\", dec= \".\")\nstr(Q1_B)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t13377 obs. of  40 variables:\n $ ID                 : int  1 2 3 4 5 6 7 8 9 10 ...\n $ FSN                : num  45001 45002 45003 45004 45005 ...\n $ Neem_Tree          : num  0 0 0 0 0 0 0 0 0 0 ...\n $ Neem_Tree_Distance : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Size     : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Age      : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Usage    : chr  \"\" \"\" \"\" \"\" ...\n $ Neem_Tree_Use_Other: chr  \"\" \"\" \"\" \"\" ...\n $ Bamboo_Tree        : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Bamboo_Tree_Dist   : num  3 10 16 17 5 4 15 3 1 10 ...\n $ Banana_Tree        : num  0 0 0 0 0 0 0 1 1 0 ...\n $ Banana_Tree_Dist   : num  -1 -1 -1 -1 -1 -1 -1 5 1 -1 ...\n $ Rice_Field         : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Rice_Field_Dist    : num  4 12 16 13 4 13 10 10 7 12 ...\n $ Perm_Water_Body    : num  0 0 0 0 0 0 0 0 0 0 ...\n $ Perm_Wat_Body_Dist : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Wat_Body_Mid_Point : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ No_Mosquito_Net    : num  0 2 1 0 0 0 0 0 1 0 ...\n $ Sprayed_2010       : num  86 86 86 86 86 86 86 86 86 86 ...\n $ Sprayed_2009       : num  86 86 86 86 86 86 86 86 86 86 ...\n $ Floor_Material     : num  153 153 153 153 153 153 153 153 155 153 ...\n $ Other_Floor_Mat    : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Is_Floor_Damp      : num  1 1 1 1 1 1 1 1 0 1 ...\n $ Roof_Material      : num  161 159 158 156 156 156 156 158 158 156 ...\n $ Other_Roof_Material: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Wall_Material      : num  164 164 164 162 163 163 162 164 164 162 ...\n $ Other_Wall_Material: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Windows_in_Room    : num  1 1 1 0 0 0 0 1 1 0 ...\n $ Granaries_in_HH    : num  1 1 1 0 1 1 0 1 1 0 ...\n $ Source_Drink_Water : num  167 167 92 92 92 92 92 92 92 92 ...\n $ Other_Src_Drink_Wat: num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Toilet_Facility    : num  177 177 177 177 177 177 177 177 177 177 ...\n $ Other_Toilet_Fac   : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Cooking_Fuel       : num  180 180 180 180 180 180 180 180 180 180 ...\n $ Other_Cooking_Fuel : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Source_Light       : num  182 182 182 182 182 182 182 182 182 182 ...\n $ Other_Source_Light : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Electricity_in_HH  : num  0 0 0 0 0 0 0 0 0 0 ...\n $ No_Of_Rooms        : num  2 2 3 1 2 3 2 1 3 1 ...\n $ No_Sleeping_Rooms  : num  2 2 2 1 2 2 2 1 1 1 ...\n```\n:::\n\n```{.r .cell-code .numberLines}\n#Merge\nQuest1_assets4_animals_q1B <-  merge(Q1_B, Quest1_assets4_animals, all=TRUE, by = \"FSN\")\nstr(Quest1_assets4_animals_q1B)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t13377 obs. of  78 variables:\n $ FSN                    : num  45001 45002 45003 45004 45005 ...\n $ ID                     : int  1 2 3 4 5 6 7 8 9 10 ...\n $ Neem_Tree              : num  0 0 0 0 0 0 0 0 0 0 ...\n $ Neem_Tree_Distance     : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Size         : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Age          : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Usage        : chr  \"\" \"\" \"\" \"\" ...\n $ Neem_Tree_Use_Other    : chr  \"\" \"\" \"\" \"\" ...\n $ Bamboo_Tree            : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Bamboo_Tree_Dist       : num  3 10 16 17 5 4 15 3 1 10 ...\n $ Banana_Tree            : num  0 0 0 0 0 0 0 1 1 0 ...\n $ Banana_Tree_Dist       : num  -1 -1 -1 -1 -1 -1 -1 5 1 -1 ...\n $ Rice_Field             : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Rice_Field_Dist        : num  4 12 16 13 4 13 10 10 7 12 ...\n $ Perm_Water_Body        : num  0 0 0 0 0 0 0 0 0 0 ...\n $ Perm_Wat_Body_Dist     : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Wat_Body_Mid_Point     : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ No_Mosquito_Net        : num  0 2 1 0 0 0 0 0 1 0 ...\n $ Sprayed_2010           : num  86 86 86 86 86 86 86 86 86 86 ...\n $ Sprayed_2009           : num  86 86 86 86 86 86 86 86 86 86 ...\n $ Floor_Material         : num  153 153 153 153 153 153 153 153 155 153 ...\n $ Other_Floor_Mat        : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Is_Floor_Damp          : num  1 1 1 1 1 1 1 1 0 1 ...\n $ Roof_Material          : num  161 159 158 156 156 156 156 158 158 156 ...\n $ Other_Roof_Material    : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Wall_Material          : num  164 164 164 162 163 163 162 164 164 162 ...\n $ Other_Wall_Material    : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Windows_in_Room        : num  1 1 1 0 0 0 0 1 1 0 ...\n $ Granaries_in_HH        : num  1 1 1 0 1 1 0 1 1 0 ...\n $ Source_Drink_Water     : num  167 167 92 92 92 92 92 92 92 92 ...\n $ Other_Src_Drink_Wat    : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Toilet_Facility        : num  177 177 177 177 177 177 177 177 177 177 ...\n $ Other_Toilet_Fac       : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Cooking_Fuel           : num  180 180 180 180 180 180 180 180 180 180 ...\n $ Other_Cooking_Fuel     : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Source_Light           : num  182 182 182 182 182 182 182 182 182 182 ...\n $ Other_Source_Light     : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Electricity_in_HH      : num  0 0 0 0 0 0 0 0 0 0 ...\n $ No_Of_Rooms            : num  2 2 3 1 2 3 2 1 3 1 ...\n $ No_Sleeping_Rooms      : num  2 2 2 1 2 2 2 1 1 1 ...\n $ asset_index            : chr  \"4\" \"3\" \"2\" \"1\" ...\n $ panchyat_id            : int  2 2 2 2 2 2 2 2 2 2 ...\n $ village_id             : int  11 11 11 11 11 11 11 11 11 11 ...\n $ ward_no                : int  1 1 1 1 1 1 1 1 1 1 ...\n $ household_no           : int  21 680 290 3390 181 3501 1401 2330 3750 2371 ...\n $ household_head_age     : int  50 35 60 35 40 40 60 23 25 40 ...\n $ household_head_sex     : int  2 2 2 2 2 2 2 2 2 3 ...\n $ household_head_religion: int  4 4 4 4 4 4 4 4 4 4 ...\n $ household_head_caste   : int  9 9 9 9 9 9 9 9 9 9 ...\n $ household_head_subcaste: chr  \"PASWAN\" \"PASWAN\" \"PASWAN\" \"PASWAN\" ...\n $ count_Goa              : int  3 NA NA 2 NA NA NA NA 7 NA ...\n $ dist_Goa               : int  5 NA NA 5 NA NA NA NA 0 NA ...\n $ indor_Goa              : int  1 NA NA 1 NA NA NA NA 1 NA ...\n $ daysin_Goa             : int  120 NA NA 180 NA NA NA NA 360 NA ...\n $ count_Pou              : int  1 NA NA NA NA NA NA NA NA NA ...\n $ dist_Pou               : int  0 NA NA NA NA NA NA NA NA NA ...\n $ indor_Pou              : int  1 NA NA NA NA NA NA NA NA NA ...\n $ daysin_Pou             : int  365 NA NA NA NA NA NA NA NA NA ...\n $ count_Buf              : int  NA 1 NA NA NA NA NA NA NA NA ...\n $ dist_Buf               : int  NA 4 NA NA NA NA NA NA NA NA ...\n $ indor_Buf              : int  NA 0 NA NA NA NA NA NA NA NA ...\n $ daysin_Buf             : int  NA -1 NA NA NA NA NA NA NA NA ...\n $ count_Cow              : int  NA NA 1 NA NA 2 NA NA NA NA ...\n $ dist_Cow               : int  NA NA 3 NA NA 0 NA NA NA NA ...\n $ indor_Cow              : int  NA NA 1 NA NA 1 NA NA NA NA ...\n $ daysin_Cow             : int  NA NA 210 NA NA 360 NA NA NA NA ...\n $ count_Pig              : int  NA NA NA NA NA NA NA NA NA NA ...\n $ dist_Pig               : int  NA NA NA NA NA NA NA NA NA NA ...\n $ indor_Pig              : int  NA NA NA NA NA NA NA NA NA NA ...\n $ daysin_Pig             : int  NA NA NA NA NA NA NA NA NA NA ...\n $ count_Dog              : int  NA NA NA NA NA NA NA NA NA NA ...\n $ dist_Dog               : int  NA NA NA NA NA NA NA NA NA NA ...\n $ indor_Dog              : int  NA NA NA NA NA NA NA NA NA NA ...\n $ daysin_Dog             : int  NA NA NA NA NA NA NA NA NA NA ...\n $ count_Oth              : int  NA NA NA NA NA NA NA NA NA NA ...\n $ dist_Oth               : int  NA NA NA NA NA NA NA NA NA NA ...\n $ indor_Oth              : int  NA NA NA NA NA NA NA NA NA NA ...\n $ daysin_Oth             : int  NA NA NA NA NA NA NA NA NA NA ...\n```\n:::\n:::\n\n\n\n#### 8. Merging with data form persons\n8.1 Opening Q1_Screening.csv\n\n::: {.cell hash='Data-Analysis-Wk2_cache/html/unnamed-chunk-32_9a9f1f81b1054791b09386ad6a10d80f'}\n\n```{.r .cell-code .numberLines}\nQ1_Screening <- read.csv(\"C:/Users/pined/OneDrive - Universidad Nacional Mayor de San Marcos/Javier 2022/Belgica/AC2_DataAnalysis_ThWk/Material/Q1_Screening.csv\", sep=\",\", dec= \".\")\nstr(Q1_Screening)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t81214 obs. of  10 variables:\n $ FSN                         : int  45001 45001 45001 45001 45001 45001 45002 45002 45002 45002 ...\n $ member_id                   : int  1 2 3 4 5 6 1 2 3 4 ...\n $ member_age                  : int  50 48 25 22 0 11 35 33 17 15 ...\n $ member_sex                  : int  2 3 2 3 2 2 2 3 2 2 ...\n $ fever_gt_3_days             : int  0 0 0 0 0 0 0 0 0 0 ...\n $ suffered_vl_since_2nd_survey: int  0 0 0 0 0 0 0 0 0 0 ...\n $ date_diagnosis              : chr  \"\" \"\" \"\" \"\" ...\n $ treatment_place             : chr  \"-1\" \"-1\" \"-1\" \"-1\" ...\n $ current_status              : int  0 0 4 0 0 0 0 0 4 0 ...\n $ datedis                     : int  NA NA NA NA NA NA NA NA NA NA ...\n```\n:::\n:::\n\n\n8.2 Merging with the merged database of households\n\n::: {.cell hash='Data-Analysis-Wk2_cache/html/unnamed-chunk-33_646f615a992bed1e46444ad2cfea5a36'}\n\n```{.r .cell-code .numberLines}\nstr(Quest1_assets4_animals_q1B)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t13377 obs. of  78 variables:\n $ FSN                    : num  45001 45002 45003 45004 45005 ...\n $ ID                     : int  1 2 3 4 5 6 7 8 9 10 ...\n $ Neem_Tree              : num  0 0 0 0 0 0 0 0 0 0 ...\n $ Neem_Tree_Distance     : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Size         : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Age          : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Usage        : chr  \"\" \"\" \"\" \"\" ...\n $ Neem_Tree_Use_Other    : chr  \"\" \"\" \"\" \"\" ...\n $ Bamboo_Tree            : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Bamboo_Tree_Dist       : num  3 10 16 17 5 4 15 3 1 10 ...\n $ Banana_Tree            : num  0 0 0 0 0 0 0 1 1 0 ...\n $ Banana_Tree_Dist       : num  -1 -1 -1 -1 -1 -1 -1 5 1 -1 ...\n $ Rice_Field             : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Rice_Field_Dist        : num  4 12 16 13 4 13 10 10 7 12 ...\n $ Perm_Water_Body        : num  0 0 0 0 0 0 0 0 0 0 ...\n $ Perm_Wat_Body_Dist     : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Wat_Body_Mid_Point     : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ No_Mosquito_Net        : num  0 2 1 0 0 0 0 0 1 0 ...\n $ Sprayed_2010           : num  86 86 86 86 86 86 86 86 86 86 ...\n $ Sprayed_2009           : num  86 86 86 86 86 86 86 86 86 86 ...\n $ Floor_Material         : num  153 153 153 153 153 153 153 153 155 153 ...\n $ Other_Floor_Mat        : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Is_Floor_Damp          : num  1 1 1 1 1 1 1 1 0 1 ...\n $ Roof_Material          : num  161 159 158 156 156 156 156 158 158 156 ...\n $ Other_Roof_Material    : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Wall_Material          : num  164 164 164 162 163 163 162 164 164 162 ...\n $ Other_Wall_Material    : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Windows_in_Room        : num  1 1 1 0 0 0 0 1 1 0 ...\n $ Granaries_in_HH        : num  1 1 1 0 1 1 0 1 1 0 ...\n $ Source_Drink_Water     : num  167 167 92 92 92 92 92 92 92 92 ...\n $ Other_Src_Drink_Wat    : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Toilet_Facility        : num  177 177 177 177 177 177 177 177 177 177 ...\n $ Other_Toilet_Fac       : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Cooking_Fuel           : num  180 180 180 180 180 180 180 180 180 180 ...\n $ Other_Cooking_Fuel     : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Source_Light           : num  182 182 182 182 182 182 182 182 182 182 ...\n $ Other_Source_Light     : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Electricity_in_HH      : num  0 0 0 0 0 0 0 0 0 0 ...\n $ No_Of_Rooms            : num  2 2 3 1 2 3 2 1 3 1 ...\n $ No_Sleeping_Rooms      : num  2 2 2 1 2 2 2 1 1 1 ...\n $ asset_index            : chr  \"4\" \"3\" \"2\" \"1\" ...\n $ panchyat_id            : int  2 2 2 2 2 2 2 2 2 2 ...\n $ village_id             : int  11 11 11 11 11 11 11 11 11 11 ...\n $ ward_no                : int  1 1 1 1 1 1 1 1 1 1 ...\n $ household_no           : int  21 680 290 3390 181 3501 1401 2330 3750 2371 ...\n $ household_head_age     : int  50 35 60 35 40 40 60 23 25 40 ...\n $ household_head_sex     : int  2 2 2 2 2 2 2 2 2 3 ...\n $ household_head_religion: int  4 4 4 4 4 4 4 4 4 4 ...\n $ household_head_caste   : int  9 9 9 9 9 9 9 9 9 9 ...\n $ household_head_subcaste: chr  \"PASWAN\" \"PASWAN\" \"PASWAN\" \"PASWAN\" ...\n $ count_Goa              : int  3 NA NA 2 NA NA NA NA 7 NA ...\n $ dist_Goa               : int  5 NA NA 5 NA NA NA NA 0 NA ...\n $ indor_Goa              : int  1 NA NA 1 NA NA NA NA 1 NA ...\n $ daysin_Goa             : int  120 NA NA 180 NA NA NA NA 360 NA ...\n $ count_Pou              : int  1 NA NA NA NA NA NA NA NA NA ...\n $ dist_Pou               : int  0 NA NA NA NA NA NA NA NA NA ...\n $ indor_Pou              : int  1 NA NA NA NA NA NA NA NA NA ...\n $ daysin_Pou             : int  365 NA NA NA NA NA NA NA NA NA ...\n $ count_Buf              : int  NA 1 NA NA NA NA NA NA NA NA ...\n $ dist_Buf               : int  NA 4 NA NA NA NA NA NA NA NA ...\n $ indor_Buf              : int  NA 0 NA NA NA NA NA NA NA NA ...\n $ daysin_Buf             : int  NA -1 NA NA NA NA NA NA NA NA ...\n $ count_Cow              : int  NA NA 1 NA NA 2 NA NA NA NA ...\n $ dist_Cow               : int  NA NA 3 NA NA 0 NA NA NA NA ...\n $ indor_Cow              : int  NA NA 1 NA NA 1 NA NA NA NA ...\n $ daysin_Cow             : int  NA NA 210 NA NA 360 NA NA NA NA ...\n $ count_Pig              : int  NA NA NA NA NA NA NA NA NA NA ...\n $ dist_Pig               : int  NA NA NA NA NA NA NA NA NA NA ...\n $ indor_Pig              : int  NA NA NA NA NA NA NA NA NA NA ...\n $ daysin_Pig             : int  NA NA NA NA NA NA NA NA NA NA ...\n $ count_Dog              : int  NA NA NA NA NA NA NA NA NA NA ...\n $ dist_Dog               : int  NA NA NA NA NA NA NA NA NA NA ...\n $ indor_Dog              : int  NA NA NA NA NA NA NA NA NA NA ...\n $ daysin_Dog             : int  NA NA NA NA NA NA NA NA NA NA ...\n $ count_Oth              : int  NA NA NA NA NA NA NA NA NA NA ...\n $ dist_Oth               : int  NA NA NA NA NA NA NA NA NA NA ...\n $ indor_Oth              : int  NA NA NA NA NA NA NA NA NA NA ...\n $ daysin_Oth             : int  NA NA NA NA NA NA NA NA NA NA ...\n```\n:::\n\n```{.r .cell-code .numberLines}\nstr(Q1_Screening)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t81214 obs. of  10 variables:\n $ FSN                         : int  45001 45001 45001 45001 45001 45001 45002 45002 45002 45002 ...\n $ member_id                   : int  1 2 3 4 5 6 1 2 3 4 ...\n $ member_age                  : int  50 48 25 22 0 11 35 33 17 15 ...\n $ member_sex                  : int  2 3 2 3 2 2 2 3 2 2 ...\n $ fever_gt_3_days             : int  0 0 0 0 0 0 0 0 0 0 ...\n $ suffered_vl_since_2nd_survey: int  0 0 0 0 0 0 0 0 0 0 ...\n $ date_diagnosis              : chr  \"\" \"\" \"\" \"\" ...\n $ treatment_place             : chr  \"-1\" \"-1\" \"-1\" \"-1\" ...\n $ current_status              : int  0 0 4 0 0 0 0 0 4 0 ...\n $ datedis                     : int  NA NA NA NA NA NA NA NA NA NA ...\n```\n:::\n\n```{.r .cell-code .numberLines}\n#Merge\nQuest1_assets4_animals_q1B_Persons <-  merge(Q1_Screening, Quest1_assets4_animals_q1B, all=TRUE, by = \"FSN\")\nstr(Quest1_assets4_animals_q1B_Persons)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t81214 obs. of  87 variables:\n $ FSN                         : int  45001 45001 45001 45001 45001 45001 45002 45002 45002 45002 ...\n $ member_id                   : int  1 2 3 4 5 6 1 2 3 4 ...\n $ member_age                  : int  50 48 25 22 0 11 35 33 17 15 ...\n $ member_sex                  : int  2 3 2 3 2 2 2 3 2 2 ...\n $ fever_gt_3_days             : int  0 0 0 0 0 0 0 0 0 0 ...\n $ suffered_vl_since_2nd_survey: int  0 0 0 0 0 0 0 0 0 0 ...\n $ date_diagnosis              : chr  \"\" \"\" \"\" \"\" ...\n $ treatment_place             : chr  \"-1\" \"-1\" \"-1\" \"-1\" ...\n $ current_status              : int  0 0 4 0 0 0 0 0 4 0 ...\n $ datedis                     : int  NA NA NA NA NA NA NA NA NA NA ...\n $ ID                          : int  1 1 1 1 1 1 2 2 2 2 ...\n $ Neem_Tree                   : num  0 0 0 0 0 0 0 0 0 0 ...\n $ Neem_Tree_Distance          : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Size              : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Age               : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Neem_Tree_Usage             : chr  \"\" \"\" \"\" \"\" ...\n $ Neem_Tree_Use_Other         : chr  \"\" \"\" \"\" \"\" ...\n $ Bamboo_Tree                 : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Bamboo_Tree_Dist            : num  3 3 3 3 3 3 10 10 10 10 ...\n $ Banana_Tree                 : num  0 0 0 0 0 0 0 0 0 0 ...\n $ Banana_Tree_Dist            : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Rice_Field                  : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Rice_Field_Dist             : num  4 4 4 4 4 4 12 12 12 12 ...\n $ Perm_Water_Body             : num  0 0 0 0 0 0 0 0 0 0 ...\n $ Perm_Wat_Body_Dist          : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Wat_Body_Mid_Point          : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ No_Mosquito_Net             : num  0 0 0 0 0 0 2 2 2 2 ...\n $ Sprayed_2010                : num  86 86 86 86 86 86 86 86 86 86 ...\n $ Sprayed_2009                : num  86 86 86 86 86 86 86 86 86 86 ...\n $ Floor_Material              : num  153 153 153 153 153 153 153 153 153 153 ...\n $ Other_Floor_Mat             : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Is_Floor_Damp               : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Roof_Material               : num  161 161 161 161 161 161 159 159 159 159 ...\n $ Other_Roof_Material         : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Wall_Material               : num  164 164 164 164 164 164 164 164 164 164 ...\n $ Other_Wall_Material         : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Windows_in_Room             : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Granaries_in_HH             : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Source_Drink_Water          : num  167 167 167 167 167 167 167 167 167 167 ...\n $ Other_Src_Drink_Wat         : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Toilet_Facility             : num  177 177 177 177 177 177 177 177 177 177 ...\n $ Other_Toilet_Fac            : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Cooking_Fuel                : num  180 180 180 180 180 180 180 180 180 180 ...\n $ Other_Cooking_Fuel          : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Source_Light                : num  182 182 182 182 182 182 182 182 182 182 ...\n $ Other_Source_Light          : num  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Electricity_in_HH           : num  0 0 0 0 0 0 0 0 0 0 ...\n $ No_Of_Rooms                 : num  2 2 2 2 2 2 2 2 2 2 ...\n $ No_Sleeping_Rooms           : num  2 2 2 2 2 2 2 2 2 2 ...\n $ asset_index                 : chr  \"4\" \"4\" \"4\" \"4\" ...\n $ panchyat_id                 : int  2 2 2 2 2 2 2 2 2 2 ...\n $ village_id                  : int  11 11 11 11 11 11 11 11 11 11 ...\n $ ward_no                     : int  1 1 1 1 1 1 1 1 1 1 ...\n $ household_no                : int  21 21 21 21 21 21 680 680 680 680 ...\n $ household_head_age          : int  50 50 50 50 50 50 35 35 35 35 ...\n $ household_head_sex          : int  2 2 2 2 2 2 2 2 2 2 ...\n $ household_head_religion     : int  4 4 4 4 4 4 4 4 4 4 ...\n $ household_head_caste        : int  9 9 9 9 9 9 9 9 9 9 ...\n $ household_head_subcaste     : chr  \"PASWAN\" \"PASWAN\" \"PASWAN\" \"PASWAN\" ...\n $ count_Goa                   : int  3 3 3 3 3 3 NA NA NA NA ...\n $ dist_Goa                    : int  5 5 5 5 5 5 NA NA NA NA ...\n $ indor_Goa                   : int  1 1 1 1 1 1 NA NA NA NA ...\n $ daysin_Goa                  : int  120 120 120 120 120 120 NA NA NA NA ...\n $ count_Pou                   : int  1 1 1 1 1 1 NA NA NA NA ...\n $ dist_Pou                    : int  0 0 0 0 0 0 NA NA NA NA ...\n $ indor_Pou                   : int  1 1 1 1 1 1 NA NA NA NA ...\n $ daysin_Pou                  : int  365 365 365 365 365 365 NA NA NA NA ...\n $ count_Buf                   : int  NA NA NA NA NA NA 1 1 1 1 ...\n $ dist_Buf                    : int  NA NA NA NA NA NA 4 4 4 4 ...\n $ indor_Buf                   : int  NA NA NA NA NA NA 0 0 0 0 ...\n $ daysin_Buf                  : int  NA NA NA NA NA NA -1 -1 -1 -1 ...\n $ count_Cow                   : int  NA NA NA NA NA NA NA NA NA NA ...\n $ dist_Cow                    : int  NA NA NA NA NA NA NA NA NA NA ...\n $ indor_Cow                   : int  NA NA NA NA NA NA NA NA NA NA ...\n $ daysin_Cow                  : int  NA NA NA NA NA NA NA NA NA NA ...\n $ count_Pig                   : int  NA NA NA NA NA NA NA NA NA NA ...\n $ dist_Pig                    : int  NA NA NA NA NA NA NA NA NA NA ...\n $ indor_Pig                   : int  NA NA NA NA NA NA NA NA NA NA ...\n $ daysin_Pig                  : int  NA NA NA NA NA NA NA NA NA NA ...\n $ count_Dog                   : int  NA NA NA NA NA NA NA NA NA NA ...\n $ dist_Dog                    : int  NA NA NA NA NA NA NA NA NA NA ...\n $ indor_Dog                   : int  NA NA NA NA NA NA NA NA NA NA ...\n $ daysin_Dog                  : int  NA NA NA NA NA NA NA NA NA NA ...\n $ count_Oth                   : int  NA NA NA NA NA NA NA NA NA NA ...\n $ dist_Oth                    : int  NA NA NA NA NA NA NA NA NA NA ...\n $ indor_Oth                   : int  NA NA NA NA NA NA NA NA NA NA ...\n $ daysin_Oth                  : int  NA NA NA NA NA NA NA NA NA NA ...\n```\n:::\n:::\n\n\n8.3 Make the final dataset with the variables that i need\n\n\n::: {.cell hash='Data-Analysis-Wk2_cache/html/unnamed-chunk-34_bb3e6426f580604854da737d9a38e989'}\n\n```{.r .cell-code .numberLines}\nfinal_dataset  <- subset(Quest1_assets4_animals_q1B_Persons, select=c(\n  FSN, asset_index, Bamboo_Tree, Banana_Tree, Cooking_Fuel, Floor_Material, Granaries_in_HH, household_head_subcaste, indor_Buf, indor_Cow, indor_Pou, indor_Goa, count_Cow, count_Buf, count_Goa, count_Pou, Is_Floor_Damp, member_age, member_sex, Neem_Tree, No_Mosquito_Net, Perm_Water_Body, Rice_Field, Roof_Material, Sprayed_2009, Sprayed_2010, suffered_vl_since_2nd_survey, Wall_Material, Windows_in_Room\n))\n\nstr(final_dataset)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t81214 obs. of  29 variables:\n $ FSN                         : int  45001 45001 45001 45001 45001 45001 45002 45002 45002 45002 ...\n $ asset_index                 : chr  \"4\" \"4\" \"4\" \"4\" ...\n $ Bamboo_Tree                 : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Banana_Tree                 : num  0 0 0 0 0 0 0 0 0 0 ...\n $ Cooking_Fuel                : num  180 180 180 180 180 180 180 180 180 180 ...\n $ Floor_Material              : num  153 153 153 153 153 153 153 153 153 153 ...\n $ Granaries_in_HH             : num  1 1 1 1 1 1 1 1 1 1 ...\n $ household_head_subcaste     : chr  \"PASWAN\" \"PASWAN\" \"PASWAN\" \"PASWAN\" ...\n $ indor_Buf                   : int  NA NA NA NA NA NA 0 0 0 0 ...\n $ indor_Cow                   : int  NA NA NA NA NA NA NA NA NA NA ...\n $ indor_Pou                   : int  1 1 1 1 1 1 NA NA NA NA ...\n $ indor_Goa                   : int  1 1 1 1 1 1 NA NA NA NA ...\n $ count_Cow                   : int  NA NA NA NA NA NA NA NA NA NA ...\n $ count_Buf                   : int  NA NA NA NA NA NA 1 1 1 1 ...\n $ count_Goa                   : int  3 3 3 3 3 3 NA NA NA NA ...\n $ count_Pou                   : int  1 1 1 1 1 1 NA NA NA NA ...\n $ Is_Floor_Damp               : num  1 1 1 1 1 1 1 1 1 1 ...\n $ member_age                  : int  50 48 25 22 0 11 35 33 17 15 ...\n $ member_sex                  : int  2 3 2 3 2 2 2 3 2 2 ...\n $ Neem_Tree                   : num  0 0 0 0 0 0 0 0 0 0 ...\n $ No_Mosquito_Net             : num  0 0 0 0 0 0 2 2 2 2 ...\n $ Perm_Water_Body             : num  0 0 0 0 0 0 0 0 0 0 ...\n $ Rice_Field                  : num  1 1 1 1 1 1 1 1 1 1 ...\n $ Roof_Material               : num  161 161 161 161 161 161 159 159 159 159 ...\n $ Sprayed_2009                : num  86 86 86 86 86 86 86 86 86 86 ...\n $ Sprayed_2010                : num  86 86 86 86 86 86 86 86 86 86 ...\n $ suffered_vl_since_2nd_survey: int  0 0 0 0 0 0 0 0 0 0 ...\n $ Wall_Material               : num  164 164 164 164 164 164 164 164 164 164 ...\n $ Windows_in_Room             : num  1 1 1 1 1 1 1 1 1 1 ...\n```\n:::\n:::\n\n::: {.cell hash='Data-Analysis-Wk2_cache/html/unnamed-chunk-35_3e261dd90921f0186d680ae1d36314e3'}\n\n```{.r .cell-code .numberLines}\nsaveRDS(final_dataset, \"final_dataset.RDS\")\n```\n:::\n\n\n\n\n#### 9. Exploring the dataset\n\n::: {.cell hash='Data-Analysis-Wk2_cache/html/unnamed-chunk-36_8dc7649a59ca9de06cd30181792167bf'}\n\n```{.r .cell-code .numberLines}\ntable(final_dataset$suffered_vl_since_2nd_survey, useNA=\"always\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n    0     1  <NA> \n81007   207     0 \n```\n:::\n\n```{.r .cell-code .numberLines}\nfinal_dataset$case <- final_dataset$suffered_vl_since_2nd_survey\n\ntable(final_dataset$case, useNA=\"always\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n    0     1  <NA> \n81007   207     0 \n```\n:::\n:::\n\n\n\n\n### Asociations exploring\n\n::: {.cell hash='Data-Analysis-Wk2_cache/html/unnamed-chunk-37_930352507f17b2b2440e54a6a0cde179'}\n\n```{.r .cell-code .numberLines}\ntable(final_dataset$Banana_Tree, final_dataset$case, useNA=\"always\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n      \n           0     1  <NA>\n  0    11422    43     0\n  1    69585   164     0\n  <NA>     0     0     0\n```\n:::\n:::\n\n::: {.cell hash='Data-Analysis-Wk2_cache/html/unnamed-chunk-38_22af36f5af958ead8023d44356732860'}\n\n```{.r .cell-code .numberLines}\n#OR Banana Tree\n(164*11422) / (43*69585)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.6260398\n```\n:::\n:::\n\n\nOR- having Banana Trees = 0.62. \nSeems a protect effect\n\n\n\n::: {.cell hash='Data-Analysis-Wk2_cache/html/unnamed-chunk-39_5a3dd7712e3bf4d92edc23543b578870'}\n\n```{.r .cell-code .numberLines}\ntable(final_dataset$asset_index, final_dataset$case, useNA=\"always\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n      \n           0     1  <NA>\n  1    15354    56     0\n  2    12874    60     0\n  3    15777    36     0\n  4    17274    38     0\n  5    19728    17     0\n  <NA>     0     0     0\n```\n:::\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}