{
  "hash": "e19cc49c924f34639551a595e1a30b00",
  "result": {
    "markdown": "---\ntitle: \"Data Analysis Wk2\"\nformat: \n  html:\n    self-contained: true\n    code-line-numbers: true\n  pdf: \n    documentclass: article\ncustom_title_page: false\nfilters:\n  - lightbox\nlightbox: auto\n---\n\n---\nsubtitle: \"Data Analysis Week - Session 1\"\ndate: 2023-02-27\n\nauthor:\n  - name: Javier Silva-Valencia\n    orcid: 0000-0002-5982-2821\n    email: javier.silva@unmsm.edu.pe\n    affiliations:\n      - name: Instituut Voor Tropische Geneeskunde. Antwerp-Belgium\n\nlanguage: \n  title-block-author-single: \"Writer\"\n  \nabstract: Today we are going to create an index/score. For this we have a lot of variables of socioeconomical aspects and we are going to clean and select the ones we are going to use to create the index/score\n---\n\n\n\n------------------------------------------------------------------------\n\n------------------------------------------------------------------------\n\n\n### Exercise 1\n\n#### 0. Import CSV\n\n0.1 Set working directory: We are not going to do it now, but this is useful to say to R that all the files we are going to work is that one directory.\n\n0.2 Importing the CSV database under the name of Q1_B_106, with \",\" as separator, and with \".\" as decimal:\n\n\n\n::: {.cell hash='Data-Analysis-Wk2_cache/pdf/unnamed-chunk-1_8886f264ab81109d57325ba009ca4760'}\n\n```{.r .cell-code .numberLines}\nQ1_B_106 <- read.csv(\"C:/Users/pined/OneDrive - Universidad Nacional Mayor de San Marcos/Javier 2022/Belgica/AC2_DataAnalysis_ThWk/Material/Q1_B_106.csv\", sep=\",\", dec= \".\")\n```\n:::\n\n\n\n\n#### 1. Cleaning the dataset\n\n1.1 Seeing the structure of the dataset\n\n\n::: {.cell hash='Data-Analysis-Wk2_cache/pdf/unnamed-chunk-2_4e539ce0ee26e15a470c2ef2f7bcca65'}\n\n```{.r .cell-code .numberLines}\nstr(Q1_B_106)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t13377 obs. of  25 variables:\n $ FSN             : int  45001 45002 45003 45004 45005 45006 45007 45008 45009 45010 ...\n $ Radio           : int  1 1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ CD_Player       : int  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ BW_Television   : int  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Color_Television: int  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Video_DVD_Player: int  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Mobile          : int  -1 -1 -1 -1 -1 1 -1 -1 -1 -1 ...\n $ Non_Mobile_Phone: int  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Refrigerator    : int  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Iron            : int  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Sewing_Machine  : int  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Watch           : int  -1 -1 -1 -1 -1 1 -1 -1 -1 -1 ...\n $ Pressure_Cooker : int  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Chairs          : int  1 -1 -1 -1 1 1 -1 -1 2 -1 ...\n $ Sofas           : int  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Tables          : int  -1 -1 -1 -1 -1 1 -1 -1 -1 -1 ...\n $ Cot_Bed         : int  2 2 3 -1 2 1 2 1 2 -1 ...\n $ Cupboards       : int  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Bicycle         : int  1 1 1 -1 -1 2 -1 -1 1 -1 ...\n $ Motor_Cycle     : int  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Animal_Draw_Cart: int  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Car             : int  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Tractor         : int  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Computer        : int  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n $ Electric_Fan    : int  -1 -1 -1 -1 -1 -1 -1 -1 -1 -1 ...\n```\n:::\n:::\n\n\n\n::: callout-tip\nAccording to diccionary\n\n-1 : Missing or not available\n\n0, 1, 2, 3 : Number of items they have\n::: \n\n\n\n\n::: {.cell hash='Data-Analysis-Wk2_cache/pdf/unnamed-chunk-3_d28e3ced93a6634bbb38c51d95b8b2c8'}\n\n```{.r .cell-code .numberLines}\nsummary(Q1_B_106)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n      FSN            Radio           CD_Player       BW_Television    \n Min.   :45001   Min.   :-1.0000   Min.   :-1.0000   Min.   :-1.0000  \n 1st Qu.:48527   1st Qu.:-1.0000   1st Qu.:-1.0000   1st Qu.:-1.0000  \n Median :52032   Median :-1.0000   Median :-1.0000   Median :-1.0000  \n Mean   :52110   Mean   :-0.7555   Mean   :-0.9517   Mean   :-0.9015  \n 3rd Qu.:55671   3rd Qu.:-1.0000   3rd Qu.:-1.0000   3rd Qu.:-1.0000  \n Max.   :59606   Max.   : 6.0000   Max.   : 3.0000   Max.   : 2.0000  \n Color_Television  Video_DVD_Player      Mobile         Non_Mobile_Phone \n Min.   :-1.0000   Min.   :-1.0000   Min.   :-1.00000   Min.   :-1.0000  \n 1st Qu.:-1.0000   1st Qu.:-1.0000   1st Qu.:-1.00000   1st Qu.:-1.0000  \n Median :-1.0000   Median :-1.0000   Median :-1.00000   Median :-1.0000  \n Mean   :-0.9217   Mean   :-0.9785   Mean   : 0.01323   Mean   :-0.9885  \n 3rd Qu.:-1.0000   3rd Qu.:-1.0000   3rd Qu.: 1.00000   3rd Qu.:-1.0000  \n Max.   : 2.0000   Max.   : 1.0000   Max.   :10.00000   Max.   : 1.0000  \n  Refrigerator          Iron         Sewing_Machine        Watch        \n Min.   :-1.0000   Min.   :-1.0000   Min.   :-1.0000   Min.   :-1.0000  \n 1st Qu.:-1.0000   1st Qu.:-1.0000   1st Qu.:-1.0000   1st Qu.:-1.0000  \n Median :-1.0000   Median :-1.0000   Median :-1.0000   Median :-1.0000  \n Mean   :-0.9937   Mean   :-0.9415   Mean   :-0.8969   Mean   :-0.3998  \n 3rd Qu.:-1.0000   3rd Qu.:-1.0000   3rd Qu.:-1.0000   3rd Qu.: 1.0000  \n Max.   : 1.0000   Max.   : 4.0000   Max.   : 3.0000   Max.   :12.0000  \n Pressure_Cooker       Chairs            Sofas             Tables       \n Min.   :-1.0000   Min.   :-1.0000   Min.   :-1.0000   Min.   :-1.0000  \n 1st Qu.:-1.0000   1st Qu.:-1.0000   1st Qu.:-1.0000   1st Qu.:-1.0000  \n Median :-1.0000   Median :-1.0000   Median :-1.0000   Median :-1.0000  \n Mean   :-0.8435   Mean   : 0.4572   Mean   :-0.9602   Mean   :-0.2501  \n 3rd Qu.:-1.0000   3rd Qu.: 2.0000   3rd Qu.:-1.0000   3rd Qu.: 1.0000  \n Max.   : 5.0000   Max.   :40.0000   Max.   : 8.0000   Max.   :10.0000  \n    Cot_Bed         Cupboards          Bicycle          Motor_Cycle     \n Min.   :-1.000   Min.   :-1.0000   Min.   :-1.00000   Min.   :-1.0000  \n 1st Qu.: 2.000   1st Qu.:-1.0000   1st Qu.:-1.00000   1st Qu.:-1.0000  \n Median : 2.000   Median :-1.0000   Median : 1.00000   Median :-1.0000  \n Mean   : 2.599   Mean   :-0.9624   Mean   : 0.09793   Mean   :-0.8656  \n 3rd Qu.: 3.000   3rd Qu.:-1.0000   3rd Qu.: 1.00000   3rd Qu.:-1.0000  \n Max.   :24.000   Max.   : 7.0000   Max.   : 6.00000   Max.   : 5.0000  \n Animal_Draw_Cart       Car             Tractor           Computer      \n Min.   :-1.0000   Min.   :-1.0000   Min.   :-1.0000   Min.   :-1.0000  \n 1st Qu.:-1.0000   1st Qu.:-1.0000   1st Qu.:-1.0000   1st Qu.:-1.0000  \n Median :-1.0000   Median :-1.0000   Median :-1.0000   Median :-1.0000  \n Mean   :-0.9919   Mean   :-0.9938   Mean   :-0.9874   Mean   :-0.9982  \n 3rd Qu.:-1.0000   3rd Qu.:-1.0000   3rd Qu.:-1.0000   3rd Qu.:-1.0000  \n Max.   : 1.0000   Max.   : 2.0000   Max.   : 3.0000   Max.   : 1.0000  \n  Electric_Fan    \n Min.   :-1.0000  \n 1st Qu.:-1.0000  \n Median :-1.0000  \n Mean   :-0.6872  \n 3rd Qu.:-1.0000  \n Max.   :11.0000  \n```\n:::\n:::\n\n\n::: callout-tip\nExample of what we can see: The maximum number of radios in a household is 6\n::: \n\n#### 2. Replace values\n\n2.1 We need that all ‘-1’  be converting to ‘0’ \n\nand all value more than ‘≥ 1’ be converting to ‘1’\n\n\n\n::: {.cell hash='Data-Analysis-Wk2_cache/pdf/unnamed-chunk-4_eee176cc1c69f3c581c7da65d3bfcd30'}\n\n```{.r .cell-code .numberLines}\n#We can do it by using \"if else\":\nQ1_B_106$own_Radio <- ifelse(Q1_B_106$Radio>0,1,0)\n\n\n#But other way is: \n#Q1_B_106$own_Radio <- as.numeric(Q1_B_106$Radio > 0)\n#Ask to create a variable called \"own_Radio\" only TRUE when \"Radio\" is more than 0 and converting that into a number (as.numeric) (1:true,0:false)\n\n\n#Checking if it works\ntable(Q1_B_106$own_Radio, Q1_B_106$Radio, useNA = \"always\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n      \n          -1     1     2     3     6  <NA>\n  0    11753     0     0     0     0     0\n  1        0  1608    12     3     1     0\n  <NA>     0     0     0     0     0     0\n```\n:::\n\n```{.r .cell-code .numberLines}\nsummary(Q1_B_106$own_Radio)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max. \n 0.0000  0.0000  0.0000  0.1214  0.0000  1.0000 \n```\n:::\n:::\n\n\nWe need to do that for every variable\n\n\n\n::: {.cell hash='Data-Analysis-Wk2_cache/pdf/unnamed-chunk-5_2b91d8a2b84c7c7673fbb56f7901ecac'}\n\n```{.r .cell-code .numberLines}\nQ1_B_106$own_Radio <- ifelse(Q1_B_106$Radio>0,1,0)\nQ1_B_106$own_CD_Player <- ifelse(Q1_B_106$CD_Player>0,1,0)\nQ1_B_106$own_BW_Television <- ifelse(Q1_B_106$BW_Television>0,1,0)\nQ1_B_106$own_Color_Television <- ifelse(Q1_B_106$Color_Television>0,1,0)\nQ1_B_106$own_Video_DVD_Player <- ifelse(Q1_B_106$Video_DVD_Player>0,1,0)\nQ1_B_106$own_Mobile <- ifelse(Q1_B_106$Mobile>0,1,0)\nQ1_B_106$own_Non_Mobile_Phone <- ifelse(Q1_B_106$Non_Mobile_Phone>0,1,0)\nQ1_B_106$own_Refrigerator <- ifelse(Q1_B_106$Refrigerator>0,1,0)\nQ1_B_106$own_Iron <- ifelse(Q1_B_106$Iron>0,1,0)\nQ1_B_106$own_Sewing_Machine <- ifelse(Q1_B_106$Sewing_Machine>0,1,0)\nQ1_B_106$own_Watch <- ifelse(Q1_B_106$Watch>0,1,0)\nQ1_B_106$own_Pressure_Cooker <- ifelse(Q1_B_106$Pressure_Cooker>0,1,0)\nQ1_B_106$own_Chairs <- ifelse(Q1_B_106$Chairs>0,1,0)\nQ1_B_106$own_Sofas <- ifelse(Q1_B_106$Sofas>0,1,0)\nQ1_B_106$own_Tables <- ifelse(Q1_B_106$Tables>0,1,0)\nQ1_B_106$own_Cot_Bed <- ifelse(Q1_B_106$Cot_Bed>0,1,0)\nQ1_B_106$own_Cupboards <- ifelse(Q1_B_106$Cupboards>0,1,0)\nQ1_B_106$own_Bicycle <- ifelse(Q1_B_106$Bicycle>0,1,0)\nQ1_B_106$own_Motor_Cycle <- ifelse(Q1_B_106$Motor_Cycle>0,1,0)\nQ1_B_106$own_Animal_Draw_Cart <- ifelse(Q1_B_106$Animal_Draw_Cart>0,1,0)\nQ1_B_106$own_Car <- ifelse(Q1_B_106$Car>0,1,0)\nQ1_B_106$own_Tractor <- ifelse(Q1_B_106$Tractor>0,1,0)\nQ1_B_106$own_Computer <- ifelse(Q1_B_106$Computer>0,1,0)\nQ1_B_106$own_Electric_Fan <- ifelse(Q1_B_106$Electric_Fan>0,1,0)\n```\n:::\n\n\n\n\n2.2 Now we will make a subset containing only the ‘own’ variables and  FSN\n\n\n::: {.cell hash='Data-Analysis-Wk2_cache/pdf/unnamed-chunk-6_5aada23e613cd1ed47df05af5bb6196c'}\n\n```{.r .cell-code .numberLines}\nassets <- subset(Q1_B_106, select = grepl(\"own|FSN\", names(Q1_B_106)))\nstr(assets)  \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t13377 obs. of  25 variables:\n $ FSN                 : int  45001 45002 45003 45004 45005 45006 45007 45008 45009 45010 ...\n $ own_Radio           : num  1 1 0 0 0 0 0 0 0 0 ...\n $ own_CD_Player       : num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_BW_Television   : num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Color_Television: num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Video_DVD_Player: num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Mobile          : num  0 0 0 0 0 1 0 0 0 0 ...\n $ own_Non_Mobile_Phone: num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Refrigerator    : num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Iron            : num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Sewing_Machine  : num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Watch           : num  0 0 0 0 0 1 0 0 0 0 ...\n $ own_Pressure_Cooker : num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Chairs          : num  1 0 0 0 1 1 0 0 1 0 ...\n $ own_Sofas           : num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Tables          : num  0 0 0 0 0 1 0 0 0 0 ...\n $ own_Cot_Bed         : num  1 1 1 0 1 1 1 1 1 0 ...\n $ own_Cupboards       : num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Bicycle         : num  1 1 1 0 0 1 0 0 1 0 ...\n $ own_Motor_Cycle     : num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Animal_Draw_Cart: num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Car             : num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Tractor         : num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Computer        : num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Electric_Fan    : num  0 0 0 0 0 0 0 0 0 0 ...\n```\n:::\n:::\n\n\n\n2.3 Now we will focus only in those variables whose mean have a value between 5-95% (0.05-0.95)\n\nwhy?: Dont know, I need to ask for that\n\n\n\n::: {.cell hash='Data-Analysis-Wk2_cache/pdf/unnamed-chunk-7_00602f3226564dfcd43f5fd4615e8580'}\n\n```{.r .cell-code .numberLines}\n#summary(assets)\nround(sapply(assets, FUN=mean),3)   #To display the mean of each variable with 3 decimals\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                 FSN            own_Radio        own_CD_Player \n           52110.000                0.121                0.024 \n   own_BW_Television own_Color_Television own_Video_DVD_Player \n               0.049                0.039                0.011 \n          own_Mobile own_Non_Mobile_Phone     own_Refrigerator \n               0.476                0.006                0.003 \n            own_Iron   own_Sewing_Machine            own_Watch \n               0.028                0.051                0.264 \n own_Pressure_Cooker           own_Chairs            own_Sofas \n               0.072                0.429                0.017 \n          own_Tables          own_Cot_Bed        own_Cupboards \n               0.329                0.968                0.013 \n         own_Bicycle      own_Motor_Cycle own_Animal_Draw_Cart \n               0.524                0.065                0.004 \n             own_Car          own_Tractor         own_Computer \n               0.003                0.006                0.001 \n    own_Electric_Fan \n               0.110 \n```\n:::\n:::\n\n\n::: callout-tip\nBesides FSN, 10 variables have a value between 5-95% (0.05-0.95) \n::: \n\n\n2.3 We are going to create a new subset with only in those variables whose mean have a value between 5-95% (0.05-0.95)\n\n\n\n::: {.cell hash='Data-Analysis-Wk2_cache/pdf/unnamed-chunk-8_1ea7333a513837917e76f5c5ba4f9a2b'}\n\n```{.r .cell-code .numberLines}\nassets2 <- subset(assets, select = c(FSN, own_Radio,own_Mobile, own_Sewing_Machine, own_Watch, own_Pressure_Cooker, own_Chairs, own_Tables, own_Bicycle, own_Motor_Cycle, own_Electric_Fan))\nstr(assets2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t13377 obs. of  11 variables:\n $ FSN                : int  45001 45002 45003 45004 45005 45006 45007 45008 45009 45010 ...\n $ own_Radio          : num  1 1 0 0 0 0 0 0 0 0 ...\n $ own_Mobile         : num  0 0 0 0 0 1 0 0 0 0 ...\n $ own_Sewing_Machine : num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Watch          : num  0 0 0 0 0 1 0 0 0 0 ...\n $ own_Pressure_Cooker: num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Chairs         : num  1 0 0 0 1 1 0 0 1 0 ...\n $ own_Tables         : num  0 0 0 0 0 1 0 0 0 0 ...\n $ own_Bicycle        : num  1 1 1 0 0 1 0 0 1 0 ...\n $ own_Motor_Cycle    : num  0 0 0 0 0 0 0 0 0 0 ...\n $ own_Electric_Fan   : num  0 0 0 0 0 0 0 0 0 0 ...\n```\n:::\n\n```{.r .cell-code .numberLines}\n#round(sapply(assets2, FUN=mean),3)  \n```\n:::\n\n\n\n\n\n#### 3. Adding brick wall variable\n\nThe researchers noticed that having a \"brick_wall\" variable is important, so we need to incorporate it. The only problem is that the brick_wall information is in another dataset.\n\n\n3.1 Opening Q1_B dataset\n\n\n::: {.cell hash='Data-Analysis-Wk2_cache/pdf/unnamed-chunk-9_13af0eddcb8f68de88d35cf589421a4c'}\n\n```{.r .cell-code .numberLines}\nQ1_B <- read.csv(\"C:/Users/pined/OneDrive - Universidad Nacional Mayor de San Marcos/Javier 2022/Belgica/AC2_DataAnalysis_ThWk/Material/Q1_B.csv\", sep=\",\", dec= \".\")\n```\n:::\n\n\n\n3.2 Checking the variable Wall_Material in the Q1_B dataset\n\n\n::: {.cell hash='Data-Analysis-Wk2_cache/pdf/unnamed-chunk-10_6b615c149e46bf3fc73aede7cc00ba3a'}\n\n```{.r .cell-code .numberLines}\ntable(Q1_B$Wall_Material)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   6  162  163  164  165  166 \n   4 4498  169 5791 2914    1 \n```\n:::\n:::\n\n\n::: callout-tip\nAccording the code list:\n\n    6= Other\n    163= Grass\n    163= Bamboo\n    164, 165, 166= Brick\n\nSo we only need those who had the value 164 or 165 in the Wall_Material variable\n::: \n\n3.3. I only need \"FSN\" and \"WallMaterial\" variables\n\n\n::: {.cell hash='Data-Analysis-Wk2_cache/pdf/unnamed-chunk-11_5f1d6f495b8ac39e6567a17ed148274e'}\n\n```{.r .cell-code .numberLines}\nhlp2 <- subset(Q1_B, select = c(FSN, Wall_Material))\n```\n:::\n\n\n\n3.4  Creating a new variable called brickwall according to what I need\n\n\n::: {.cell hash='Data-Analysis-Wk2_cache/pdf/unnamed-chunk-12_a4ae735611b3160d9a9ce975d4030cf6'}\n\n```{.r .cell-code .numberLines}\nhlp2$brick_wall <- NA\nhlp2$brick_wall[hlp2$Wall_Material %in% c(6,162,163)] <- 0\nhlp2$brick_wall[hlp2$Wall_Material %in% c(164:166)] <- 1\n\ntable(hlp2$brick_wall, Q1_B$Wall_Material)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   \n       6  162  163  164  165  166\n  0    4 4498  169    0    0    0\n  1    0    0    0 5791 2914    1\n```\n:::\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}